In [1]:
import psycopg2
import os
import pandas as pd
import ast
import re

from tqdm import tqdm
from dotenv import load_dotenv
load_dotenv()
pd.set_option('display.max_rows', 100000)
pd.set_option("max_colwidth", 500)
KEY_POSTGRES = os.getenv("KEY_POSTGRES")

In [ ]:
def counter_hits(df):
    total_len_man = 0
    total_len_db = 0
    
    for row in df.index:
        total_len_db += len(df.at[row,"Institutions_db_name"])
        try:
            total_len_man += len(ast.literal_eval(df.at[row,"Institutions_man"]))
        except:
            continue

    return(total_len_man, total_len_db)

In [2]:
DF_input = input().strip()

 C:\Users\svalb\OneDrive\Escritorio\Data_40_years_cancer_studies\preparedInstitutionsTestDatabaseAccess.csv

In [3]:
df = pd.read_csv(DF_input)

In [18]:
# Create empty columns
df['Institutions_db_id'] = [[] for _ in range(len(df))]
df['Institutions_db_name'] = [[] for _ in range(len(df))]
df['Countries_db_country'] = [[] for _ in range(len(df))]

# Open ONE connection
connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)
cursor = connection.cursor()

for row in tqdm(range(len(df))):
    found_institutions = []

    if pd.isna(df.at[row, "NER_BERT"]):    
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = [ner.get('word') for ner in ner_results if ner.get('entity_group') == 'SUBC']
    cou_ner_results = [ner.get('word') for ner in ner_results if ner.get('entity_group') == 'COU']

    for ner in ner_results:
        if ner.get('entity_group') != 'INS':
            continue
    
        query = ner.get('word')

        if '\'' in query:
            query = re.sub("\'", "\'\'", query)
        
        # PARAMETERIZED QUERY
        cursor.execute(
            "SELECT institution_id, name FROM institution_names WHERE name = %s;",
            (query,)
        )
        records = cursor.fetchall()

        candidates = {
            el[0]: el[1]
            for el in records
        }


        # -------------------------
        # ---- ONE EXACT MATCH ----
        # -------------------------

        if len(candidates) == 1:
            new_query = list(candidates.keys())[0]
    
            cursor.execute(
                "SELECT country_name FROM institution_locations WHERE institution_id = %s;",
                (new_query,)
            )
            
            location_records = cursor.fetchall()
    
            if location_records:
                found_institutions.append((new_query, list(candidates.values())[0], location_records[0][0]))
                continue


        # -------------------------------------
        # ---- NO MATCHES, TRY FUZZY MATCH ----
        # -------------------------------------

        elif len(candidates) == 0:
            # Call the database again with a fuzzy string match
            cursor.execute(
                "SELECT institution_id, name FROM institution_names WHERE levenshtein(name, %s) <= 2;",
                (query,)
            )
            records = cursor.fetchall()
            
            candidates = {
                el[0]: el[1]
                for el in records
            }
            

            # -------------------------
            # ---- ONE FUZZY MATCH ----
            # -------------------------

            if len(candidates) == 1:
                
                # Find related country via institution_locations
                new_query = list(candidates.keys())[0]
    
                cursor.execute(
                    "SELECT city_name, country_name, subdivision_name FROM institution_locations WHERE institution_id = %s;",
                    (new_query,)
                )
                location_records = cursor.fetchall()
    
                if location_records and (location_records[0][1] in cou_ner_results):
                    found_institutions.append((new_query, list(candidates.values())[0], location_records[0][0]))
                    continue

                elif location_records and ((location_records[0][0] in subc_ner_results) or (location_records[0][2] in subc_ner_results)):
                    found_institutions.append((new_query, list(candidates.values())[0], location_records[0][0]))
                    continue
                else:
                    continue


            # -----------------------------------
            # ---- NO FUZZY MATCHES, GIVE UP ----
            # -----------------------------------

            elif len(candidates) == 0:
                continue

            
            # ------------------------------------------------------------------------------
            # ---- MULTIPLE FUZZY MATCHES, TRY DISAMBIGUATION VIA COUNTRY OR SUBCOUNTRY ----
            # ------------------------------------------------------------------------------

            elif len(candidates) > 1:
                matching_candidates = []

                for inst_id, inst_name in candidates.items():
                    new_query = inst_id    

                    cursor.execute(
                        "SELECT city_name, country_name, subdivision_name FROM institution_locations WHERE institution_id = %s;",
                        (new_query,)
                    )

                    location_records = cursor.fetchall()

                    if location_records and (location_records[0][1] in cou_ner_results):
                        matching_candidates.append((inst_id, 
                                                    inst_name,
                                                    location_records[0][0]))
                    
                    elif location_records and ((location_records[0][0] in subc_ner_results) or (location_records[0][2] in subc_ner_results)):
                        matching_candidates.append((inst_id, 
                                                    inst_name,
                                                    location_records[0][0]))
                    

                if len(matching_candidates) == 1:
                    found_institutions.append(matching_candidates[0])

                # Grow here to add dissambiguation via hierarchies of institutions



        # ------------------------------------------------------------------------------
        # ---- MULTIPLE EXACT MATCHES, TRY DISAMBIGUATION VIA COUNTRY OR SUBCOUNTRY ----
        # ------------------------------------------------------------------------------
        
        elif len(candidates) > 1:
            matching_candidates = []

            for inst_id, inst_name in candidates.items():
                new_query = inst_id    


                cursor.execute(
                    "SELECT city_name, country_name, subdivision_name FROM institution_locations WHERE institution_id = %s;",
                    (new_query,)
                )

                location_records = cursor.fetchall()

                if location_records and (location_records[0][1] in cou_ner_results):
                    matching_candidates.append((new_query,
                                                inst_name,
                                                location_records[0][0]))
                    
                elif location_records and ((location_records[0][0] in subc_ner_results) or (location_records[0][2] in subc_ner_results)):
                    matching_candidates.append((new_query, 
                                                inst_name,
                                                location_records[0][0]))
                    

            if len(matching_candidates) == 1:
                found_institutions.append(matching_candidates[0])

            # Grow here to add dissambiguation via hierarchies of institutions


    
    if found_institutions:
        found_institutions = list(set(found_institutions))
        ids, names, countries = zip(*found_institutions)

        df.at[row, 'Institutions_db_id'] = list(ids)
        df.at[row, 'Institutions_db_name'] = list(names)
        df.at[row, 'Countries_db_country'] = list(countries)


cursor.close()
connection.close()

100%|████████████████████████████████████████████████████████████████████████████████| 103/103 [03:17<00:00,  1.91s/it]

# Optimization of country queries

In [26]:
# Pre-create result columns
df['Institutions_db_id'] = [[] for _ in range(len(df))]
df['Institutions_db_name'] = [[] for _ in range(len(df))]
df['Countries_db_country'] = [[] for _ in range(len(df))]

connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)

cursor = connection.cursor()

for row in tqdm(range(len(df))):

    if pd.isna(df.at[row, "NER_BERT"]):
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'SUBC'
    }

    cou_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'COU'
    }

    found_institutions = []

    for ner in ner_results:

        if ner.get('entity_group') != 'INS':
            continue

        query = ner.get('word')

        # -----------------------
        # EXACT MATCH QUERY
        # -----------------------

        cursor.execute(
            "SELECT institution_id, name FROM institution_names WHERE name = %s;",
            (query,)
        )

        records = cursor.fetchall()

        candidates = {r[0]: r[1] for r in records}

        # =========================
        # EXACT MATCH: ONE
        # =========================

        if len(candidates) == 1:

            inst_id = next(iter(candidates))

            cursor.execute(
                "SELECT country_name FROM institution_locations WHERE institution_id = %s;",
                (inst_id,)
            )

            location = cursor.fetchone()

            if location:
                found_institutions.append(
                    (inst_id, candidates[inst_id], location[0])
                )

            continue

        # =========================
        # EXACT MATCH: MULTIPLE
        # =========================

        elif len(candidates) > 1:

            candidate_ids = list(candidates.keys())

            cursor.execute(
                """
                SELECT institution_id, city_name, country_name, subdivision_name
                FROM institution_locations
                WHERE institution_id = ANY(%s);
                """,
                (candidate_ids,)
            )

            location_rows = cursor.fetchall()

            location_map = {
                r[0]: r[1:] for r in location_rows
            }

            matching_candidates = []

            for inst_id, inst_name in candidates.items():

                if inst_id not in location_map:
                    continue

                city, country, subdivision = location_map[inst_id]

                if country in cou_ner_results:
                    matching_candidates.append(
                        (inst_id, inst_name, country)
                    )

                elif city in subc_ner_results or subdivision in subc_ner_results:
                    matching_candidates.append(
                        (inst_id, inst_name, country)
                    )

            if len(matching_candidates) == 1:
                found_institutions.append(matching_candidates[0])

            continue

        # =========================
        # EXACT MATCH: ZERO → FUZZY
        # =========================

        elif len(candidates) == 0:

            cursor.execute(
                """
                SELECT institution_id, name
                FROM institution_names
                WHERE levenshtein(name, %s) <= 2;
                """,
                (query,)
            )

            records = cursor.fetchall()

            candidates = {r[0]: r[1] for r in records}

            # -------------------
            # FUZZY: ONE
            # -------------------

            if len(candidates) == 1:

                inst_id = next(iter(candidates))

                cursor.execute(
                    """
                    SELECT city_name, country_name, subdivision_name
                    FROM institution_locations
                    WHERE institution_id = %s;
                    """,
                    (inst_id,)
                )

                location = cursor.fetchone()

                if location:

                    city, country, subdivision = location

                    if (
                        country in cou_ner_results
                        or city in subc_ner_results
                        or subdivision in subc_ner_results
                    ):
                        found_institutions.append(
                            (inst_id, candidates[inst_id], country)
                        )

                continue

            # -------------------
            # FUZZY: MULTIPLE
            # -------------------

            elif len(candidates) > 1:

                candidate_ids = list(candidates.keys())

                cursor.execute(
                    """
                    SELECT institution_id, city_name, country_name, subdivision_name
                    FROM institution_locations
                    WHERE institution_id = ANY(%s);
                    """,
                    (candidate_ids,)
                )

                location_rows = cursor.fetchall()

                location_map = {
                    r[0]: r[1:] for r in location_rows
                }

                matching_candidates = []

                for inst_id, inst_name in candidates.items():

                    if inst_id not in location_map:
                        continue

                    city, country, subdivision = location_map[inst_id]

                    if country in cou_ner_results:
                        matching_candidates.append(
                            (inst_id, inst_name, country)
                        )

                    elif city in subc_ner_results or subdivision in subc_ner_results:
                        matching_candidates.append(
                            (inst_id, inst_name, country)
                        )

                if len(matching_candidates) == 1:
                    found_institutions.append(matching_candidates[0])

                continue

            # -------------------
            # FUZZY: ZERO
            # -------------------

            elif len(candidates) == 0:
                continue

    # =========================
    # WRITE RESULTS
    # =========================

    if found_institutions:
        found_institutions = list(set(found_institutions))
        
        ids, names, countries = zip(*found_institutions)

        df.at[row, 'Institutions_db_id'] = list(ids)
        df.at[row, 'Institutions_db_name'] = list(names)
        df.at[row, 'Countries_db_country'] = list(countries)

cursor.close()
connection.close()

100%|████████████████████████████████████████████████████████████████████████████████| 103/103 [02:50<00:00,  1.66s/it]

In [28]:
df[["Institutions_man", "Institutions_db_name"]]

,Institutions_man,Institutions_db_name
0,NaN,[]
1,NaN,[]
2,"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of British Columbia, University of Porto]"
3,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[Cincinnati Children's Hospital Medical Center, Children's Healthcare of Atlanta, University of Cincinnati, Emory University]"
4,"['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[University of Chicago, Stephenson Cancer Center, University of Memphis, University of Pennsylvania, University of Buffalo, Battelle Memorial Institute, University of Oklahoma Health Sciences Center, Rutgers Biomedical and Health Sciences]"
5,"['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[CONAHCYT, Universidad Nacional Autónoma de México]"
6,"['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[Inserm, Centre de Recherche en Cancérologie de Toulouse, Curium, CNRS, ANR]"
7,['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University]
8,"['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw]
9,"['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']",[Chang Gung University]
10,"['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']",[Ruhr University Bochum]
11,"['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[IRCCS Ospedale San Raffaele, Vita-Salute San Raffaele University]"
12,"['University of Adelaide', 'Queen Elizabeth Hospital']","[Queen Elizabeth Hospital, University of Adelaide]"
13,['University of Zimbabwe'],[University of Zimbabwe]
14,['University of Tokyo Hospital'],[University of Tokyo Hospital]
15,['University Hospital Centre of Grenoble'],[]
16,['Harvard'],[]
17,['University of Washington'],[University of Washington]
18,['University of Würzburg'],[University of Würzburg]
19,"['Mannheim Medical Center', 'University of Heidelberg']",[]
20,NaN,[]
21,['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology]
22,['Duke University Medical Center'],[]
23,"['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]",[Liverpool Women's Hospital]
24,['University of Rochester'],[University of Rochester]
25,['Stavanger University Hospital'],[Stavanger University Hospital]
26,['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[]
27,['Akademii Medycznej w Gdańsku'],[]
28,['Vienna Medical University'],[]
29,"['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]"
30,NaN,[]
31,"['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University]
32,"['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital]
33,"['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University]
34,NaN,[]
35,['Royal North Brisbane Hospital'],[]
36,['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[]
37,['Universitá degli Studi di Palermo'],[Università degli Studi di Palermo]
38,['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf]
39,NaN,[]
40,"['Institute of Medical Microbiology', 'Charles University']",[Charles University]
41,['Queensland Institute of Medical Research'],[Queensland Institute of Medical Research]
42,['University of Porto'],[University of Porto]
43,"['University of Liverpool', 'Linda McCartney Centre', 'Royal Liverpool University Hospital']","[Royal Liverpool University Hospital, University of Liverpool]"
44,"['University of Leipzig Medical Center', 'University Medical Center Hamburg-Eppendorf', 'Institute for Medical Biostatistics, Epidemiology and Informatics', 'University of Mainz Medical Center', 'University Hospital of Essen', ""Children's Hospital""]","[Kantonsspital St. Gallen, University Medical Center Göttingen, University Hospital of Bern, University Medical Center Hamburg-Eppendorf, University of Würzburg]"
45,"['Northwestern Memorial Hospital', 'Robert H. Lurie Comprehensive Cancer Center', 'Northwestern University']","[Northwestern Memorial Hospital, Robert H. Lurie Comprehensive Cancer Center, Northwestern University]"
46,"['First Affiliated Hospital', 'Nanchang University']",[First Affiliated Hospital of Nanchang University]
47,"['Suzhou Municipal Hospital', 'Affiliated Suzhou Hospital', 'Nanjing Medical University', ""Shaoxing People's Hospital"", 'Shaoxing Hospital', 'Zhejiang University']","[Shaoxing People's Hospital, Suzhou Municipal Hospital]"
48,NaN,[]
49,NaN,[]
50,"['Institute of Biomedical and Genetic Engineering (IBGE)', 'International Islamic University']",[]
51,"['Istanbul University', 'Institute of Experimental Medicine', 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital']","[Istanbul University, Yeditepe University]"
52,NaN,[]
53,NaN,[]
54,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', 'Cancer and Blood Disease Institute', ""Boston Children's Hospital"", 'Harvard']","[Cincinnati Children's Hospital Medical Center, University of Cincinnati]"
55,"['Erasmus MC', 'Utrecht University', 'Erasmus MC Cancer Institute']","[Erasmus MC Cancer Institute, Utrecht University, Erasmus MC]"
56,NaN,[]
57,NaN,[]
58,"['Queen Elizabeth Hospital', 'Royal Victoria Infirmary', 'Medical Research Council Clinical Trials Unit', 'University College London']","[Medical Research Council, Royal Victoria Infirmary, University College London]"
59,"['Centro Nacional de Investigaciones Oncológicas (CNIO)', 'Center for Molecular Biology of Heidelberg University (ZMBH)', 'Centro de Investigación en Red de Enfermedades Neurodegenerativas (CIBERNED)', 'University of Cantabria', 'IDIVAL', 'Center for Biomedicine and Medical Technology Mannheim (CBTM)', 'Heidelberg University', 'German Cancer Research Center (DKFZ)', 'Hope Center for Neurological Diseases', 'Washington University']","[Heidelberg University, IDIVAL, DKFZ-ZMBH Alliance, University of Cantabria]"
60,"[""King's College London"", 'Comprehensive Biomedical Research Centre', ""Guy's and St Thomas NHS Foundation Trust"", 'Uppsala University', 'Medical Products Agency', 'Karolinska Insituet']","[Uppsala University, King's College London, Karolinska Institutet, Medical Products Agency]"
61,"['August Pi i Sunyer Biomedical Research Institute', 'Hospital Clínic', 'Sant Joan de Deu Childrens Hospital', 'University of Barcelona', 'Nihon University School of Medicine', 'University of Lausanne', 'University of Pennsylvania', 'Catalan Institution for Research and Advanced Studies']","[University of Pennsylvania, University of Barcelona, Nihon University]"
62,['Delhi State Cancer Institute'],[Delhi State Cancer Institute]
63,"['Kushiro Rosai Hospital', 'Kanagawa Cancer Center', 'Keio University', 'Sapporo Medical University', 'Hijirigaoka Hospital', 'National Hospital Organization', 'Osaka National Hospital', 'Hiroshima University', 'University of Tokyo', 'Tokai Central Hospital', 'Translational Research and Clinical Trial Center', 'Hokkaido University Hospital', 'Japanese Foundation for Multidisciplinary Treatment of Cancer']","[Hiroshima University, Kushiro Rosai Hospital, Keio University, Osaka National Hospital, National Hospital Organization, Hokkaido University Hospital, Japanese Foundation for Multidisciplinary Treatment of Cancer, Tokai Central Hospital, Sapporo Medical University, Kanagawa Cancer Center]"
64,['Life Raft Group'],[]
65,['Washington State University'],[Washington State University]
66,"['Addis Ababa University', 'Karolinska Institutet', 'Karolinska University Hospital', 'Center for Innovative Drug Development and Therapeutic Trials', 'Armauer Hansen Research Institute']","[Karolinska University Hospital, Karolinska Institutet, Addis Ababa University, Armauer Hansen Research Institute]"
67,[nan],[]
68,"['Tulane University', 'Louisiana State University Health Sciences Center']",[Tulane University]
69,"['Hebei Medical University', 'Bethune International Peace Hospital', 'Hebei University of Chinese Medicine']","[Bethune International Peace Hospital, Hebei Medical University, Hebei University of Chinese Medicine]"
70,"[""Henan Provincial People's Hospital"", ""Zhengzhou University People's Hospital"", ""Henan University People's Hospital"", 'Institute of Hematology']",[Henan Provincial People's Hospital]
71,"['Huazhong University of Science and Technology Union Shenzhen Hospital (Nanshan Hospital)', ""Shenzhen Second People's Hospital"", 'First Affiliated Hospital', 'Shenzhen University']","[Huazhong University of Science and Technology, Shenzhen Second People's Hospital]"
72,['Medical University of Innsbruck'],[]
73,"['Stanton L. Young Biomedical Research Center', 'University of Oklahoma Health Science Center']",[University of Oklahoma Health Sciences Center]
74,"['Center for Bioengineering and Tissue Regeneration', 'University of California', 'Gladstone Institutes', 'Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research', 'Helen Diller Family Comprehensive Cancer Center']",[Gladstone Institutes]
75,"['Northwestern University', 'Robert H. Lurie Comprehensive Cancer Center']",[Robert H. Lurie Comprehensive Cancer Center]
76,"['Qilu Hospital', 'Shandong University', 'Central Hospital', 'Zaozhuang Coal Mining Group', 'Jinan integrative medicine hospital']",[Qilu Hospital of Shandong University]
77,"[""St. Jude Children's Research Hospital"", 'Cornell', 'University of Chicago', 'Howard Hughes Medical Institute']","[University of Chicago, Howard Hughes Medical Institute, Weill Cornell Medicine, St. Jude Children's Research Hospital]"
78,['Baylor College of Medicine'],[Baylor College of Medicine]
79,['University of California'],[]
80,NaN,[]
81,NaN,[]
82,"['Second Affiliated Hospital', 'Fujian Medical University', 'Nanjing Medical University']","[Nanjing Medical University, Second Affiliated Hospital of Fujian Medical University]"
83,"['Universidade de São Paulo', 'Universidade do Oeste Paulista UNOESTE', 'Center of Translational Research in Oncology (LIM24)', 'Instituto do Cancer do Estado de Sao Paulo (ICESP)']",[Universidade de São Paulo]
84,"['Hepatic Surgery Center', 'Tongji Hospital', 'Huazhong University of Science and Technology', 'Shanxi Bethune Hospital', 'Shanxi Academy of Medical Sciences', 'Shanxi Medical University', 'Shanxi Tongji Hospital']","[Huazhong University of Science and Technology, Shanxi Medical University, Shanxi Academy of Medical Sciences, Tongji Hospital]"
85,"['Centre de Recherche des Cordeliers', 'INSERM', 'Sorbonne Université', 'Université Paris Cité', 'Institut universitaire de France', 'Institut Gustave Roussy', 'Centre de Recherche des Cordeliers', 'Klinikum Rechts der Isar', 'Technical University of Munich', 'Institute of Biophysics', 'Czech Academy of Sciences', 'CNRS', 'Institut Polytechnique de Paris', 'Université Paris-Saclay', 'Université Sorbonne Paris Nord', 'Institut du Cancer Paris CARPEM', 'Hôpital Européen Georges Pompidou']","[Institut Polytechnique de Paris, Université Paris Cité, CNRS, Université Sorbonne Paris Nord, Université Paris-Saclay, Institut Universitaire de France, École Polytechnique, INSERM, Czech Academy of Sciences, Institut Gustave Roussy, Klinikum rechts der Isar, Centre de Recherche des Cordeliers, Hôpital Européen Georges-Pompidou, Sorbonne Université, Technical University of Munich]"
86,"['Norwegian University of Science and Technology', 'St. Olavs Hospital', 'Center for Oral Health Services and Research Mid-Norway (TkMidt)', 'Clinic of Medicine', 'K.G. Jebsen Centre for Genetic Epidemiology']",[Norwegian University of Science and Technology]
87,['Mayo Clinic'],[Mayo Clinic]
88,"['University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca', 'Biotechnology Research Center', 'Life Sciences Institute King Michael I of Romania', 'Babeș-Bolyai University']","[Babeș-Bolyai University, Biotechnology Research Center, University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca]"
89,"['Graduate Institute of Biomedical Science', 'China Medical University', 'Taichung Tzu Chi Hospital', 'Buddhist Tzu Chi Medical Foundation', 'China Medical University Hospital', 'Asia University', 'Institute of New Drug Development']","[China Medical University Hospital, China Medical University, Tzu Chi University, Buddhist Tzu Chi Medical Foundation]"
90,"['Chongqing University Three Gorges Hospital', 'Center for Medicine Research and Translation', ""Chengdu Fifth People's Hospital""]",[Chengdu Fifth People's Hospital]
91,"['Boston University', 'Shaukat Khanum Memorial Cancer Hospital and Research Centre']","[Boston University, Shaukat Khanum Memorial Cancer Hospital and Research Center]"
92,NaN,[]
93,NaN,[]
94,['Georgetown University Medical Center'],[Georgetown University Medical Center]
95,['University of South Florida'],[University of South Florida]
96,['Johns Hopkins Oncology Center'],[]
97,"['Albert Einstein Cancer Center', 'Montefiore Medical Center']",[Montefiore Medical Center]
98,['General Hospital Manuel Gea Gonzalez'],[]
99,['University Hospital Leiden'],[]
100,['Paul Scherrer Institute'],[Paul Scherrer Institute]
101,['Wayne State University'],[Wayne State University]
102,[],[]

# Trigram similarities

In [36]:
# -----------------------
# CACHE (LRU size = 1000)
# -----------------------

CACHE_SIZE = 1000
institution_cache = OrderedDict()

# -----------------------
# PRE-CREATE RESULT COLUMNS
# -----------------------

df['Institutions_db_id'] = [[] for _ in range(len(df))]
df['Institutions_db_name'] = [[] for _ in range(len(df))]
df['Countries_db_country'] = [[] for _ in range(len(df))]

# -----------------------
# DB CONNECTION
# -----------------------

connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)

cursor = connection.cursor()

# -----------------------
# LOAD DATABASE TABLES INTO MEMORY
# -----------------------

print("Loading institution_names...")
cursor.execute("SELECT institution_id, name FROM institution_names")
rows = cursor.fetchall()

name_index = {}
for inst_id, name in rows:
    name_index.setdefault(name, []).append((inst_id, name))

print("Loading institution_locations...")
cursor.execute("""
    SELECT institution_id, city_name, country_name, subdivision_name
    FROM institution_locations
""")

rows = cursor.fetchall()

location_index = {
    r[0]: (r[1], r[2], r[3])
    for r in rows
}

print("Indices loaded.")

# -----------------------
# MAIN LOOP
# -----------------------

for row in tqdm(range(len(df))):

    if pd.isna(df.at[row, "NER_BERT"]):
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'SUBC'
    }

    cou_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'COU'
    }

    found_institutions = []

    for ner in ner_results:

        if ner.get('entity_group') != 'INS':
            continue

        query = ner.get('word')

        # -----------------------
        # CACHE LOOKUP
        # -----------------------

        if query in institution_cache:

            ids, names, countries = institution_cache[query]

            for inst in zip(ids, names, countries):
                found_institutions.append(inst)

            institution_cache.move_to_end(query)

            continue

        # -----------------------
        # EXACT MATCH (IN MEMORY)
        # -----------------------

        records = name_index.get(query, [])
        candidates = {r[0]: r[1] for r in records}

        resolved = []

        # =========================
        # EXACT MATCH: ONE
        # =========================

        if len(candidates) == 1:

            inst_id = next(iter(candidates))

            location = location_index.get(inst_id)

            if location:
                city, country, subdivision = location
                resolved.append((inst_id, candidates[inst_id], country))

        # =========================
        # EXACT MATCH: MULTIPLE
        # =========================

        elif len(candidates) > 1:

            candidate_ids = list(candidates.keys())

            location_map = {
                inst_id: location_index[inst_id]
                for inst_id in candidate_ids
                if inst_id in location_index
            }

            matching_candidates = []

            for inst_id, inst_name in candidates.items():

                if inst_id not in location_map:
                    continue

                city, country, subdivision = location_map[inst_id]

                if country in cou_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

                elif city in subc_ner_results or subdivision in subc_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

            if len(matching_candidates) == 1:
                resolved.append(matching_candidates[0])

        # =========================
        # EXACT MATCH: ZERO → FUZZY
        # =========================

        elif len(candidates) == 0:

            cursor.execute(
                """
                SELECT institution_id, name
                FROM institution_names
                WHERE similarity(name, %s) > 0.6
                """,
                (query,)
            )

            records = cursor.fetchall()
            candidates = {r[0]: r[1] for r in records}

            # -------------------
            # FUZZY: ONE
            # -------------------

            if len(candidates) == 1:

                inst_id = next(iter(candidates))
                location = location_index.get(inst_id)

                if location:

                    city, country, subdivision = location

                    if (
                        country in cou_ner_results
                        or city in subc_ner_results
                        or subdivision in subc_ner_results
                    ):
                        resolved.append((inst_id, candidates[inst_id], country))

            # -------------------
            # FUZZY: MULTIPLE
            # -------------------

            elif len(candidates) > 1:

                candidate_ids = list(candidates.keys())

                location_map = {
                    inst_id: location_index[inst_id]
                    for inst_id in candidate_ids
                    if inst_id in location_index
                }

                matching_candidates = []

                for inst_id, inst_name in candidates.items():

                    if inst_id not in location_map:
                        continue

                    city, country, subdivision = location_map[inst_id]

                    if country in cou_ner_results:
                        matching_candidates.append((inst_id, inst_name, country))

                    elif city in subc_ner_results or subdivision in subc_ner_results:
                        matching_candidates.append((inst_id, inst_name, country))

                if len(matching_candidates) == 1:
                    resolved.append(matching_candidates[0])

        # -----------------------
        # STORE IN CACHE
        # -----------------------

        if resolved:

            ids, names, countries = zip(*resolved)

            institution_cache[query] = (list(ids), list(names), list(countries))

            if len(institution_cache) > CACHE_SIZE:
                institution_cache.popitem(last=False)

            for inst in resolved:
                found_institutions.append(inst)

    # =========================
    # WRITE RESULTS
    # =========================

    if found_institutions:

        found_institutions = list(set(found_institutions))

        ids, names, countries = zip(*found_institutions)

        df.at[row, 'Institutions_db_id'] = list(ids)
        df.at[row, 'Institutions_db_name'] = list(names)
        df.at[row, 'Countries_db_country'] = list(countries)

cursor.close()
connection.close()

Loading institution_names...
Loading institution_locations...
Indices loaded.

100%|████████████████████████████████████████████████████████████████████████████████| 103/103 [07:47<00:00,  4.54s/it]

In [37]:
df[["Institutions_man", "Institutions_db_name"]]

,Institutions_man,Institutions_db_name
0,NaN,[]
1,NaN,[]
2,"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of British Columbia, University of Porto, i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto]"
3,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[Cincinnati Children's Hospital Medical Center, Children's Healthcare of Atlanta, University of Cincinnati, Emory University]"
4,"['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[University of Chicago, Stephenson Cancer Center, University of Memphis, University of Pennsylvania, Battelle Memorial Institute, University of Oklahoma Health Sciences Center, Rutgers Biomedical and Health Sciences]"
5,"['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[CONAHCYT, Universidad Nacional Autónoma de México]"
6,"['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[Inserm, University Cancer Institute Toulouse Oncopole, CNRS, ANR]"
7,['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University]
8,"['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw]
9,"['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']",[Chang Gung University]
10,"['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']","[BG University Hospital Bergmannsheil Bochum, Ludwig-Maximilians-Universität in Munich, Ruhr University Bochum, Medical Genetics Center]"
11,"['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[IRCCS Ospedale San Raffaele, Vita-Salute San Raffaele University]"
12,"['University of Adelaide', 'Queen Elizabeth Hospital']","[Queen Elizabeth Hospital, University of Adelaide]"
13,['University of Zimbabwe'],[University of Zimbabwe]
14,['University of Tokyo Hospital'],[University of Tokyo Hospital]
15,['University Hospital Centre of Grenoble'],[]
16,['Harvard'],[]
17,['University of Washington'],[University of Washington]
18,['University of Würzburg'],[University of Würzburg]
19,"['Mannheim Medical Center', 'University of Heidelberg']",[]
20,NaN,[]
21,['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology]
22,['Duke University Medical Center'],[]
23,"['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]",[]
24,['University of Rochester'],[University of Rochester]
25,['Stavanger University Hospital'],[Stavanger University Hospital]
26,['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[]
27,['Akademii Medycznej w Gdańsku'],[]
28,['Vienna Medical University'],[]
29,"['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]"
30,NaN,[]
31,"['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University]
32,"['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital]
33,"['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University]
34,NaN,[]
35,['Royal North Brisbane Hospital'],[]
36,['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[Azienda Ospedaliero Universitaria Maggiore della Carita]
37,['Universitá degli Studi di Palermo'],[]
38,['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf]
39,NaN,[]
40,"['Institute of Medical Microbiology', 'Charles University']","[Institute of Microbiology CAS, Charles University]"
41,['Queensland Institute of Medical Research'],[Queensland Institute of Medical Research]
42,['University of Porto'],[University of Porto]
43,"['University of Liverpool', 'Linda McCartney Centre', 'Royal Liverpool University Hospital']","[Royal Liverpool University Hospital, University of Liverpool]"
44,"['University of Leipzig Medical Center', 'University Medical Center Hamburg-Eppendorf', 'Institute for Medical Biostatistics, Epidemiology and Informatics', 'University of Mainz Medical Center', 'University Hospital of Essen', ""Children's Hospital""]","[Cnopf Children's Hospital, Kantonsspital St. Gallen, University Medical Center Göttingen, Institute for Medical Informatics and Biostatistics, University Medical Center Freiburg, University Medical Center Hamburg-Eppendorf, University of Würzburg]"
45,"['Northwestern Memorial Hospital', 'Robert H. Lurie Comprehensive Cancer Center', 'Northwestern University']","[Northwestern Memorial Hospital, Robert H. Lurie Comprehensive Cancer Center, Northwestern University]"
46,"['First Affiliated Hospital', 'Nanchang University']",[First Affiliated Hospital of Nanchang University]
47,"['Suzhou Municipal Hospital', 'Affiliated Suzhou Hospital', 'Nanjing Medical University', ""Shaoxing People's Hospital"", 'Shaoxing Hospital', 'Zhejiang University']","[Children's Hospital of Zhejiang University, Suzhou Municipal Hospital]"
48,NaN,[]
49,NaN,[]
50,"['Institute of Biomedical and Genetic Engineering (IBGE)', 'International Islamic University']",[Institute of Biomedical and Genetic Engineering]
51,"['Istanbul University', 'Institute of Experimental Medicine', 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital']","[Istanbul University, Yeditepe University]"
52,NaN,[]
53,NaN,[]
54,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', 'Cancer and Blood Disease Institute', ""Boston Children's Hospital"", 'Harvard']","[Cincinnati Children's Hospital Medical Center, Boston Children's Museum, University of Cincinnati, IIT@Harvard]"
55,"['Erasmus MC', 'Utrecht University', 'Erasmus MC Cancer Institute']","[Erasmus MC Cancer Institute, Utrecht University, Erasmus MC]"
56,NaN,[]
57,NaN,[]
58,"['Queen Elizabeth Hospital', 'Royal Victoria Infirmary', 'Medical Research Council Clinical Trials Unit', 'University College London']","[Medical Research Council, Queen Elizabeth Hospital, Royal Victoria Infirmary, University College London]"
59,"['Centro Nacional de Investigaciones Oncológicas (CNIO)', 'Center for Molecular Biology of Heidelberg University (ZMBH)', 'Centro de Investigación en Red de Enfermedades Neurodegenerativas (CIBERNED)', 'University of Cantabria', 'IDIVAL', 'Center for Biomedicine and Medical Technology Mannheim (CBTM)', 'Heidelberg University', 'German Cancer Research Center (DKFZ)', 'Hope Center for Neurological Diseases', 'Washington University']","[IDIVAL, DKFZ-ZMBH Alliance, Center for Molecular Biology Severo Ochoa, University of Cantabria, Heidelberg University, Centro de Investigación Biomédica en Red, Enfermedades Neurodegenerativas]"
60,"[""King's College London"", 'Comprehensive Biomedical Research Centre', ""Guy's and St Thomas NHS Foundation Trust"", 'Uppsala University', 'Medical Products Agency', 'Karolinska Insituet']","[King's College London, UCL Biomedical Research Centre, Uppsala University, Guy's and St Thomas' NHS Foundation Trust, Karolinska Institutet, Medical Products Agency]"
61,"['August Pi i Sunyer Biomedical Research Institute', 'Hospital Clínic', 'Sant Joan de Deu Childrens Hospital', 'University of Barcelona', 'Nihon University School of Medicine', 'University of Lausanne', 'University of Pennsylvania', 'Catalan Institution for Research and Advanced Studies']","[Catalan Institution for Research and Advanced Studies, University of Pennsylvania, University of Barcelona, Nihon University, Sant Joan de Déu-Barcelona Children’s Hospital]"
62,['Delhi State Cancer Institute'],[Delhi State Cancer Institute]
63,"['Kushiro Rosai Hospital', 'Kanagawa Cancer Center', 'Keio University', 'Sapporo Medical University', 'Hijirigaoka Hospital', 'National Hospital Organization', 'Osaka National Hospital', 'Hiroshima University', 'University of Tokyo', 'Tokai Central Hospital', 'Translational Research and Clinical Trial Center', 'Hokkaido University Hospital', 'Japanese Foundation for Multidisciplinary Treatment of Cancer']","[Hiroshima University, Kushiro Rosai Hospital, Keio University, Osaka National Hospital, National Hospital Organization, Hokkaido University Hospital, Japanese Foundation for Multidisciplinary Treatment of Cancer, Tokai Central Hospital, Sapporo Medical University, Kanagawa Cancer Center]"
64,['Life Raft Group'],[]
65,['Washington State University'],[Washington State University]
66,"['Addis Ababa University', 'Karolinska Institutet', 'Karolinska University Hospital', 'Center for Innovative Drug Development and Therapeutic Trials', 'Armauer Hansen Research Institute']","[Karolinska University Hospital, Karolinska Institutet, Addis Ababa University, Armauer Hansen Research Institute]"
67,[nan],[]
68,"['Tulane University', 'Louisiana State University Health Sciences Center']","[Louisiana State University Health Sciences Center New Orleans, Tulane University]"
69,"['Hebei Medical University', 'Bethune International Peace Hospital', 'Hebei University of Chinese Medicine']","[Bethune International Peace Hospital, Hebei Medical University, Hebei University of Chinese Medicine]"
70,"[""Henan Provincial People's Hospital"", ""Zhengzhou University People's Hospital"", ""Henan University People's Hospital"", 'Institute of Hematology']",[]
71,"['Huazhong University of Science and Technology Union Shenzhen Hospital (Nanshan Hospital)', ""Shenzhen Second People's Hospital"", 'First Affiliated Hospital', 'Shenzhen University']",[Huazhong University of Science and Technology]
72,['Medical University of Innsbruck'],[]
73,"['Stanton L. Young Biomedical Research Center', 'University of Oklahoma Health Science Center']",[University of Oklahoma Health Sciences Center]
74,"['Center for Bioengineering and Tissue Regeneration', 'University of California', 'Gladstone Institutes', 'Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research', 'Helen Diller Family Comprehensive Cancer Center']","[UCSF Helen Diller Family Comprehensive Cancer Center, Gladstone Institutes, University of California, San Francisco]"
75,"['Northwestern University', 'Robert H. Lurie Comprehensive Cancer Center']","[Northwestern University, Robert H. Lurie Comprehensive Cancer Center]"
76,"['Qilu Hospital', 'Shandong University', 'Central Hospital', 'Zaozhuang Coal Mining Group', 'Jinan integrative medicine hospital']",[Qilu Hospital of Shandong University]
77,"[""St. Jude Children's Research Hospital"", 'Cornell', 'University of Chicago', 'Howard Hughes Medical Institute']","[University of Chicago, Weill Cornell Medicine, St. Jude Children's Research Hospital, Memphis Zoo, Howard Hughes Medical Institute]"
78,['Baylor College of Medicine'],[Baylor College of Medicine]
79,['University of California'],"[University of California, San Francisco]"
80,NaN,[]
81,NaN,[]
82,"['Second Affiliated Hospital', 'Fujian Medical University', 'Nanjing Medical University']","[Nanjing Medical University, Second Affiliated Hospital of Fujian Medical University]"
83,"['Universidade de São Paulo', 'Universidade do Oeste Paulista UNOESTE', 'Center of Translational Research in Oncology (LIM24)', 'Instituto do Cancer do Estado de Sao Paulo (ICESP)']","[Universidade de São Paulo, Instituto do Câncer do Estado de São Paulo]"
84,"['Hepatic Surgery Center', 'Tongji Hospital', 'Huazhong University of Science and Technology', 'Shanxi Bethune Hospital', 'Shanxi Academy of Medical Sciences', 'Shanxi Medical University', 'Shanxi Tongji Hospital']","[Bethune Second Hospital, Huazhong University of Science and Technology, Shanxi Medical University, Shanxi Academy of Medical Sciences, Tongji Hospital]"
85,"['Centre de Recherche des Cordeliers', 'INSERM', 'Sorbonne Université', 'Université Paris Cité', 'Institut universitaire de France', 'Institut Gustave Roussy', 'Centre de Recherche des Cordeliers', 'Klinikum Rechts der Isar', 'Technical University of Munich', 'Institute of Biophysics', 'Czech Academy of Sciences', 'CNRS', 'Institut Polytechnique de Paris', 'Université Paris-Saclay', 'Université Sorbonne Paris Nord', 'Institut du Cancer Paris CARPEM', 'Hôpital Européen Georges Pompidou']","[Institut Polytechnique de Paris, Université Paris Cité, CNRS, Université Sorbonne Paris Nord, Institut Universitaire de France, INSERM, Czech Academy of Sciences, Institut Gustave Roussy, Klinikum rechts der Isar, Centre de Recherche des Cordeliers, École Polytechnique, Sorbonne Université, Technical University of Munich]"
86,"['Norwegian University of Science and Technology', 'St. Olavs Hospital', 'Center for Oral Health Services and Research Mid-Norway (TkMidt)', 'Clinic of Medicine', 'K.G. Jebsen Centre for Genetic Epidemiology']",[Norwegian University of Science and Technology]
87,['Mayo Clinic'],[Mayo Clinic]
88,"['University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca', 'Biotechnology Research Center', 'Life Sciences Institute King Michael I of Romania', 'Babeș-Bolyai University']","[Biotechnology Research Center, Universitatea Babeș-Bolyai]"
89,"['Graduate Institute of Biomedical Science', 'China Medical University', 'Taichung Tzu Chi Hospital', 'Buddhist Tzu Chi Medical Foundation', 'China Medical University Hospital', 'Asia University', 'Institute of New Drug Development']","[China Medical University Hospital, China Medical University, Tzu Chi University, Buddhist Tzu Chi Medical Foundation]"
90,"['Chongqing University Three Gorges Hospital', 'Center for Medicine Research and Translation', ""Chengdu Fifth People's Hospital""]",[]
91,"['Boston University', 'Shaukat Khanum Memorial Cancer Hospital and Research Centre']","[Boston University, Shaukat Khanum Memorial Cancer Hospital and Research Center]"
92,NaN,[]
93,NaN,[]
94,['Georgetown University Medical Center'],[Georgetown University Medical Center]
95,['University of South Florida'],[University of South Florida]
96,['Johns Hopkins Oncology Center'],[]
97,"['Albert Einstein Cancer Center', 'Montefiore Medical Center']","[Albert Einstein Cancer Center at Montefiore, Montefiore Medical Center]"
98,['General Hospital Manuel Gea Gonzalez'],[Hospital General Dr. Manuel Gea Gonzalez]
99,['University Hospital Leiden'],[Leiden University]
100,['Paul Scherrer Institute'],[Paul Scherrer Institute]
101,['Wayne State University'],[Wayne State University]
102,[],[]

# 1.- Deduplicating NER words

In [39]:
from collections import OrderedDict
import psycopg2
import pandas as pd
import ast
import re
from tqdm import tqdm

# -----------------------
# CACHE (LRU size = 1000)
# -----------------------

CACHE_SIZE = 1000
institution_cache = OrderedDict()

# -----------------------
# PRE-CREATE RESULT COLUMNS
# -----------------------

df['Institutions_db_id'] = [[] for _ in range(len(df))]
df['Institutions_db_name'] = [[] for _ in range(len(df))]
df['Countries_db_country'] = [[] for _ in range(len(df))]

# -----------------------
# DB CONNECTION
# -----------------------

connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)

cursor = connection.cursor()

# -----------------------
# LOAD DATABASE TABLES INTO MEMORY
# -----------------------

print("Loading institution_names...")
cursor.execute("SELECT institution_id, name FROM institution_names")
rows = cursor.fetchall()

name_index = {}
for inst_id, name in rows:
    name_index.setdefault(name, []).append((inst_id, name))

print("Loading institution_locations...")
cursor.execute("""
    SELECT institution_id, city_name, country_name, subdivision_name
    FROM institution_locations
""")

rows = cursor.fetchall()

location_index = {
    r[0]: (r[1], r[2], r[3])
    for r in rows
}

print("Indices loaded.")

# -----------------------
# MAIN LOOP
# -----------------------

for row in tqdm(range(len(df))):

    if pd.isna(df.at[row, "NER_BERT"]):
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'SUBC'
    }

    cou_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'COU'
    }

    # -----------------------
    # UNIQUE INS WORDS (ORDER PRESERVED)
    # -----------------------

    seen_queries = set()
    ins_queries = []

    for ner in ner_results:

        if ner.get('entity_group') != 'INS':
            continue

        query = ner.get('word')

        if query not in seen_queries:
            seen_queries.add(query)
            ins_queries.append(query)

    found_institutions = []

    # -----------------------
    # LOOP OVER UNIQUE QUERIES
    # -----------------------

    for query in ins_queries:

        # -----------------------
        # CACHE LOOKUP
        # -----------------------

        if query in institution_cache:

            ids, names, countries = institution_cache[query]

            for inst in zip(ids, names, countries):
                found_institutions.append(inst)

            institution_cache.move_to_end(query)

            continue

        # -----------------------
        # EXACT MATCH (IN MEMORY)
        # -----------------------

        records = name_index.get(query, [])
        candidates = {r[0]: r[1] for r in records}

        resolved = []

        # =========================
        # EXACT MATCH: ONE
        # =========================

        if len(candidates) == 1:

            inst_id = next(iter(candidates))

            location = location_index.get(inst_id)

            if location:
                city, country, subdivision = location
                resolved.append((inst_id, candidates[inst_id], country))

        # =========================
        # EXACT MATCH: MULTIPLE
        # =========================

        elif len(candidates) > 1:

            candidate_ids = list(candidates.keys())

            location_map = {
                inst_id: location_index[inst_id]
                for inst_id in candidate_ids
                if inst_id in location_index
            }

            matching_candidates = []

            for inst_id, inst_name in candidates.items():

                if inst_id not in location_map:
                    continue

                city, country, subdivision = location_map[inst_id]

                if country in cou_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

                elif city in subc_ner_results or subdivision in subc_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

            if len(matching_candidates) == 1:
                resolved.append(matching_candidates[0])

        # =========================
        # EXACT MATCH: ZERO → FUZZY
        # =========================

        elif len(candidates) == 0:

            cursor.execute(
                """
                SELECT institution_id, name
                FROM institution_names
                WHERE similarity(name, %s) > 0.6
                """,
                (query,)
            )

            records = cursor.fetchall()
            candidates = {r[0]: r[1] for r in records}

            # -------------------
            # FUZZY: ONE
            # -------------------

            if len(candidates) == 1:

                inst_id = next(iter(candidates))
                location = location_index.get(inst_id)

                if location:

                    city, country, subdivision = location

                    if (
                        country in cou_ner_results
                        or city in subc_ner_results
                        or subdivision in subc_ner_results
                    ):
                        resolved.append((inst_id, candidates[inst_id], country))

            # -------------------
            # FUZZY: MULTIPLE
            # -------------------

            elif len(candidates) > 1:

                candidate_ids = list(candidates.keys())

                location_map = {
                    inst_id: location_index[inst_id]
                    for inst_id in candidate_ids
                    if inst_id in location_index
                }

                matching_candidates = []

                for inst_id, inst_name in candidates.items():

                    if inst_id not in location_map:
                        continue

                    city, country, subdivision = location_map[inst_id]

                    if country in cou_ner_results:
                        matching_candidates.append((inst_id, inst_name, country))

                    elif city in subc_ner_results or subdivision in subc_ner_results:
                        matching_candidates.append((inst_id, inst_name, country))

                if len(matching_candidates) == 1:
                    resolved.append(matching_candidates[0])

        # -----------------------
        # STORE IN CACHE
        # -----------------------

        if resolved:

            ids, names, countries = zip(*resolved)

            institution_cache[query] = (list(ids), list(names), list(countries))

            if len(institution_cache) > CACHE_SIZE:
                institution_cache.popitem(last=False)

            for inst in resolved:
                found_institutions.append(inst)

    # =========================
    # WRITE RESULTS
    # =========================

    if found_institutions:

        found_institutions = list(set(found_institutions))

        ids, names, countries = zip(*found_institutions)

        df.at[row, 'Institutions_db_id'] = list(ids)
        df.at[row, 'Institutions_db_name'] = list(names)
        df.at[row, 'Countries_db_country'] = list(countries)

cursor.close()
connection.close()

Loading institution_names...
Loading institution_locations...
Indices loaded.

100%|████████████████████████████████████████████████████████████████████████████████| 103/103 [06:50<00:00,  3.99s/it]

In [40]:
df[["Institutions_man", "Institutions_db_name"]]

,Institutions_man,Institutions_db_name
0,NaN,[]
1,NaN,[]
2,"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of British Columbia, University of Porto, i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto]"
3,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[Cincinnati Children's Hospital Medical Center, Children's Healthcare of Atlanta, University of Cincinnati, Emory University]"
4,"['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[University of Chicago, Stephenson Cancer Center, University of Memphis, University of Pennsylvania, Battelle Memorial Institute, University of Oklahoma Health Sciences Center, Rutgers Biomedical and Health Sciences]"
5,"['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[CONAHCYT, Universidad Nacional Autónoma de México]"
6,"['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[Inserm, University Cancer Institute Toulouse Oncopole, CNRS, ANR]"
7,['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University]
8,"['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw]
9,"['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']",[Chang Gung University]
10,"['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']","[BG University Hospital Bergmannsheil Bochum, Ludwig-Maximilians-Universität in Munich, Ruhr University Bochum, Medical Genetics Center]"
11,"['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[IRCCS Ospedale San Raffaele, Vita-Salute San Raffaele University]"
12,"['University of Adelaide', 'Queen Elizabeth Hospital']","[Queen Elizabeth Hospital, University of Adelaide]"
13,['University of Zimbabwe'],[University of Zimbabwe]
14,['University of Tokyo Hospital'],[University of Tokyo Hospital]
15,['University Hospital Centre of Grenoble'],[]
16,['Harvard'],[]
17,['University of Washington'],[University of Washington]
18,['University of Würzburg'],[University of Würzburg]
19,"['Mannheim Medical Center', 'University of Heidelberg']",[]
20,NaN,[]
21,['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology]
22,['Duke University Medical Center'],[]
23,"['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]",[]
24,['University of Rochester'],[University of Rochester]
25,['Stavanger University Hospital'],[Stavanger University Hospital]
26,['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[]
27,['Akademii Medycznej w Gdańsku'],[]
28,['Vienna Medical University'],[]
29,"['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]"
30,NaN,[]
31,"['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University]
32,"['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital]
33,"['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University]
34,NaN,[]
35,['Royal North Brisbane Hospital'],[]
36,['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[Azienda Ospedaliero Universitaria Maggiore della Carita]
37,['Universitá degli Studi di Palermo'],[]
38,['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf]
39,NaN,[]
40,"['Institute of Medical Microbiology', 'Charles University']","[Institute of Microbiology CAS, Charles University]"
41,['Queensland Institute of Medical Research'],[Queensland Institute of Medical Research]
42,['University of Porto'],[University of Porto]
43,"['University of Liverpool', 'Linda McCartney Centre', 'Royal Liverpool University Hospital']","[Royal Liverpool University Hospital, University of Liverpool]"
44,"['University of Leipzig Medical Center', 'University Medical Center Hamburg-Eppendorf', 'Institute for Medical Biostatistics, Epidemiology and Informatics', 'University of Mainz Medical Center', 'University Hospital of Essen', ""Children's Hospital""]","[Cnopf Children's Hospital, Kantonsspital St. Gallen, University Medical Center Göttingen, Institute for Medical Informatics and Biostatistics, University Medical Center Freiburg, University Medical Center Hamburg-Eppendorf, University of Würzburg]"
45,"['Northwestern Memorial Hospital', 'Robert H. Lurie Comprehensive Cancer Center', 'Northwestern University']","[Northwestern Memorial Hospital, Robert H. Lurie Comprehensive Cancer Center, Northwestern University]"
46,"['First Affiliated Hospital', 'Nanchang University']",[First Affiliated Hospital of Nanchang University]
47,"['Suzhou Municipal Hospital', 'Affiliated Suzhou Hospital', 'Nanjing Medical University', ""Shaoxing People's Hospital"", 'Shaoxing Hospital', 'Zhejiang University']","[Children's Hospital of Zhejiang University, Suzhou Municipal Hospital]"
48,NaN,[]
49,NaN,[]
50,"['Institute of Biomedical and Genetic Engineering (IBGE)', 'International Islamic University']",[Institute of Biomedical and Genetic Engineering]
51,"['Istanbul University', 'Institute of Experimental Medicine', 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital']","[Istanbul University, Yeditepe University]"
52,NaN,[]
53,NaN,[]
54,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', 'Cancer and Blood Disease Institute', ""Boston Children's Hospital"", 'Harvard']","[Cincinnati Children's Hospital Medical Center, Boston Children's Museum, University of Cincinnati, IIT@Harvard]"
55,"['Erasmus MC', 'Utrecht University', 'Erasmus MC Cancer Institute']","[Erasmus MC Cancer Institute, Utrecht University, Erasmus MC]"
56,NaN,[]
57,NaN,[]
58,"['Queen Elizabeth Hospital', 'Royal Victoria Infirmary', 'Medical Research Council Clinical Trials Unit', 'University College London']","[Medical Research Council, Queen Elizabeth Hospital, Royal Victoria Infirmary, University College London]"
59,"['Centro Nacional de Investigaciones Oncológicas (CNIO)', 'Center for Molecular Biology of Heidelberg University (ZMBH)', 'Centro de Investigación en Red de Enfermedades Neurodegenerativas (CIBERNED)', 'University of Cantabria', 'IDIVAL', 'Center for Biomedicine and Medical Technology Mannheim (CBTM)', 'Heidelberg University', 'German Cancer Research Center (DKFZ)', 'Hope Center for Neurological Diseases', 'Washington University']","[IDIVAL, DKFZ-ZMBH Alliance, Center for Molecular Biology Severo Ochoa, University of Cantabria, Heidelberg University, Centro de Investigación Biomédica en Red, Enfermedades Neurodegenerativas]"
60,"[""King's College London"", 'Comprehensive Biomedical Research Centre', ""Guy's and St Thomas NHS Foundation Trust"", 'Uppsala University', 'Medical Products Agency', 'Karolinska Insituet']","[King's College London, UCL Biomedical Research Centre, Uppsala University, Guy's and St Thomas' NHS Foundation Trust, Karolinska Institutet, Medical Products Agency]"
61,"['August Pi i Sunyer Biomedical Research Institute', 'Hospital Clínic', 'Sant Joan de Deu Childrens Hospital', 'University of Barcelona', 'Nihon University School of Medicine', 'University of Lausanne', 'University of Pennsylvania', 'Catalan Institution for Research and Advanced Studies']","[Catalan Institution for Research and Advanced Studies, University of Pennsylvania, University of Barcelona, Nihon University, Sant Joan de Déu-Barcelona Children’s Hospital]"
62,['Delhi State Cancer Institute'],[Delhi State Cancer Institute]
63,"['Kushiro Rosai Hospital', 'Kanagawa Cancer Center', 'Keio University', 'Sapporo Medical University', 'Hijirigaoka Hospital', 'National Hospital Organization', 'Osaka National Hospital', 'Hiroshima University', 'University of Tokyo', 'Tokai Central Hospital', 'Translational Research and Clinical Trial Center', 'Hokkaido University Hospital', 'Japanese Foundation for Multidisciplinary Treatment of Cancer']","[Hiroshima University, Kushiro Rosai Hospital, Keio University, Osaka National Hospital, National Hospital Organization, Hokkaido University Hospital, Japanese Foundation for Multidisciplinary Treatment of Cancer, Tokai Central Hospital, Sapporo Medical University, Kanagawa Cancer Center]"
64,['Life Raft Group'],[]
65,['Washington State University'],[Washington State University]
66,"['Addis Ababa University', 'Karolinska Institutet', 'Karolinska University Hospital', 'Center for Innovative Drug Development and Therapeutic Trials', 'Armauer Hansen Research Institute']","[Karolinska University Hospital, Karolinska Institutet, Addis Ababa University, Armauer Hansen Research Institute]"
67,[nan],[]
68,"['Tulane University', 'Louisiana State University Health Sciences Center']","[Louisiana State University Health Sciences Center New Orleans, Tulane University]"
69,"['Hebei Medical University', 'Bethune International Peace Hospital', 'Hebei University of Chinese Medicine']","[Bethune International Peace Hospital, Hebei Medical University, Hebei University of Chinese Medicine]"
70,"[""Henan Provincial People's Hospital"", ""Zhengzhou University People's Hospital"", ""Henan University People's Hospital"", 'Institute of Hematology']",[]
71,"['Huazhong University of Science and Technology Union Shenzhen Hospital (Nanshan Hospital)', ""Shenzhen Second People's Hospital"", 'First Affiliated Hospital', 'Shenzhen University']",[Huazhong University of Science and Technology]
72,['Medical University of Innsbruck'],[]
73,"['Stanton L. Young Biomedical Research Center', 'University of Oklahoma Health Science Center']",[University of Oklahoma Health Sciences Center]
74,"['Center for Bioengineering and Tissue Regeneration', 'University of California', 'Gladstone Institutes', 'Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research', 'Helen Diller Family Comprehensive Cancer Center']","[UCSF Helen Diller Family Comprehensive Cancer Center, Gladstone Institutes, University of California, San Francisco]"
75,"['Northwestern University', 'Robert H. Lurie Comprehensive Cancer Center']","[Northwestern University, Robert H. Lurie Comprehensive Cancer Center]"
76,"['Qilu Hospital', 'Shandong University', 'Central Hospital', 'Zaozhuang Coal Mining Group', 'Jinan integrative medicine hospital']",[Qilu Hospital of Shandong University]
77,"[""St. Jude Children's Research Hospital"", 'Cornell', 'University of Chicago', 'Howard Hughes Medical Institute']","[University of Chicago, Weill Cornell Medicine, St. Jude Children's Research Hospital, Memphis Zoo, Howard Hughes Medical Institute]"
78,['Baylor College of Medicine'],[Baylor College of Medicine]
79,['University of California'],"[University of California, San Francisco]"
80,NaN,[]
81,NaN,[]
82,"['Second Affiliated Hospital', 'Fujian Medical University', 'Nanjing Medical University']","[Nanjing Medical University, Second Affiliated Hospital of Fujian Medical University]"
83,"['Universidade de São Paulo', 'Universidade do Oeste Paulista UNOESTE', 'Center of Translational Research in Oncology (LIM24)', 'Instituto do Cancer do Estado de Sao Paulo (ICESP)']","[Universidade de São Paulo, Instituto do Câncer do Estado de São Paulo]"
84,"['Hepatic Surgery Center', 'Tongji Hospital', 'Huazhong University of Science and Technology', 'Shanxi Bethune Hospital', 'Shanxi Academy of Medical Sciences', 'Shanxi Medical University', 'Shanxi Tongji Hospital']","[Bethune Second Hospital, Huazhong University of Science and Technology, Shanxi Medical University, Shanxi Academy of Medical Sciences, Tongji Hospital]"
85,"['Centre de Recherche des Cordeliers', 'INSERM', 'Sorbonne Université', 'Université Paris Cité', 'Institut universitaire de France', 'Institut Gustave Roussy', 'Centre de Recherche des Cordeliers', 'Klinikum Rechts der Isar', 'Technical University of Munich', 'Institute of Biophysics', 'Czech Academy of Sciences', 'CNRS', 'Institut Polytechnique de Paris', 'Université Paris-Saclay', 'Université Sorbonne Paris Nord', 'Institut du Cancer Paris CARPEM', 'Hôpital Européen Georges Pompidou']","[Institut Polytechnique de Paris, Université Paris Cité, CNRS, Université Sorbonne Paris Nord, Institut Universitaire de France, INSERM, Czech Academy of Sciences, Institut Gustave Roussy, Klinikum rechts der Isar, Centre de Recherche des Cordeliers, École Polytechnique, Sorbonne Université, Technical University of Munich]"
86,"['Norwegian University of Science and Technology', 'St. Olavs Hospital', 'Center for Oral Health Services and Research Mid-Norway (TkMidt)', 'Clinic of Medicine', 'K.G. Jebsen Centre for Genetic Epidemiology']",[Norwegian University of Science and Technology]
87,['Mayo Clinic'],[Mayo Clinic]
88,"['University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca', 'Biotechnology Research Center', 'Life Sciences Institute King Michael I of Romania', 'Babeș-Bolyai University']","[Biotechnology Research Center, Universitatea Babeș-Bolyai]"
89,"['Graduate Institute of Biomedical Science', 'China Medical University', 'Taichung Tzu Chi Hospital', 'Buddhist Tzu Chi Medical Foundation', 'China Medical University Hospital', 'Asia University', 'Institute of New Drug Development']","[China Medical University Hospital, China Medical University, Tzu Chi University, Buddhist Tzu Chi Medical Foundation]"
90,"['Chongqing University Three Gorges Hospital', 'Center for Medicine Research and Translation', ""Chengdu Fifth People's Hospital""]",[]
91,"['Boston University', 'Shaukat Khanum Memorial Cancer Hospital and Research Centre']","[Boston University, Shaukat Khanum Memorial Cancer Hospital and Research Center]"
92,NaN,[]
93,NaN,[]
94,['Georgetown University Medical Center'],[Georgetown University Medical Center]
95,['University of South Florida'],[University of South Florida]
96,['Johns Hopkins Oncology Center'],[]
97,"['Albert Einstein Cancer Center', 'Montefiore Medical Center']","[Albert Einstein Cancer Center at Montefiore, Montefiore Medical Center]"
98,['General Hospital Manuel Gea Gonzalez'],[Hospital General Dr. Manuel Gea Gonzalez]
99,['University Hospital Leiden'],[Leiden University]
100,['Paul Scherrer Institute'],[Paul Scherrer Institute]
101,['Wayne State University'],[Wayne State University]
102,[],[]

# 2.- Changing logic of fuzzy match within pgAdmin

In [84]:
from collections import OrderedDict
import psycopg2
import pandas as pd
import ast
import re
from tqdm import tqdm

# -----------------------
# CACHE (LRU size = 1000)
# -----------------------

CACHE_SIZE = 1000
institution_cache = OrderedDict()

# -----------------------
# PRE-CREATE RESULT COLUMNS
# -----------------------

df['Institutions_db_id'] = [[] for _ in range(len(df))]
df['Institutions_db_name'] = [[] for _ in range(len(df))]
df['Countries_db_country'] = [[] for _ in range(len(df))]

# -----------------------
# DB CONNECTION
# -----------------------

connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)

cursor = connection.cursor()

# Ensure trigram similarity threshold
cursor.execute("SET pg_trgm.similarity_threshold = 0.6")

# -----------------------
# LOAD DATABASE TABLES INTO MEMORY
# -----------------------

print("Loading institution_names...")
cursor.execute("SELECT institution_id, name FROM institution_names")
rows = cursor.fetchall()

name_index = {}
for inst_id, name in rows:
    name_index.setdefault(name, []).append((inst_id, name))

print("Loading institution_locations...")
cursor.execute("""
    SELECT institution_id, city_name, country_name, subdivision_name
    FROM institution_locations
""")

rows = cursor.fetchall()

location_index = {
    r[0]: (r[1], r[2], r[3])
    for r in rows
}

print("Indices loaded.")

# -----------------------
# MAIN LOOP
# -----------------------

for row in tqdm(range(len(df))):

    if pd.isna(df.at[row, "NER_BERT"]):
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'SUBC'
    }

    cou_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'COU'
    }

    # -----------------------
    # UNIQUE INS WORDS (ORDER PRESERVED)
    # -----------------------

    seen_queries = set()
    ins_queries = []

    for ner in ner_results:

        if ner.get('entity_group') != 'INS':
            continue

        query = ner.get('word')

        if query not in seen_queries:
            seen_queries.add(query)
            ins_queries.append(query)

    found_institutions = []

    # -----------------------
    # LOOP OVER UNIQUE QUERIES
    # -----------------------

    for query in ins_queries:

        # -----------------------
        # CACHE LOOKUP
        # -----------------------

        if query in institution_cache:

            ids, names, countries = institution_cache[query]

            for inst in zip(ids, names, countries):
                found_institutions.append(inst)

            institution_cache.move_to_end(query)

            continue

        # -----------------------
        # EXACT MATCH (IN MEMORY)
        # -----------------------

        records = name_index.get(query, [])
        candidates = {r[0]: r[1] for r in records}

        resolved = []

        # =========================
        # EXACT MATCH: ONE
        # =========================

        if len(candidates) == 1:

            inst_id = next(iter(candidates))

            location = location_index.get(inst_id)

            if location:
                city, country, subdivision = location
                resolved.append((inst_id, candidates[inst_id], country))

        # =========================
        # EXACT MATCH: MULTIPLE
        # =========================

        elif len(candidates) > 1:

            candidate_ids = list(candidates.keys())

            location_map = {
                inst_id: location_index[inst_id]
                for inst_id in candidate_ids
                if inst_id in location_index
            }

            matching_candidates = []

            for inst_id, inst_name in candidates.items():

                if inst_id not in location_map:
                    continue

                city, country, subdivision = location_map[inst_id]

                if country in cou_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

                elif city in subc_ner_results or subdivision in subc_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

            if len(matching_candidates) == 1:
                resolved.append(matching_candidates[0])

        # =========================
        # EXACT MATCH: ZERO → FUZZY
        # =========================

        elif len(candidates) == 0:

            cursor.execute(
                """
                SELECT institution_id,
                       name,
                       similarity(name, %s) AS sim
                FROM institution_names
                WHERE name %% %s
                  AND similarity(name, %s) >= 0.6
                ORDER BY sim DESC
                LIMIT 10
                """,
                (query, query, query)
            )

            records = cursor.fetchall()

            candidates = {r[0]: r[1] for r in records}

            # -------------------
            # FUZZY: ONE
            # -------------------

            if len(candidates) == 1:

                inst_id = next(iter(candidates))
                location = location_index.get(inst_id)

                if location:

                    city, country, subdivision = location

                    if (
                        country in cou_ner_results
                        or city in subc_ner_results
                        or subdivision in subc_ner_results
                    ):
                        resolved.append((inst_id, candidates[inst_id], country))

            # -------------------
            # FUZZY: MULTIPLE
            # -------------------

            elif len(candidates) > 1:

                candidate_ids = list(candidates.keys())

                location_map = {
                    inst_id: location_index[inst_id]
                    for inst_id in candidate_ids
                    if inst_id in location_index
                }

                matching_candidates = []

                for inst_id, inst_name in candidates.items():

                    if inst_id not in location_map:
                        continue

                    city, country, subdivision = location_map[inst_id]

                    if country in cou_ner_results:
                        matching_candidates.append((inst_id, inst_name, country))

                    elif city in subc_ner_results or subdivision in subc_ner_results:
                        matching_candidates.append((inst_id, inst_name, country))

                if len(matching_candidates) == 1:
                    resolved.append(matching_candidates[0])

        # -----------------------
        # STORE IN CACHE
        # -----------------------

        if resolved:

            ids, names, countries = zip(*resolved)

            institution_cache[query] = (list(ids), list(names), list(countries))

            if len(institution_cache) > CACHE_SIZE:
                institution_cache.popitem(last=False)

            for inst in resolved:
                found_institutions.append(inst)

    # =========================
    # WRITE RESULTS
    # =========================

    if found_institutions:

        found_institutions = list(set(found_institutions))

        ids, names, countries = zip(*found_institutions)

        df.at[row, 'Institutions_db_id'] = list(ids)
        df.at[row, 'Institutions_db_name'] = list(names)
        df.at[row, 'Countries_db_country'] = list(countries)

cursor.close()
connection.close()

Loading institution_names...
Loading institution_locations...
Indices loaded.

100%|████████████████████████████████████████████████████████████████████████████████| 103/103 [00:06<00:00, 16.70it/s]

In [85]:
df[["Institutions_man", "Institutions_db_name"]]

,Institutions_man,Institutions_db_name
0,NaN,[]
1,NaN,[]
2,"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of British Columbia, University of Porto, i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto]"
3,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[Emory University, University of Cincinnati, Cincinnati Children's Hospital Medical Center, Children's Healthcare of Atlanta]"
4,"['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[University of Chicago, University of Oklahoma Health Sciences Center, University of Pennsylvania, Battelle Memorial Institute, University of Memphis, Stephenson Cancer Center, Rutgers Biomedical and Health Sciences]"
5,"['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[CONAHCYT, Universidad Nacional Autónoma de México]"
6,"['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[Inserm, University Cancer Institute Toulouse Oncopole, CNRS, ANR]"
7,['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University]
8,"['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw]
9,"['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']",[Chang Gung University]
10,"['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']","[Medical Genetics Center, BG University Hospital Bergmannsheil Bochum, Ruhr University Bochum, Ludwig-Maximilians-Universität in Munich]"
11,"['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[Università Vita-Salute San Raffaele, IRCCS Ospedale San Raffaele]"
12,"['University of Adelaide', 'Queen Elizabeth Hospital']","[Queen Elizabeth Hospital, University of Adelaide]"
13,['University of Zimbabwe'],[University of Zimbabwe]
14,['University of Tokyo Hospital'],[University of Tokyo Hospital]
15,['University Hospital Centre of Grenoble'],[]
16,['Harvard'],[]
17,['University of Washington'],[University of Washington]
18,['University of Würzburg'],[University of Würzburg]
19,"['Mannheim Medical Center', 'University of Heidelberg']",[]
20,NaN,[]
21,['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology]
22,['Duke University Medical Center'],[]
23,"['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]",[]
24,['University of Rochester'],[University of Rochester]
25,['Stavanger University Hospital'],[Stavanger University Hospital]
26,['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[]
27,['Akademii Medycznej w Gdańsku'],[]
28,['Vienna Medical University'],[Medical University of Vienna]
29,"['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]"
30,NaN,[]
31,"['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University]
32,"['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital]
33,"['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University]
34,NaN,[]
35,['Royal North Brisbane Hospital'],[]
36,['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[Azienda Ospedaliero Universitaria Maggiore della Carita]
37,['Universitá degli Studi di Palermo'],[]
38,['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf]
39,NaN,[]
40,"['Institute of Medical Microbiology', 'Charles University']",[Charles University]
41,['Queensland Institute of Medical Research'],[Queensland Institute of Medical Research]
42,['University of Porto'],[University of Porto]
43,"['University of Liverpool', 'Linda McCartney Centre', 'Royal Liverpool University Hospital']","[University of Liverpool, Royal Liverpool University Hospital]"
44,"['University of Leipzig Medical Center', 'University Medical Center Hamburg-Eppendorf', 'Institute for Medical Biostatistics, Epidemiology and Informatics', 'University of Mainz Medical Center', 'University Hospital of Essen', ""Children's Hospital""]","[Essen University Hospital, University Medical Center Göttingen, University Medical Center Hamburg-Eppendorf, Kantonsspital St. Gallen, Institute for Medical Informatics and Biostatistics, University of Würzburg]"
45,"['Northwestern Memorial Hospital', 'Robert H. Lurie Comprehensive Cancer Center', 'Northwestern University']","[Northwestern Memorial Hospital, Northwestern University, Robert H. Lurie Comprehensive Cancer Center]"
46,"['First Affiliated Hospital', 'Nanchang University']",[First Affiliated Hospital of Nanchang University]
47,"['Suzhou Municipal Hospital', 'Affiliated Suzhou Hospital', 'Nanjing Medical University', ""Shaoxing People's Hospital"", 'Shaoxing Hospital', 'Zhejiang University']","[Suzhou Municipal Hospital, Children's Hospital of Zhejiang University]"
48,NaN,[]
49,NaN,[]
50,"['Institute of Biomedical and Genetic Engineering (IBGE)', 'International Islamic University']","[Institute of Biomedical and Genetic Engineering, International Islamic University, Islamabad]"
51,"['Istanbul University', 'Institute of Experimental Medicine', 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital']","[Istanbul University, Yeditepe University]"
52,NaN,[]
53,NaN,[]
54,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', 'Cancer and Blood Disease Institute', ""Boston Children's Hospital"", 'Harvard']","[Boston Children's Museum, University of Cincinnati, Cincinnati Children's Hospital Medical Center, IIT@Harvard]"
55,"['Erasmus MC', 'Utrecht University', 'Erasmus MC Cancer Institute']","[Erasmus MC Cancer Institute, Utrecht University, Erasmus MC]"
56,NaN,[]
57,NaN,[]
58,"['Queen Elizabeth Hospital', 'Royal Victoria Infirmary', 'Medical Research Council Clinical Trials Unit', 'University College London']","[Medical Research Council, Royal Victoria Infirmary, Queen Elizabeth Hospital, University College London]"
59,"['Centro Nacional de Investigaciones Oncológicas (CNIO)', 'Center for Molecular Biology of Heidelberg University (ZMBH)', 'Centro de Investigación en Red de Enfermedades Neurodegenerativas (CIBERNED)', 'University of Cantabria', 'IDIVAL', 'Center for Biomedicine and Medical Technology Mannheim (CBTM)', 'Heidelberg University', 'German Cancer Research Center (DKFZ)', 'Hope Center for Neurological Diseases', 'Washington University']","[DKFZ-ZMBH Alliance, University of Cantabria, IDIVAL, Centro de Investigación Biomédica en Red, Enfermedades Neurodegenerativas, Heidelberg University, Center for Molecular Biology Severo Ochoa]"
60,"[""King's College London"", 'Comprehensive Biomedical Research Centre', ""Guy's and St Thomas NHS Foundation Trust"", 'Uppsala University', 'Medical Products Agency', 'Karolinska Insituet']","[Medical Products Agency, King's College London, Guy's and St Thomas' NHS Foundation Trust, UCL Biomedical Research Centre, Karolinska Institutet, Uppsala University]"
61,"['August Pi i Sunyer Biomedical Research Institute', 'Hospital Clínic', 'Sant Joan de Deu Childrens Hospital', 'University of Barcelona', 'Nihon University School of Medicine', 'University of Lausanne', 'University of Pennsylvania', 'Catalan Institution for Research and Advanced Studies']","[University of Pennsylvania, Nihon University, Catalan Institution for Research and Advanced Studies, University of Barcelona, Sant Joan de Déu-Barcelona Children’s Hospital]"
62,['Delhi State Cancer Institute'],[Delhi State Cancer Institute]
63,"['Kushiro Rosai Hospital', 'Kanagawa Cancer Center', 'Keio University', 'Sapporo Medical University', 'Hijirigaoka Hospital', 'National Hospital Organization', 'Osaka National Hospital', 'Hiroshima University', 'University of Tokyo', 'Tokai Central Hospital', 'Translational Research and Clinical Trial Center', 'Hokkaido University Hospital', 'Japanese Foundation for Multidisciplinary Treatment of Cancer']","[Japanese Foundation for Multidisciplinary Treatment of Cancer, Osaka National Hospital, Keio University, Kushiro Rosai Hospital, Hokkaido University Hospital, National Hospital Organization, Tokai Central Hospital, Hiroshima University, Kanagawa Cancer Center, Sapporo Medical University]"
64,['Life Raft Group'],[]
65,['Washington State University'],[Washington State University]
66,"['Addis Ababa University', 'Karolinska Institutet', 'Karolinska University Hospital', 'Center for Innovative Drug Development and Therapeutic Trials', 'Armauer Hansen Research Institute']","[Armauer Hansen Research Institute, Addis Ababa University, Karolinska Institutet, Karolinska University Hospital]"
67,[nan],[]
68,"['Tulane University', 'Louisiana State University Health Sciences Center']","[Louisiana State University Health Sciences Center New Orleans, Tulane University]"
69,"['Hebei Medical University', 'Bethune International Peace Hospital', 'Hebei University of Chinese Medicine']","[Hebei Medical University, Bethune International Peace Hospital, Hebei University of Chinese Medicine]"
70,"[""Henan Provincial People's Hospital"", ""Zhengzhou University People's Hospital"", ""Henan University People's Hospital"", 'Institute of Hematology']",[Shanghai Institute of Hematology]
71,"['Huazhong University of Science and Technology Union Shenzhen Hospital (Nanshan Hospital)', ""Shenzhen Second People's Hospital"", 'First Affiliated Hospital', 'Shenzhen University']",[Huazhong University of Science and Technology]
72,['Medical University of Innsbruck'],[]
73,"['Stanton L. Young Biomedical Research Center', 'University of Oklahoma Health Science Center']",[University of Oklahoma Health Sciences Center]
74,"['Center for Bioengineering and Tissue Regeneration', 'University of California', 'Gladstone Institutes', 'Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research', 'Helen Diller Family Comprehensive Cancer Center']","[Gladstone Institutes, UCSF Helen Diller Family Comprehensive Cancer Center]"
75,"['Northwestern University', 'Robert H. Lurie Comprehensive Cancer Center']","[Robert H. Lurie Comprehensive Cancer Center, Northwestern University]"
76,"['Qilu Hospital', 'Shandong University', 'Central Hospital', 'Zaozhuang Coal Mining Group', 'Jinan integrative medicine hospital']",[Qilu Hospital of Shandong University]
77,"[""St. Jude Children's Research Hospital"", 'Cornell', 'University of Chicago', 'Howard Hughes Medical Institute']","[University of Chicago, Weill Cornell Medicine, Memphis Zoo, St. Jude Children's Research Hospital, Howard Hughes Medical Institute]"
78,['Baylor College of Medicine'],[Baylor College of Medicine]
79,['University of California'],[]
80,NaN,[]
81,NaN,[]
82,"['Second Affiliated Hospital', 'Fujian Medical University', 'Nanjing Medical University']","[Second Affiliated Hospital of Fujian Medical University, Nanjing Medical University]"
83,"['Universidade de São Paulo', 'Universidade do Oeste Paulista UNOESTE', 'Center of Translational Research in Oncology (LIM24)', 'Instituto do Cancer do Estado de Sao Paulo (ICESP)']","[Instituto do Câncer do Estado de São Paulo, Universidade de São Paulo]"
84,"['Hepatic Surgery Center', 'Tongji Hospital', 'Huazhong University of Science and Technology', 'Shanxi Bethune Hospital', 'Shanxi Academy of Medical Sciences', 'Shanxi Medical University', 'Shanxi Tongji Hospital']","[Huazhong University of Science and Technology, Shanxi Academy of Medical Sciences, Shanxi Medical University, Tongji Hospital, Bethune Second Hospital]"
85,"['Centre de Recherche des Cordeliers', 'INSERM', 'Sorbonne Université', 'Université Paris Cité', 'Institut universitaire de France', 'Institut Gustave Roussy', 'Centre de Recherche des Cordeliers', 'Klinikum Rechts der Isar', 'Technical University of Munich', 'Institute of Biophysics', 'Czech Academy of Sciences', 'CNRS', 'Institut Polytechnique de Paris', 'Université Paris-Saclay', 'Université Sorbonne Paris Nord', 'Institut du Cancer Paris CARPEM', 'Hôpital Européen Georges Pompidou']","[Technical University of Munich, Sorbonne Université, Institut Polytechnique de Paris, Czech Academy of Sciences, Institut Universitaire de France, École Polytechnique, Université Sorbonne Paris Nord, Institut Gustave Roussy, Klinikum rechts der Isar, Centre de Recherche des Cordeliers, CNRS, INSERM, Université Paris Cité]"
86,"['Norwegian University of Science and Technology', 'St. Olavs Hospital', 'Center for Oral Health Services and Research Mid-Norway (TkMidt)', 'Clinic of Medicine', 'K.G. Jebsen Centre for Genetic Epidemiology']",[Norwegian University of Science and Technology]
87,['Mayo Clinic'],[Mayo Clinic]
88,"['University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca', 'Biotechnology Research Center', 'Life Sciences Institute King Michael I of Romania', 'Babeș-Bolyai University']","[Universitatea Babeș-Bolyai, Biotechnology Research Center]"
89,"['Graduate Institute of Biomedical Science', 'China Medical University', 'Taichung Tzu Chi Hospital', 'Buddhist Tzu Chi Medical Foundation', 'China Medical University Hospital', 'Asia University', 'Institute of New Drug Development']","[China Medical University, China Medical University Hospital, Tzu Chi University, Buddhist Tzu Chi Medical Foundation]"
90,"['Chongqing University Three Gorges Hospital', 'Center for Medicine Research and Translation', ""Chengdu Fifth People's Hospital""]",[]
91,"['Boston University', 'Shaukat Khanum Memorial Cancer Hospital and Research Centre']","[Shaukat Khanum Memorial Cancer Hospital and Research Center, Boston University]"
92,NaN,[]
93,NaN,[]
94,['Georgetown University Medical Center'],[Georgetown University Medical Center]
95,['University of South Florida'],[University of South Florida]
96,['Johns Hopkins Oncology Center'],[]
97,"['Albert Einstein Cancer Center', 'Montefiore Medical Center']","[Albert Einstein Cancer Center at Montefiore, Montefiore Medical Center]"
98,['General Hospital Manuel Gea Gonzalez'],[Hospital General Dr. Manuel Gea Gonzalez]
99,['University Hospital Leiden'],[Leiden University]
100,['Paul Scherrer Institute'],[Paul Scherrer Institute]
101,['Wayne State University'],[Wayne State University]
102,[],[]

In [86]:
counter_hits(df)

(272, 170)

# Add column with not found INS

In [87]:
from collections import OrderedDict
import psycopg2
import pandas as pd
import ast
import re
from tqdm import tqdm

# -----------------------
# CACHE (LRU size = 1000)
# -----------------------

CACHE_SIZE = 1000
institution_cache = OrderedDict()

# -----------------------
# PRE-CREATE RESULT COLUMNS
# -----------------------

df['Institutions_db_id'] = [[] for _ in range(len(df))]
df['Institutions_db_name'] = [[] for _ in range(len(df))]
df['Institutions_db_country'] = [[] for _ in range(len(df))] 

# -----------------------
# DB CONNECTION
# -----------------------

connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)

cursor = connection.cursor()

# Ensure trigram similarity threshold
cursor.execute("SET pg_trgm.similarity_threshold = 0.6")

# -----------------------
# LOAD DATABASE TABLES INTO MEMORY
# -----------------------

print("Loading institution_names...")
cursor.execute("SELECT institution_id, name FROM institution_names")
rows = cursor.fetchall()

name_index = {}
for inst_id, name in rows:
    name_index.setdefault(name, []).append((inst_id, name))

print("Loading institution_locations...")
cursor.execute("""
    SELECT institution_id, city_name, country_name, subdivision_name
    FROM institution_locations
""")
rows = cursor.fetchall()

location_index = {
    r[0]: (r[1], r[2], r[3])
    for r in rows
}

print("Indices loaded.")

# -----------------------
# MAIN LOOP
# -----------------------

for row in tqdm(range(len(df))):

    if pd.isna(df.at[row, "NER_BERT"]):
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'SUBC'
    }

    cou_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'COU'
    }

    # -----------------------
    # UNIQUE INS WORDS (ORDER PRESERVED)
    # -----------------------

    seen_queries = set()
    ins_queries = []

    for ner in ner_results:
        if ner.get('entity_group') != 'INS':
            continue
        query = ner.get('word')
        if query not in seen_queries:
            seen_queries.add(query)
            ins_queries.append(query)

    found_institutions = []
    unmatched_queries = []  # Track unmatched INS

    # -----------------------
    # LOOP OVER UNIQUE QUERIES
    # -----------------------

    for query in ins_queries:

        # -----------------------
        # CACHE LOOKUP
        # -----------------------
        if query in institution_cache:
            ids, names, countries = institution_cache[query]
            for inst in zip(ids, names, countries):
                found_institutions.append(inst)
            institution_cache.move_to_end(query)
            continue

        # -----------------------
        # EXACT MATCH (IN MEMORY)
        # -----------------------
        records = name_index.get(query, [])
        candidates = {r[0]: r[1] for r in records}
        resolved = []

        # =========================
        # EXACT MATCH: ONE
        # =========================
        if len(candidates) == 1:
            inst_id = next(iter(candidates))
            location = location_index.get(inst_id)
            if location:
                city, country, subdivision = location
                resolved.append((inst_id, candidates[inst_id], country))

        # =========================
        # EXACT MATCH: MULTIPLE
        # =========================
        elif len(candidates) > 1:
            candidate_ids = list(candidates.keys())
            location_map = {
                inst_id: location_index[inst_id]
                for inst_id in candidate_ids
                if inst_id in location_index
            }
            matching_candidates = []
            for inst_id, inst_name in candidates.items():
                if inst_id not in location_map:
                    continue
                city, country, subdivision = location_map[inst_id]
                if country in cou_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))
                elif city in subc_ner_results or subdivision in subc_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))
            if len(matching_candidates) == 1:
                resolved.append(matching_candidates[0])

        # =========================
        # EXACT MATCH: ZERO → FUZZY
        # =========================
        elif len(candidates) == 0:
            cursor.execute(
                """
                SELECT institution_id,
                       name,
                       similarity(name, %s) AS sim
                FROM institution_names
                WHERE name %% %s
                  AND similarity(name, %s) >= 0.6
                ORDER BY sim DESC
                LIMIT 10
                """,
                (query, query, query)
            )
            records = cursor.fetchall()
            candidates = {r[0]: r[1] for r in records}

            # -------------------
            # FUZZY: ONE
            # -------------------
            if len(candidates) == 1:
                inst_id = next(iter(candidates))
                location = location_index.get(inst_id)
                if location:
                    city, country, subdivision = location
                    if (country in cou_ner_results
                        or city in subc_ner_results
                        or subdivision in subc_ner_results):
                        resolved.append((inst_id, candidates[inst_id], country))

            # -------------------
            # FUZZY: MULTIPLE
            # -------------------
            elif len(candidates) > 1:
                candidate_ids = list(candidates.keys())
                location_map = {
                    inst_id: location_index[inst_id]
                    for inst_id in candidate_ids
                    if inst_id in location_index
                }
                matching_candidates = []
                for inst_id, inst_name in candidates.items():
                    if inst_id not in location_map:
                        continue
                    city, country, subdivision = location_map[inst_id]
                    if country in cou_ner_results:
                        matching_candidates.append((inst_id, inst_name, country))
                    elif city in subc_ner_results or subdivision in subc_ner_results:
                        matching_candidates.append((inst_id, inst_name, country))
                if len(matching_candidates) == 1:
                    resolved.append(matching_candidates[0])

        # -----------------------
        # STORE IN CACHE OR TRACK UNMATCHED
        # -----------------------
        if resolved:
            ids, names, countries = zip(*resolved)
            institution_cache[query] = (list(ids), list(names), list(countries))
            if len(institution_cache) > CACHE_SIZE:
                institution_cache.popitem(last=False)
            for inst in resolved:
                found_institutions.append(inst)
        else:
            unmatched_queries.append(query)

    # =========================
    # WRITE RESULTS
    # =========================
    if found_institutions:
        found_institutions = list(set(found_institutions))
        ids, names, countries = zip(*found_institutions)
        df.at[row, 'Institutions_db_id'] = list(ids)
        df.at[row, 'Institutions_db_name'] = list(names)
        df.at[row, 'Institutions_db_country'] = list(countries)

    if unmatched_queries:
        df.at[row, 'Unmatched_INS'] = unmatched_queries

# -----------------------
# CLOSE CONNECTION
# -----------------------
cursor.close()
connection.close()

Loading institution_names...
Loading institution_locations...
Indices loaded.

100%|████████████████████████████████████████████████████████████████████████████████| 103/103 [00:06<00:00, 16.32it/s]

In [88]:
df[["Institutions_man", "Institutions_db_name"]]

,Institutions_man,Institutions_db_name
0,NaN,[]
1,NaN,[]
2,"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of British Columbia, University of Porto, i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto]"
3,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[Emory University, University of Cincinnati, Cincinnati Children's Hospital Medical Center, Children's Healthcare of Atlanta]"
4,"['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[University of Chicago, University of Oklahoma Health Sciences Center, University of Pennsylvania, Battelle Memorial Institute, University of Memphis, Stephenson Cancer Center, Rutgers Biomedical and Health Sciences]"
5,"['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[CONAHCYT, Universidad Nacional Autónoma de México]"
6,"['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[Inserm, University Cancer Institute Toulouse Oncopole, CNRS, ANR]"
7,['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University]
8,"['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw]
9,"['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']",[Chang Gung University]
10,"['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']","[Medical Genetics Center, BG University Hospital Bergmannsheil Bochum, Ruhr University Bochum, Ludwig-Maximilians-Universität in Munich]"
11,"['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[Università Vita-Salute San Raffaele, IRCCS Ospedale San Raffaele]"
12,"['University of Adelaide', 'Queen Elizabeth Hospital']","[Queen Elizabeth Hospital, University of Adelaide]"
13,['University of Zimbabwe'],[University of Zimbabwe]
14,['University of Tokyo Hospital'],[University of Tokyo Hospital]
15,['University Hospital Centre of Grenoble'],[]
16,['Harvard'],[]
17,['University of Washington'],[University of Washington]
18,['University of Würzburg'],[University of Würzburg]
19,"['Mannheim Medical Center', 'University of Heidelberg']",[]
20,NaN,[]
21,['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology]
22,['Duke University Medical Center'],[]
23,"['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]",[]
24,['University of Rochester'],[University of Rochester]
25,['Stavanger University Hospital'],[Stavanger University Hospital]
26,['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[]
27,['Akademii Medycznej w Gdańsku'],[]
28,['Vienna Medical University'],[Medical University of Vienna]
29,"['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]"
30,NaN,[]
31,"['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University]
32,"['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital]
33,"['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University]
34,NaN,[]
35,['Royal North Brisbane Hospital'],[]
36,['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[Azienda Ospedaliero Universitaria Maggiore della Carita]
37,['Universitá degli Studi di Palermo'],[]
38,['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf]
39,NaN,[]
40,"['Institute of Medical Microbiology', 'Charles University']",[Charles University]
41,['Queensland Institute of Medical Research'],[Queensland Institute of Medical Research]
42,['University of Porto'],[University of Porto]
43,"['University of Liverpool', 'Linda McCartney Centre', 'Royal Liverpool University Hospital']","[University of Liverpool, Royal Liverpool University Hospital]"
44,"['University of Leipzig Medical Center', 'University Medical Center Hamburg-Eppendorf', 'Institute for Medical Biostatistics, Epidemiology and Informatics', 'University of Mainz Medical Center', 'University Hospital of Essen', ""Children's Hospital""]","[Essen University Hospital, University Medical Center Göttingen, University Medical Center Hamburg-Eppendorf, Kantonsspital St. Gallen, Institute for Medical Informatics and Biostatistics, University of Würzburg]"
45,"['Northwestern Memorial Hospital', 'Robert H. Lurie Comprehensive Cancer Center', 'Northwestern University']","[Northwestern Memorial Hospital, Northwestern University, Robert H. Lurie Comprehensive Cancer Center]"
46,"['First Affiliated Hospital', 'Nanchang University']",[First Affiliated Hospital of Nanchang University]
47,"['Suzhou Municipal Hospital', 'Affiliated Suzhou Hospital', 'Nanjing Medical University', ""Shaoxing People's Hospital"", 'Shaoxing Hospital', 'Zhejiang University']","[Suzhou Municipal Hospital, Children's Hospital of Zhejiang University]"
48,NaN,[]
49,NaN,[]
50,"['Institute of Biomedical and Genetic Engineering (IBGE)', 'International Islamic University']","[Institute of Biomedical and Genetic Engineering, International Islamic University, Islamabad]"
51,"['Istanbul University', 'Institute of Experimental Medicine', 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital']","[Istanbul University, Yeditepe University]"
52,NaN,[]
53,NaN,[]
54,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', 'Cancer and Blood Disease Institute', ""Boston Children's Hospital"", 'Harvard']","[Boston Children's Museum, University of Cincinnati, Cincinnati Children's Hospital Medical Center, IIT@Harvard]"
55,"['Erasmus MC', 'Utrecht University', 'Erasmus MC Cancer Institute']","[Erasmus MC Cancer Institute, Utrecht University, Erasmus MC]"
56,NaN,[]
57,NaN,[]
58,"['Queen Elizabeth Hospital', 'Royal Victoria Infirmary', 'Medical Research Council Clinical Trials Unit', 'University College London']","[Medical Research Council, Royal Victoria Infirmary, Queen Elizabeth Hospital, University College London]"
59,"['Centro Nacional de Investigaciones Oncológicas (CNIO)', 'Center for Molecular Biology of Heidelberg University (ZMBH)', 'Centro de Investigación en Red de Enfermedades Neurodegenerativas (CIBERNED)', 'University of Cantabria', 'IDIVAL', 'Center for Biomedicine and Medical Technology Mannheim (CBTM)', 'Heidelberg University', 'German Cancer Research Center (DKFZ)', 'Hope Center for Neurological Diseases', 'Washington University']","[DKFZ-ZMBH Alliance, University of Cantabria, IDIVAL, Centro de Investigación Biomédica en Red, Enfermedades Neurodegenerativas, Heidelberg University, Center for Molecular Biology Severo Ochoa]"
60,"[""King's College London"", 'Comprehensive Biomedical Research Centre', ""Guy's and St Thomas NHS Foundation Trust"", 'Uppsala University', 'Medical Products Agency', 'Karolinska Insituet']","[Medical Products Agency, King's College London, Guy's and St Thomas' NHS Foundation Trust, UCL Biomedical Research Centre, Karolinska Institutet, Uppsala University]"
61,"['August Pi i Sunyer Biomedical Research Institute', 'Hospital Clínic', 'Sant Joan de Deu Childrens Hospital', 'University of Barcelona', 'Nihon University School of Medicine', 'University of Lausanne', 'University of Pennsylvania', 'Catalan Institution for Research and Advanced Studies']","[University of Pennsylvania, Nihon University, Catalan Institution for Research and Advanced Studies, University of Barcelona, Sant Joan de Déu-Barcelona Children’s Hospital]"
62,['Delhi State Cancer Institute'],[Delhi State Cancer Institute]
63,"['Kushiro Rosai Hospital', 'Kanagawa Cancer Center', 'Keio University', 'Sapporo Medical University', 'Hijirigaoka Hospital', 'National Hospital Organization', 'Osaka National Hospital', 'Hiroshima University', 'University of Tokyo', 'Tokai Central Hospital', 'Translational Research and Clinical Trial Center', 'Hokkaido University Hospital', 'Japanese Foundation for Multidisciplinary Treatment of Cancer']","[Japanese Foundation for Multidisciplinary Treatment of Cancer, Osaka National Hospital, Keio University, Kushiro Rosai Hospital, Hokkaido University Hospital, National Hospital Organization, Tokai Central Hospital, Hiroshima University, Kanagawa Cancer Center, Sapporo Medical University]"
64,['Life Raft Group'],[]
65,['Washington State University'],[Washington State University]
66,"['Addis Ababa University', 'Karolinska Institutet', 'Karolinska University Hospital', 'Center for Innovative Drug Development and Therapeutic Trials', 'Armauer Hansen Research Institute']","[Armauer Hansen Research Institute, Addis Ababa University, Karolinska Institutet, Karolinska University Hospital]"
67,[nan],[]
68,"['Tulane University', 'Louisiana State University Health Sciences Center']","[Louisiana State University Health Sciences Center New Orleans, Tulane University]"
69,"['Hebei Medical University', 'Bethune International Peace Hospital', 'Hebei University of Chinese Medicine']","[Hebei Medical University, Bethune International Peace Hospital, Hebei University of Chinese Medicine]"
70,"[""Henan Provincial People's Hospital"", ""Zhengzhou University People's Hospital"", ""Henan University People's Hospital"", 'Institute of Hematology']",[Shanghai Institute of Hematology]
71,"['Huazhong University of Science and Technology Union Shenzhen Hospital (Nanshan Hospital)', ""Shenzhen Second People's Hospital"", 'First Affiliated Hospital', 'Shenzhen University']",[Huazhong University of Science and Technology]
72,['Medical University of Innsbruck'],[]
73,"['Stanton L. Young Biomedical Research Center', 'University of Oklahoma Health Science Center']",[University of Oklahoma Health Sciences Center]
74,"['Center for Bioengineering and Tissue Regeneration', 'University of California', 'Gladstone Institutes', 'Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research', 'Helen Diller Family Comprehensive Cancer Center']","[Gladstone Institutes, UCSF Helen Diller Family Comprehensive Cancer Center]"
75,"['Northwestern University', 'Robert H. Lurie Comprehensive Cancer Center']","[Robert H. Lurie Comprehensive Cancer Center, Northwestern University]"
76,"['Qilu Hospital', 'Shandong University', 'Central Hospital', 'Zaozhuang Coal Mining Group', 'Jinan integrative medicine hospital']",[Qilu Hospital of Shandong University]
77,"[""St. Jude Children's Research Hospital"", 'Cornell', 'University of Chicago', 'Howard Hughes Medical Institute']","[University of Chicago, Weill Cornell Medicine, Memphis Zoo, St. Jude Children's Research Hospital, Howard Hughes Medical Institute]"
78,['Baylor College of Medicine'],[Baylor College of Medicine]
79,['University of California'],[]
80,NaN,[]
81,NaN,[]
82,"['Second Affiliated Hospital', 'Fujian Medical University', 'Nanjing Medical University']","[Second Affiliated Hospital of Fujian Medical University, Nanjing Medical University]"
83,"['Universidade de São Paulo', 'Universidade do Oeste Paulista UNOESTE', 'Center of Translational Research in Oncology (LIM24)', 'Instituto do Cancer do Estado de Sao Paulo (ICESP)']","[Instituto do Câncer do Estado de São Paulo, Universidade de São Paulo]"
84,"['Hepatic Surgery Center', 'Tongji Hospital', 'Huazhong University of Science and Technology', 'Shanxi Bethune Hospital', 'Shanxi Academy of Medical Sciences', 'Shanxi Medical University', 'Shanxi Tongji Hospital']","[Huazhong University of Science and Technology, Shanxi Academy of Medical Sciences, Shanxi Medical University, Tongji Hospital, Bethune Second Hospital]"
85,"['Centre de Recherche des Cordeliers', 'INSERM', 'Sorbonne Université', 'Université Paris Cité', 'Institut universitaire de France', 'Institut Gustave Roussy', 'Centre de Recherche des Cordeliers', 'Klinikum Rechts der Isar', 'Technical University of Munich', 'Institute of Biophysics', 'Czech Academy of Sciences', 'CNRS', 'Institut Polytechnique de Paris', 'Université Paris-Saclay', 'Université Sorbonne Paris Nord', 'Institut du Cancer Paris CARPEM', 'Hôpital Européen Georges Pompidou']","[Technical University of Munich, Sorbonne Université, Institut Polytechnique de Paris, Czech Academy of Sciences, Institut Universitaire de France, École Polytechnique, Université Sorbonne Paris Nord, Institut Gustave Roussy, Klinikum rechts der Isar, Centre de Recherche des Cordeliers, CNRS, INSERM, Université Paris Cité]"
86,"['Norwegian University of Science and Technology', 'St. Olavs Hospital', 'Center for Oral Health Services and Research Mid-Norway (TkMidt)', 'Clinic of Medicine', 'K.G. Jebsen Centre for Genetic Epidemiology']",[Norwegian University of Science and Technology]
87,['Mayo Clinic'],[Mayo Clinic]
88,"['University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca', 'Biotechnology Research Center', 'Life Sciences Institute King Michael I of Romania', 'Babeș-Bolyai University']","[Universitatea Babeș-Bolyai, Biotechnology Research Center]"
89,"['Graduate Institute of Biomedical Science', 'China Medical University', 'Taichung Tzu Chi Hospital', 'Buddhist Tzu Chi Medical Foundation', 'China Medical University Hospital', 'Asia University', 'Institute of New Drug Development']","[China Medical University, China Medical University Hospital, Tzu Chi University, Buddhist Tzu Chi Medical Foundation]"
90,"['Chongqing University Three Gorges Hospital', 'Center for Medicine Research and Translation', ""Chengdu Fifth People's Hospital""]",[]
91,"['Boston University', 'Shaukat Khanum Memorial Cancer Hospital and Research Centre']","[Shaukat Khanum Memorial Cancer Hospital and Research Center, Boston University]"
92,NaN,[]
93,NaN,[]
94,['Georgetown University Medical Center'],[Georgetown University Medical Center]
95,['University of South Florida'],[University of South Florida]
96,['Johns Hopkins Oncology Center'],[]
97,"['Albert Einstein Cancer Center', 'Montefiore Medical Center']","[Albert Einstein Cancer Center at Montefiore, Montefiore Medical Center]"
98,['General Hospital Manuel Gea Gonzalez'],[Hospital General Dr. Manuel Gea Gonzalez]
99,['University Hospital Leiden'],[Leiden University]
100,['Paul Scherrer Institute'],[Paul Scherrer Institute]
101,['Wayne State University'],[Wayne State University]
102,[],[]

In [89]:
counter_hits(df)

(272, 170)

# 4.- Disambiguation of multiple fuzzy based on sim difference between first and second hits - OLD BENCHMARK

In [105]:
from collections import OrderedDict
import psycopg2
import pandas as pd
import ast
import re
from tqdm import tqdm

# -----------------------
# CACHE (LRU size = 1000)
# -----------------------
CACHE_SIZE = 1000
institution_cache = OrderedDict()

# -----------------------
# PRE-CREATE RESULT COLUMNS
# -----------------------
df['Institutions_db_id'] = [[] for _ in range(len(df))]
df['Institutions_db_name'] = [[] for _ in range(len(df))]
df['Institutions_db_country'] = [[] for _ in range(len(df))]
df['Unmatched_INS'] = [[] for _ in range(len(df))]

# -----------------------
# DB CONNECTION
# -----------------------
connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)
cursor = connection.cursor()
cursor.execute("SET pg_trgm.similarity_threshold = 0.6")

# -----------------------
# LOAD DATABASE TABLES INTO MEMORY
# -----------------------
print("Loading institution_names...")
cursor.execute("SELECT institution_id, name FROM institution_names")
rows = cursor.fetchall()
name_index = {}
for inst_id, name in rows:
    name_index.setdefault(name, []).append((inst_id, name))

print("Loading institution_locations...")
cursor.execute("""
    SELECT institution_id, city_name, country_name, subdivision_name
    FROM institution_locations
""")
rows = cursor.fetchall()
location_index = {r[0]: (r[1], r[2], r[3]) for r in rows}

print("Indices loaded.")

# -----------------------
# MAIN LOOP
# -----------------------
for row in tqdm(range(len(df))):

    if pd.isna(df.at[row, "NER_BERT"]):
        continue

    # Clean and parse NER results
    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    # Collect subcountry and country entities
    subc_ner_results = {ner.get('word') for ner in ner_results if ner.get('entity_group') == 'SUBC'}
    cou_ner_results = {ner.get('word') for ner in ner_results if ner.get('entity_group') == 'COU'}

    # Extract unique INS words (order preserved)
    seen_queries = set()
    ins_queries = []
    for ner in ner_results:
        if ner.get('entity_group') != 'INS':
            continue
        query = ner.get('word')

        if query == "Harvard":
            query = "Harvard University"

        query = query.replace("’", "'").replace(" ' s", "'s").strip()
        
        if query not in seen_queries:
            seen_queries.add(query)
            ins_queries.append(query)

    found_institutions = []
    unmatched_queries = []

    for query in ins_queries:

        # -----------------------
        # CACHE LOOKUP
        # -----------------------
        if query in institution_cache:
            ids, names, countries = institution_cache[query]
            for inst in zip(ids, names, countries):
                found_institutions.append(inst)
            institution_cache.move_to_end(query)
            continue

        # -----------------------
        # EXACT MATCH
        # -----------------------
        records_exact = name_index.get(query, [])
        candidates = {r[0]: r[1] for r in records_exact}
        resolved = []

        # =========================
        # EXACT MATCH: ONE
        # =========================
        if len(candidates) == 1:
            inst_id = next(iter(candidates))
            location = location_index.get(inst_id)
            if location:
                city, country, subdivision = location
                resolved.append((inst_id, candidates[inst_id], country))


        # =========================
        # EXACT MATCH: MULTIPLE
        # =========================
        elif len(candidates) > 1:
            candidate_ids = list(candidates.keys())
            location_map = {
                inst_id: location_index[inst_id]
                for inst_id in candidate_ids
                if inst_id in location_index
            }
            matching_candidates = []
            for inst_id, inst_name in candidates.items():
                if inst_id not in location_map:
                    continue
                city, country, subdivision = location_map[inst_id]
                if country in cou_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))
                elif city in subc_ner_results or subdivision in subc_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))
            if len(matching_candidates) == 1:
                resolved.append(matching_candidates[0])

        

        # =========================
        # EXACT MATCH: ZERO: FUZZY SEARCH
        # =========================
        elif len(candidates) == 0:

            # -----------------------
            # FUZZY SEARCH
            # -----------------------
            records_fuzzy = []
            cursor.execute(
                """
                SELECT institution_id, name, similarity(name, %s) AS sim
                FROM institution_names
                WHERE name %% %s AND similarity(name, %s) >= 0.6
                ORDER BY sim DESC
                LIMIT 10
                """,
                (query, query, query)
            )
            records_fuzzy = cursor.fetchall()
            candidates_fuzzy = {r[0]: r[1] for r in records_fuzzy}

            # -----------------------
            # LOCATION-BASED DISAMBIGUATION
            # -----------------------
            candidate_ids = list(candidates_fuzzy.keys())
            location_map = {inst_id: location_index[inst_id] for inst_id in candidate_ids if inst_id in location_index}
            matching_candidates = []
            for inst_id, inst_name in candidates_fuzzy.items():
                if inst_id not in location_map:
                    continue
                city, country, subdivision = location_map[inst_id]
                if country in cou_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))
                elif city in subc_ner_results or subdivision in subc_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

            # -----------------------
            # ACCEPT IF EXACTLY ONE LOCATION MATCH
            # -----------------------
            if len(matching_candidates) == 1:
                resolved.append(matching_candidates[0])

            # -----------------------
            # FALLBACK: MULTIPLE OR ZERO LOCATION MATCHES
            # -----------------------
            elif len(candidates_fuzzy) > 0:
                deduped = {}
                for inst_id, name, sim in records_fuzzy:
                    if inst_id not in deduped or sim > deduped[inst_id][1]:
                        deduped[inst_id] = (name, sim)

                deduped_sorted = sorted(deduped.items(), key=lambda x: x[1][1], reverse=True)
                top_id, (top_name, top_sim) = deduped_sorted[0]
                second_sim = deduped_sorted[1][1][1] if len(deduped_sorted) > 1 else None
                sim_gap = top_sim - second_sim if second_sim is not None else 0

                location = location_index.get(top_id)
                if location:
                    city, country, subdivision = location
                    if (top_sim >= 0.6 and
                        (country in cou_ner_results
                         or city in subc_ner_results
                         or subdivision in subc_ner_results
                         or sim_gap >= 0.2)):
                        resolved.append((top_id, top_name, country))

        # -----------------------
        # STORE IN CACHE OR TRACK UNMATCHED
        # -----------------------
        if resolved:
            ids, names, countries = zip(*resolved)
            institution_cache[query] = (list(ids), list(names), list(countries))
            if len(institution_cache) > CACHE_SIZE:
                institution_cache.popitem(last=False)
            for inst in resolved:
                found_institutions.append(inst)
        else:
            unmatched_queries.append(query)

    # -----------------------
    # WRITE RESULTS
    # -----------------------
    if found_institutions:
    # Deduplicate by institution_id only
        unique_dict = {}
        for inst_id, inst_name, country in found_institutions:
            if inst_id not in unique_dict:
                unique_dict[inst_id] = (inst_name, country)
    
        ids = list(unique_dict.keys())
        names = [v[0] for v in unique_dict.values()]
        countries = [v[1] for v in unique_dict.values()]
    
        df.at[row, 'Institutions_db_id'] = ids
        df.at[row, 'Institutions_db_name'] = names
        df.at[row, 'Institutions_db_country'] = countries

    if unmatched_queries:
        df.at[row, 'Unmatched_INS'] = unmatched_queries

# -----------------------
# CLOSE CONNECTION
# -----------------------
cursor.close()
connection.close()

Loading institution_names...
Loading institution_locations...
Indices loaded.

100%|████████████████████████████████████████████████████████████████████████████████| 103/103 [00:05<00:00, 17.55it/s]

In [106]:
df[["Institutions_man", "Institutions_db_name"]]

,Institutions_man,Institutions_db_name
0,NaN,[]
1,NaN,[]
2,"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of British Columbia, i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto, University of Porto]"
3,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[Cincinnati Children's Hospital Medical Center, University of Cincinnati, Children's Healthcare of Atlanta, Emory University, Children's Hospital of Los Angeles]"
4,"['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[University of Pennsylvania, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, University of Memphis, Battelle Memorial Institute, University of Chicago, University of Buffalo, Rutgers Biomedical and Health Sciences]"
5,"['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[CONAHCYT, Universidad Nacional Autónoma de México]"
6,"['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[ANR, Inserm, CNRS, Centre de Recherche en Cancérologie de Toulouse, University Cancer Institute Toulouse Oncopole]"
7,['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University]
8,"['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw]
9,"['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']","[Chang Gung University, Linkou Chang Gung Memorial Hospital, Chang Gung Memorial Hospital]"
10,"['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']","[Ruhr University Bochum, BG University Hospital Bergmannsheil Bochum, Ludwig-Maximilians-Universität in Munich, Medical Genetics Center]"
11,"['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[IRCCS Ospedale San Raffaele, Università Vita-Salute San Raffaele]"
12,"['University of Adelaide', 'Queen Elizabeth Hospital']","[University of Adelaide, Queen Elizabeth Hospital]"
13,['University of Zimbabwe'],[University of Zimbabwe]
14,['University of Tokyo Hospital'],[University of Tokyo Hospital]
15,['University Hospital Centre of Grenoble'],[Grenoble University Hospital Centre]
16,['Harvard'],[Harvard University]
17,['University of Washington'],[University of Washington]
18,['University of Würzburg'],[University of Würzburg]
19,"['Mannheim Medical Center', 'University of Heidelberg']",[]
20,NaN,[]
21,['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology]
22,['Duke University Medical Center'],[]
23,"['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]",[Liverpool Women's Hospital]
24,['University of Rochester'],[University of Rochester]
25,['Stavanger University Hospital'],[Stavanger University Hospital]
26,['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[]
27,['Akademii Medycznej w Gdańsku'],[]
28,['Vienna Medical University'],[Medical University of Vienna]
29,"['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]"
30,NaN,[]
31,"['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University]
32,"['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital]
33,"['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University]
34,NaN,[]
35,['Royal North Brisbane Hospital'],[]
36,['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[Azienda Ospedaliero Universitaria Maggiore della Carita]
37,['Universitá degli Studi di Palermo'],[Università degli Studi di Palermo]
38,['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf]
39,NaN,[]
40,"['Institute of Medical Microbiology', 'Charles University']",[Charles University]
41,['Queensland Institute of Medical Research'],[Queensland Institute of Medical Research]
42,['University of Porto'],[University of Porto]
43,"['University of Liverpool', 'Linda McCartney Centre', 'Royal Liverpool University Hospital']","[University of Liverpool, Royal Liverpool University Hospital]"
44,"['University of Leipzig Medical Center', 'University Medical Center Hamburg-Eppendorf', 'Institute for Medical Biostatistics, Epidemiology and Informatics', 'University of Mainz Medical Center', 'University Hospital of Essen', ""Children's Hospital""]","[University Medical Center Hamburg-Eppendorf, Kantonsspital St. Gallen, University of Würzburg, University Medical Center Göttingen, Essen University Hospital, Institute for Medical Informatics and Biostatistics, Children's Hospital, University Hospital Bonn, Düsseldorf University Hospital]"
45,"['Northwestern Memorial Hospital', 'Robert H. Lurie Comprehensive Cancer Center', 'Northwestern University']","[Northwestern Memorial Hospital, Robert H. Lurie Comprehensive Cancer Center, Northwestern University]"
46,"['First Affiliated Hospital', 'Nanchang University']",[First Affiliated Hospital of Nanchang University]
47,"['Suzhou Municipal Hospital', 'Affiliated Suzhou Hospital', 'Nanjing Medical University', ""Shaoxing People's Hospital"", 'Shaoxing Hospital', 'Zhejiang University']","[Suzhou Municipal Hospital, Second Affiliated Hospital of Nanjing Medical University, Shaoxing People's Hospital, Children's Hospital of Zhejiang University]"
48,NaN,[]
49,NaN,[]
50,"['Institute of Biomedical and Genetic Engineering (IBGE)', 'International Islamic University']","[Institute of Biomedical and Genetic Engineering, International Islamic University, Islamabad]"
51,"['Istanbul University', 'Institute of Experimental Medicine', 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital']","[Istanbul University, Yeditepe University]"
52,NaN,[]
53,NaN,[]
54,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', 'Cancer and Blood Disease Institute', ""Boston Children's Hospital"", 'Harvard']","[University of Cincinnati, Cincinnati Children's Hospital Medical Center, Boston Children's Museum, Harvard University]"
55,"['Erasmus MC', 'Utrecht University', 'Erasmus MC Cancer Institute']","[Utrecht University, Erasmus MC Cancer Institute, Erasmus MC]"
56,NaN,[]
57,NaN,[]
58,"['Queen Elizabeth Hospital', 'Royal Victoria Infirmary', 'Medical Research Council Clinical Trials Unit', 'University College London']","[Medical Research Council, University College London, Queen Elizabeth Hospital, Royal Victoria Infirmary]"
59,"['Centro Nacional de Investigaciones Oncológicas (CNIO)', 'Center for Molecular Biology of Heidelberg University (ZMBH)', 'Centro de Investigación en Red de Enfermedades Neurodegenerativas (CIBERNED)', 'University of Cantabria', 'IDIVAL', 'Center for Biomedicine and Medical Technology Mannheim (CBTM)', 'Heidelberg University', 'German Cancer Research Center (DKFZ)', 'Hope Center for Neurological Diseases', 'Washington University']","[Heidelberg University, Center for Molecular Biology Severo Ochoa, Centro de Investigación Biomédica en Red, Enfermedades Neurodegenerativas, University of Cantabria, IDIVAL, Centro Nacional de Investigaciones Oncológicas, German Cancer Research Center, DKFZ-ZMBH Alliance]"
60,"[""King's College London"", 'Comprehensive Biomedical Research Centre', ""Guy's and St Thomas NHS Foundation Trust"", 'Uppsala University', 'Medical Products Agency', 'Karolinska Insituet']","[Karolinska Institutet, UCL Biomedical Research Centre, Guy's and St Thomas' NHS Foundation Trust, King's College London, Uppsala University, Medical Products Agency]"
61,"['August Pi i Sunyer Biomedical Research Institute', 'Hospital Clínic', 'Sant Joan de Deu Childrens Hospital', 'University of Barcelona', 'Nihon University School of Medicine', 'University of Lausanne', 'University of Pennsylvania', 'Catalan Institution for Research and Advanced Studies']","[Sant Joan de Déu-Barcelona Children’s Hospital, University of Barcelona, Nihon University, University of Lausanne, University of Pennsylvania, Catalan Institution for Research and Advanced Studies]"
62,['Delhi State Cancer Institute'],[Delhi State Cancer Institute]
63,"['Kushiro Rosai Hospital', 'Kanagawa Cancer Center', 'Keio University', 'Sapporo Medical University', 'Hijirigaoka Hospital', 'National Hospital Organization', 'Osaka National Hospital', 'Hiroshima University', 'University of Tokyo', 'Tokai Central Hospital', 'Translational Research and Clinical Trial Center', 'Hokkaido University Hospital', 'Japanese Foundation for Multidisciplinary Treatment of Cancer']","[Keio University, Japanese Foundation for Multidisciplinary Treatment of Cancer, Kanagawa Cancer Center, Kushiro Rosai Hospital, The University of Tokyo, National Hospital Organization, Osaka National Hospital, Sapporo Medical University, Hokkaido University Hospital, Tokai Central Hospital, Hiroshima University]"
64,['Life Raft Group'],[]
65,['Washington State University'],[Washington State University]
66,"['Addis Ababa University', 'Karolinska Institutet', 'Karolinska University Hospital', 'Center for Innovative Drug Development and Therapeutic Trials', 'Armauer Hansen Research Institute']","[Karolinska Institutet, Armauer Hansen Research Institute, Addis Ababa University, Karolinska University Hospital]"
67,[nan],[]
68,"['Tulane University', 'Louisiana State University Health Sciences Center']","[Tulane University, Louisiana State University Health Sciences Center New Orleans]"
69,"['Hebei Medical University', 'Bethune International Peace Hospital', 'Hebei University of Chinese Medicine']","[Bethune International Peace Hospital, Hebei Medical University, Hebei University of Chinese Medicine]"
70,"[""Henan Provincial People's Hospital"", ""Zhengzhou University People's Hospital"", ""Henan University People's Hospital"", 'Institute of Hematology']","[Shanghai Institute of Hematology, Henan Provincial People's Hospital, Zhengzhou People's Hospital, Peking University People's Hospital]"
71,"['Huazhong University of Science and Technology Union Shenzhen Hospital (Nanshan Hospital)', ""Shenzhen Second People's Hospital"", 'First Affiliated Hospital', 'Shenzhen University']","[Shenzhen Second People's Hospital, Huazhong University of Science and Technology]"
72,['Medical University of Innsbruck'],[Innsbruck Medical University]
73,"['Stanton L. Young Biomedical Research Center', 'University of Oklahoma Health Science Center']",[University of Oklahoma Health Sciences Center]
74,"['Center for Bioengineering and Tissue Regeneration', 'University of California', 'Gladstone Institutes', 'Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research', 'Helen Diller Family Comprehensive Cancer Center']","[Gladstone Institutes, UCSF Helen Diller Family Comprehensive Cancer Center]"
75,"['Northwestern University', 'Robert H. Lurie Comprehensive Cancer Center']","[Northwestern University, Robert H. Lurie Comprehensive Cancer Center]"
76,"['Qilu Hospital', 'Shandong University', 'Central Hospital', 'Zaozhuang Coal Mining Group', 'Jinan integrative medicine hospital']","[Integrative Medicine Hospital of Nanchang, Qilu Hospital of Shandong University]"
77,"[""St. Jude Children's Research Hospital"", 'Cornell', 'University of Chicago', 'Howard Hughes Medical Institute']","[University of Chicago, St. Jude Children's Research Hospital, Weill Cornell Medicine, Howard Hughes Medical Institute, Memphis Zoo]"
78,['Baylor College of Medicine'],[Baylor College of Medicine]
79,['University of California'],[]
80,NaN,[]
81,NaN,[]
82,"['Second Affiliated Hospital', 'Fujian Medical University', 'Nanjing Medical University']","[Second Affiliated Hospital of Fujian Medical University, Nanjing Medical University]"
83,"['Universidade de São Paulo', 'Universidade do Oeste Paulista UNOESTE', 'Center of Translational Research in Oncology (LIM24)', 'Instituto do Cancer do Estado de Sao Paulo (ICESP)']","[Universidade de São Paulo, Universidade do Oeste Paulista, Instituto do Câncer do Estado de São Paulo]"
84,"['Hepatic Surgery Center', 'Tongji Hospital', 'Huazhong University of Science and Technology', 'Shanxi Bethune Hospital', 'Shanxi Academy of Medical Sciences', 'Shanxi Medical University', 'Shanxi Tongji Hospital']","[Tongji Hospital, Huazhong University of Science and Technology, Bethune Second Hospital, Shanxi Academy of Medical Sciences, Shanxi Medical University]"
85,"['Centre de Recherche des Cordeliers', 'INSERM', 'Sorbonne Université', 'Université Paris Cité', 'Institut universitaire de France', 'Institut Gustave Roussy', 'Centre de Recherche des Cordeliers', 'Klinikum Rechts der Isar', 'Technical University of Munich', 'Institute of Biophysics', 'Czech Academy of Sciences', 'CNRS', 'Institut Polytechnique de Paris', 'Université Paris-Saclay', 'Université Sorbonne Paris Nord', 'Institut du Cancer Paris CARPEM', 'Hôpital Européen Georges Pompidou']","[Czech Academy of Sciences, Université Sorbonne Paris Nord, Klinikum rechts der Isar, Technical University of Munich, Institut Gustave Roussy, Centre de Recherche des Cordeliers, INSERM, Sorbonne Université, Université Paris Cité, Institut Universitaire de France, Hôpital Européen Georges-Pompidou, CNRS, Université Paris-Saclay, École Polytechnique, Institut Polytechnique de Paris]"
86,"['Norwegian University of Science and Technology', 'St. Olavs Hospital', 'Center for Oral Health Services and Research Mid-Norway (TkMidt)', 'Clinic of Medicine', 'K.G. Jebsen Centre for Genetic Epidemiology']",[Norwegian University of Science and Technology]
87,['Mayo Clinic'],[Mayo Clinic]
88,"['University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca', 'Biotechnology Research Center', 'Life Sciences Institute King Michael I of Romania', 'Babeș-Bolyai University']","[University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca, Universitatea Babeș-Bolyai, Banat University of Agricultural Sciences and Veterinary Medicine, Biotechnology Research Center]"
89,"['Graduate Institute of Biomedical Science', 'China Medical University', 'Taichung Tzu Chi Hospital', 'Buddhist Tzu Chi Medical Foundation', 'China Medical University Hospital', 'Asia University', 'Institute of New Drug Development']","[China Medical University, China Medical University Hospital, Taichung Hospital, Buddhist Tzu Chi Medical Foundation, Tzu Chi University]"
90,"['Chongqing University Three Gorges Hospital', 'Center for Medicine Research and Translation', ""Chengdu Fifth People's Hospital""]","[Chongqing Three Gorges University, Chengdu Fifth People's Hospital]"
91,"['Boston University', 'Shaukat Khanum Memorial Cancer Hospital and Research Centre']","[Shaukat Khanum Memorial Cancer Hospital and Research Center, Boston University]"
92,NaN,[]
93,NaN,[]
94,['Georgetown University Medical Center'],[Georgetown University Medical Center]
95,['University of South Florida'],[University of South Florida]
96,['Johns Hopkins Oncology Center'],[]
97,"['Albert Einstein Cancer Center', 'Montefiore Medical Center']","[Albert Einstein Cancer Center at Montefiore, Montefiore Medical Center]"
98,['General Hospital Manuel Gea Gonzalez'],[Hospital General Dr. Manuel Gea Gonzalez]
99,['University Hospital Leiden'],[Leiden University]
100,['Paul Scherrer Institute'],[Paul Scherrer Institute]
101,['Wayne State University'],[Wayne State University]
102,[],[]

In [107]:
counter_hits(df)

(272, 202)

# NEW BENCHMARK : IF THERE ARE TWO INSTITUTIONS WITH LESS THAN 0.2 sim DIFF AND THEY ARE RELATED IN THE institution_relationships TABLE (AND COU OR SUBCOU MATCH), ADD THE TOP

In [108]:
df_2 = df.copy(deep = True)

In [158]:
from collections import OrderedDict
import psycopg2
import pandas as pd
import ast
import re
from tqdm import tqdm

# -----------------------
# CACHE (LRU size = 1000)
# -----------------------
CACHE_SIZE = 1000
institution_cache = OrderedDict()

# -----------------------
# PRE-CREATE RESULT COLUMNS
# -----------------------
df_2['Institutions_db_id'] = [[] for _ in range(len(df_2))]
df_2['Institutions_db_name'] = [[] for _ in range(len(df_2))]
df_2['Institutions_db_country'] = [[] for _ in range(len(df_2))]
df_2['Unmatched_INS'] = [[] for _ in range(len(df_2))]

# -----------------------
# DB CONNECTION
# -----------------------
connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)

cursor = connection.cursor()
cursor.execute("SET pg_trgm.similarity_threshold = 0.6")

# -----------------------
# LOAD DATABASE TABLES INTO MEMORY
# -----------------------
print("Loading institution_names...")
cursor.execute("SELECT institution_id, name FROM institution_names")
rows = cursor.fetchall()

name_index = {}
for inst_id, name in rows:
    name_index.setdefault(name, []).append((inst_id, name))


print("Loading institution_locations...")
cursor.execute("""
    SELECT institution_id, city_name, country_name, subdivision_name
    FROM institution_locations
""")

rows = cursor.fetchall()
location_index = {r[0]: (r[1], r[2], r[3]) for r in rows}


print("Loading institution_relationships...")
cursor.execute("""
    SELECT child_institution_id, parent_institution_id
    FROM institution_relationships
""")

rows = cursor.fetchall()

relationship_index = set()
for child_id, parent_id in rows:
    relationship_index.add((child_id, parent_id))
    relationship_index.add((parent_id, child_id))

print("Indices loaded.")

# -----------------------
# MAIN LOOP
# -----------------------
for row in tqdm(range(len(df))):

    if pd.isna(df.at[row, "NER_BERT"]):
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = {
        ner.get('word')
        for ner in ner_results
        if ner.get('entity_group') == 'SUBC'
    }

    cou_ner_results = {
        ner.get('word')
        for ner in ner_results
        if ner.get('entity_group') == 'COU'
    }

    # -----------------------
    # EXTRACT UNIQUE INS
    # -----------------------
    seen_queries = set()
    ins_queries = []

    for ner in ner_results:

        if ner.get('entity_group') != 'INS':
            continue

        query = ner.get('word')

        if query == "Harvard":
            query = "Harvard University"

        query = query.replace("’", "'").replace(" ' s", "'s").strip()

        if query not in seen_queries:
            seen_queries.add(query)
            ins_queries.append(query)

    found_institutions = []
    unmatched_queries = []

    # -----------------------
    # PROCESS EACH QUERY
    # -----------------------
    for query in ins_queries:

        # -----------------------
        # CACHE LOOKUP
        # -----------------------
        if query in institution_cache:

            ids, names, countries = institution_cache[query]

            for inst in zip(ids, names, countries):
                found_institutions.append(inst)

            institution_cache.move_to_end(query)
            continue

        # -----------------------
        # EXACT MATCH
        # -----------------------
        records_exact = name_index.get(query, [])
        candidates = {r[0]: r[1] for r in records_exact}

        resolved = []

        # =========================
        # EXACT MATCH: ONE
        # =========================
        if len(candidates) == 1:

            inst_id = next(iter(candidates))
            location = location_index.get(inst_id)

            if location:
                city, country, subdivision = location
                resolved.append((inst_id, candidates[inst_id], country))

        # =========================
        # EXACT MATCH: MULTIPLE
        # =========================
        elif len(candidates) > 1:
            # Get locations for all candidate IDs
            candidate_ids = list(candidates.keys())
            location_map = {inst_id: location_index.get(inst_id) for inst_id in candidate_ids if inst_id in location_index}

        # Step 1: Filter candidates by location match (country or subcountry)
        location_matches = []
        for inst_id, inst_name in candidates.items():
            loc = location_map.get(inst_id)
            if not loc:
                continue
            city, country, subdivision = loc
            if country in cou_ner_results or city in subc_ner_results or subdivision in subc_ner_results:
                location_matches.append((inst_id, inst_name, country))

        # Step 2: Resolve if exactly one location match
        if len(location_matches) == 1:
            resolved.append(location_matches[0])

        # Step 3: If multiple location matches or zero, apply relationship rule
        elif len(location_matches) > 1:
            # Pick the first candidate that has a relationship with any other
            found = False
            for i, (inst_id_i, name_i, country_i) in enumerate(location_matches):
                for j, (inst_id_j, name_j, country_j) in enumerate(location_matches):
                    if i == j:
                        continue
                    if (inst_id_i, inst_id_j) in relationship_index:
                        resolved.append((inst_id_i, name_i, country_i))
                        found = True
                        break
                if found:
                    break

        # =========================
        # FUZZY SEARCH
        # =========================
        elif len(candidates) == 0:

            cursor.execute(
                """
                SELECT institution_id, name, similarity(name, %s) AS sim
                FROM institution_names
                WHERE name %% %s
                AND similarity(name, %s) >= 0.6
                ORDER BY sim DESC
                LIMIT 10
                """,
                (query, query, query)
            )

            records_fuzzy = cursor.fetchall()

            candidates_fuzzy = {r[0]: r[1] for r in records_fuzzy}

            candidate_ids = list(candidates_fuzzy.keys())

            location_map = {
                inst_id: location_index[inst_id]
                for inst_id in candidate_ids
                if inst_id in location_index
            }

            matching_candidates = []

            for inst_id, inst_name in candidates_fuzzy.items():

                if inst_id not in location_map:
                    continue

                city, country, subdivision = location_map[inst_id]

                if country in cou_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

                elif city in subc_ner_results or subdivision in subc_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

            # -----------------------
            # ACCEPT IF ONE LOCATION MATCH
            # -----------------------
            if len(matching_candidates) == 1:
                resolved.append(matching_candidates[0])

            # -----------------------
            # FALLBACK
            # -----------------------
            elif len(candidates_fuzzy) > 0:

                deduped = {}

                for inst_id, name, sim in records_fuzzy:

                    if inst_id not in deduped or sim > deduped[inst_id][1]:
                        deduped[inst_id] = (name, sim)

                deduped_sorted = sorted(
                    deduped.items(),
                    key=lambda x: x[1][1],
                    reverse=True
                )

                top_id, (top_name, top_sim) = deduped_sorted[0]

                second_sim = (
                    deduped_sorted[1][1][1]
                    if len(deduped_sorted) > 1
                    else None
                )

                sim_gap = (
                    top_sim - second_sim
                    if second_sim is not None
                    else 0
                )

                location = location_index.get(top_id)

                if location:

                    city, country, subdivision = location

                    location_match = (
                        country in cou_ner_results
                        or city in subc_ner_results
                        or subdivision in subc_ner_results
                    )

                    # STANDARD ACCEPTANCE
                    if top_sim >= 0.6 and (location_match or sim_gap >= 0.2):
                        resolved.append((top_id, top_name, country))

                    # ACCEPT BASED ON SIM DISTANCE
                    elif (
                        second_sim is not None
                        and sim_gap < 0.2
                        and location_match
                    ):

                        second_id = deduped_sorted[1][0]

                        if (top_id, second_id) in relationship_index:
                            resolved.append((top_id, top_name, country))

        # -----------------------
        # CACHE OR UNMATCHED
        # -----------------------
        if resolved:

            ids, names, countries = zip(*resolved)

            institution_cache[query] = (
                list(ids),
                list(names),
                list(countries)
            )

            if len(institution_cache) > CACHE_SIZE:
                institution_cache.popitem(last=False)

            for inst in resolved:
                found_institutions.append(inst)

        else:
            unmatched_queries.append(query)

    # -----------------------
    # WRITE RESULTS
    # -----------------------
    if found_institutions:

        unique_dict = {}

        for inst_id, inst_name, country in found_institutions:
            if inst_id not in unique_dict:
                unique_dict[inst_id] = (inst_name, country)

        ids = list(unique_dict.keys())
        names = [v[0] for v in unique_dict.values()]
        countries = [v[1] for v in unique_dict.values()]

        df_2.at[row, 'Institutions_db_id'] = ids
        df_2.at[row, 'Institutions_db_name'] = names
        df_2.at[row, 'Institutions_db_country'] = countries

    if unmatched_queries:
        df_2.at[row, 'Unmatched_INS'] = unmatched_queries


# -----------------------
# CLOSE CONNECTION
# -----------------------
cursor.close()
connection.close()

Loading institution_names...
Loading institution_locations...
Loading institution_relationships...
Indices loaded.

100%|████████████████████████████████████████████████████████████████████████████████| 103/103 [00:05<00:00, 17.26it/s]

In [159]:
df_2[["Institutions_man", "Institutions_db_name"]]

,Institutions_man,Institutions_db_name
0,NaN,[]
1,NaN,[]
2,"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of British Columbia, i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto, Institute of Molecular Pathology and Immunology of the University of Porto, University of Porto]"
3,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[Cincinnati Children's Hospital Medical Center, University of Cincinnati, Children's Healthcare of Atlanta, Emory University, Children's Hospital of Los Angeles]"
4,"['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[University of Pennsylvania, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, University of Memphis, Battelle Memorial Institute, University of Chicago, University of Buffalo, Rutgers Institute for Nicotine & Tobacco Studies, Rutgers Biomedical and Health Sciences]"
5,"['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[CONAHCYT, Universidad Nacional Autónoma de México]"
6,"['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[ANR, Université de Toulouse, Inserm, CNRS, Centre de Recherche en Cancérologie de Toulouse, University Cancer Institute Toulouse Oncopole]"
7,['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University]
8,"['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw]
9,"['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']","[Chang Gung University, Linkou Chang Gung Memorial Hospital, Chang Gung Memorial Hospital]"
10,"['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']","[Ruhr University Bochum, BG University Hospital Bergmannsheil Bochum, Ludwig-Maximilians-Universität in Munich, Medical Genetics Center]"
11,"['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[IRCCS Ospedale San Raffaele, Università Vita-Salute San Raffaele]"
12,"['University of Adelaide', 'Queen Elizabeth Hospital']","[University of Adelaide, Queen Elizabeth Hospital]"
13,['University of Zimbabwe'],[University of Zimbabwe]
14,['University of Tokyo Hospital'],[University of Tokyo Hospital]
15,['University Hospital Centre of Grenoble'],[Grenoble University Hospital Centre]
16,['Harvard'],[Harvard University]
17,['University of Washington'],[University of Washington]
18,['University of Würzburg'],[University of Würzburg]
19,"['Mannheim Medical Center', 'University of Heidelberg']",[]
20,NaN,[]
21,['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology]
22,['Duke University Medical Center'],[Duke University Medical Center]
23,"['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]","[Hewitt Centre for Reproductive Medicine, Liverpool Women's Hospital]"
24,['University of Rochester'],[University of Rochester]
25,['Stavanger University Hospital'],[Stavanger University Hospital]
26,['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[]
27,['Akademii Medycznej w Gdańsku'],[]
28,['Vienna Medical University'],[Medical University of Vienna]
29,"['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]"
30,NaN,[]
31,"['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University]
32,"['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital]
33,"['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University]
34,NaN,[]
35,['Royal North Brisbane Hospital'],[]
36,['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[Azienda Ospedaliero Universitaria Maggiore della Carita]
37,['Universitá degli Studi di Palermo'],[Università degli Studi di Palermo]
38,['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf]
39,NaN,[]
40,"['Institute of Medical Microbiology', 'Charles University']",[Charles University]
41,['Queensland Institute of Medical Research'],[Queensland Institute of Medical Research]
42,['University of Porto'],[University of Porto]
43,"['University of Liverpool', 'Linda McCartney Centre', 'Royal Liverpool University Hospital']","[University of Liverpool, Royal Liverpool University Hospital]"
44,"['University of Leipzig Medical Center', 'University Medical Center Hamburg-Eppendorf', 'Institute for Medical Biostatistics, Epidemiology and Informatics', 'University of Mainz Medical Center', 'University Hospital of Essen', ""Children's Hospital""]","[University Medical Center Hamburg-Eppendorf, Kantonsspital St. Gallen, University of Würzburg, University Medical Center Göttingen, Essen University Hospital, Institute for Medical Informatics and Biostatistics, Children's Hospital, University Hospital Bonn, Düsseldorf University Hospital]"
45,"['Northwestern Memorial Hospital', 'Robert H. Lurie Comprehensive Cancer Center', 'Northwestern University']","[Northwestern Memorial Hospital, Robert H. Lurie Comprehensive Cancer Center, Northwestern University]"
46,"['First Affiliated Hospital', 'Nanchang University']",[First Affiliated Hospital of Nanchang University]
47,"['Suzhou Municipal Hospital', 'Affiliated Suzhou Hospital', 'Nanjing Medical University', ""Shaoxing People's Hospital"", 'Shaoxing Hospital', 'Zhejiang University']","[Suzhou Municipal Hospital, Second Affiliated Hospital of Nanjing Medical University, Shaoxing People's Hospital, Children's Hospital of Zhejiang University]"
48,NaN,[]
49,NaN,[]
50,"['Institute of Biomedical and Genetic Engineering (IBGE)', 'International Islamic University']","[Institute of Biomedical and Genetic Engineering, International Islamic University, Islamabad]"
51,"['Istanbul University', 'Institute of Experimental Medicine', 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital']","[Istanbul University, Yeditepe University]"
52,NaN,[]
53,NaN,[]
54,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', 'Cancer and Blood Disease Institute', ""Boston Children's Hospital"", 'Harvard']","[University of Cincinnati, Cincinnati Children's Hospital Medical Center, Boston Children's Museum, Harvard University]"
55,"['Erasmus MC', 'Utrecht University', 'Erasmus MC Cancer Institute']","[Utrecht University, Erasmus MC Cancer Institute, Erasmus MC]"
56,NaN,[]
57,NaN,[]
58,"['Queen Elizabeth Hospital', 'Royal Victoria Infirmary', 'Medical Research Council Clinical Trials Unit', 'University College London']","[Medical Research Council, University College London, Queen Elizabeth Hospital, Royal Victoria Infirmary]"
59,"['Centro Nacional de Investigaciones Oncológicas (CNIO)', 'Center for Molecular Biology of Heidelberg University (ZMBH)', 'Centro de Investigación en Red de Enfermedades Neurodegenerativas (CIBERNED)', 'University of Cantabria', 'IDIVAL', 'Center for Biomedicine and Medical Technology Mannheim (CBTM)', 'Heidelberg University', 'German Cancer Research Center (DKFZ)', 'Hope Center for Neurological Diseases', 'Washington University']","[Heidelberg University, Center for Molecular Biology Severo Ochoa, Centro de Investigación Biomédica en Red, Enfermedades Neurodegenerativas, University of Cantabria, IDIVAL, Centro Nacional de Investigaciones Oncológicas, German Cancer Research Center, DKFZ-ZMBH Alliance]"
60,"[""King's College London"", 'Comprehensive Biomedical Research Centre', ""Guy's and St Thomas NHS Foundation Trust"", 'Uppsala University', 'Medical Products Agency', 'Karolinska Insituet']","[Karolinska Institutet, UCL Biomedical Research Centre, Guy's and St Thomas' NHS Foundation Trust, King's College London, Uppsala University, Medical Products Agency]"
61,"['August Pi i Sunyer Biomedical Research Institute', 'Hospital Clínic', 'Sant Joan de Deu Childrens Hospital', 'University of Barcelona', 'Nihon University School of Medicine', 'University of Lausanne', 'University of Pennsylvania', 'Catalan Institution for Research and Advanced Studies']","[Sant Joan de Déu-Barcelona Children’s Hospital, University of Barcelona, Nihon University, University of Lausanne, University of Pennsylvania, Catalan Institution for Research and Advanced Studies]"
62,['Delhi State Cancer Institute'],[Delhi State Cancer Institute]
63,"['Kushiro Rosai Hospital', 'Kanagawa Cancer Center', 'Keio University', 'Sapporo Medical University', 'Hijirigaoka Hospital', 'National Hospital Organization', 'Osaka National Hospital', 'Hiroshima University', 'University of Tokyo', 'Tokai Central Hospital', 'Translational Research and Clinical Trial Center', 'Hokkaido University Hospital', 'Japanese Foundation for Multidisciplinary Treatment of Cancer']","[Keio University, Japanese Foundation for Multidisciplinary Treatment of Cancer, Kanagawa Cancer Center, Kushiro Rosai Hospital, The University of Tokyo, National Hospital Organization, Osaka National Hospital, Sapporo Medical University, Hokkaido University Hospital, Tokai Central Hospital, Hiroshima University]"
64,['Life Raft Group'],[]
65,['Washington State University'],[Washington State University]
66,"['Addis Ababa University', 'Karolinska Institutet', 'Karolinska University Hospital', 'Center for Innovative Drug Development and Therapeutic Trials', 'Armauer Hansen Research Institute']","[Karolinska Institutet, Armauer Hansen Research Institute, Addis Ababa University, Karolinska University Hospital]"
67,[nan],[]
68,"['Tulane University', 'Louisiana State University Health Sciences Center']","[Tulane University, Louisiana State University Health Sciences Center New Orleans]"
69,"['Hebei Medical University', 'Bethune International Peace Hospital', 'Hebei University of Chinese Medicine']","[Bethune International Peace Hospital, Hebei Medical University, Hebei University of Chinese Medicine]"
70,"[""Henan Provincial People's Hospital"", ""Zhengzhou University People's Hospital"", ""Henan University People's Hospital"", 'Institute of Hematology']","[Shanghai Institute of Hematology, Henan Provincial People's Hospital, Zhengzhou People's Hospital, Peking University People's Hospital]"
71,"['Huazhong University of Science and Technology Union Shenzhen Hospital (Nanshan Hospital)', ""Shenzhen Second People's Hospital"", 'First Affiliated Hospital', 'Shenzhen University']","[Shenzhen Second People's Hospital, Huazhong University of Science and Technology]"
72,['Medical University of Innsbruck'],[Innsbruck Medical University]
73,"['Stanton L. Young Biomedical Research Center', 'University of Oklahoma Health Science Center']",[University of Oklahoma Health Sciences Center]
74,"['Center for Bioengineering and Tissue Regeneration', 'University of California', 'Gladstone Institutes', 'Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research', 'Helen Diller Family Comprehensive Cancer Center']","[Gladstone Institutes, UCSF Helen Diller Family Comprehensive Cancer Center]"
75,"['Northwestern University', 'Robert H. Lurie Comprehensive Cancer Center']","[Northwestern University, Robert H. Lurie Comprehensive Cancer Center]"
76,"['Qilu Hospital', 'Shandong University', 'Central Hospital', 'Zaozhuang Coal Mining Group', 'Jinan integrative medicine hospital']","[Integrative Medicine Hospital of Nanchang, Qilu Hospital of Shandong University]"
77,"[""St. Jude Children's Research Hospital"", 'Cornell', 'University of Chicago', 'Howard Hughes Medical Institute']","[University of Chicago, St. Jude Children's Research Hospital, Weill Cornell Medicine, Howard Hughes Medical Institute, Memphis Zoo]"
78,['Baylor College of Medicine'],[Baylor College of Medicine]
79,['University of California'],[]
80,NaN,[]
81,NaN,[]
82,"['Second Affiliated Hospital', 'Fujian Medical University', 'Nanjing Medical University']","[Second Affiliated Hospital of Fujian Medical University, Nanjing Medical University]"
83,"['Universidade de São Paulo', 'Universidade do Oeste Paulista UNOESTE', 'Center of Translational Research in Oncology (LIM24)', 'Instituto do Cancer do Estado de Sao Paulo (ICESP)']","[Universidade de São Paulo, Universidade do Oeste Paulista, Instituto do Câncer do Estado de São Paulo]"
84,"['Hepatic Surgery Center', 'Tongji Hospital', 'Huazhong University of Science and Technology', 'Shanxi Bethune Hospital', 'Shanxi Academy of Medical Sciences', 'Shanxi Medical University', 'Shanxi Tongji Hospital']","[Tongji Hospital, Huazhong University of Science and Technology, Bethune Second Hospital, Shanxi Academy of Medical Sciences, Shanxi Medical University]"
85,"['Centre de Recherche des Cordeliers', 'INSERM', 'Sorbonne Université', 'Université Paris Cité', 'Institut universitaire de France', 'Institut Gustave Roussy', 'Centre de Recherche des Cordeliers', 'Klinikum Rechts der Isar', 'Technical University of Munich', 'Institute of Biophysics', 'Czech Academy of Sciences', 'CNRS', 'Institut Polytechnique de Paris', 'Université Paris-Saclay', 'Université Sorbonne Paris Nord', 'Institut du Cancer Paris CARPEM', 'Hôpital Européen Georges Pompidou']","[Czech Academy of Sciences, Université Sorbonne Paris Nord, Klinikum rechts der Isar, Technical University of Munich, Institut Gustave Roussy, Centre de Recherche des Cordeliers, INSERM, Sorbonne Université, Université Paris Cité, Institut Universitaire de France, Hôpital Européen Georges-Pompidou, CNRS, Université Paris-Saclay, École Polytechnique, Institut Polytechnique de Paris]"
86,"['Norwegian University of Science and Technology', 'St. Olavs Hospital', 'Center for Oral Health Services and Research Mid-Norway (TkMidt)', 'Clinic of Medicine', 'K.G. Jebsen Centre for Genetic Epidemiology']",[Norwegian University of Science and Technology]
87,['Mayo Clinic'],[Mayo Clinic]
88,"['University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca', 'Biotechnology Research Center', 'Life Sciences Institute King Michael I of Romania', 'Babeș-Bolyai University']","[University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca, Universitatea Babeș-Bolyai, Banat University of Agricultural Sciences and Veterinary Medicine, Biotechnology Research Center]"
89,"['Graduate Institute of Biomedical Science', 'China Medical University', 'Taichung Tzu Chi Hospital', 'Buddhist Tzu Chi Medical Foundation', 'China Medical University Hospital', 'Asia University', 'Institute of New Drug Development']","[Asia University, China Medical University, China Medical University Hospital, Taichung Hospital, Buddhist Tzu Chi Medical Foundation, Tzu Chi University]"
90,"['Chongqing University Three Gorges Hospital', 'Center for Medicine Research and Translation', ""Chengdu Fifth People's Hospital""]","[Chongqing Three Gorges University, Chengdu Fifth People's Hospital]"
91,"['Boston University', 'Shaukat Khanum Memorial Cancer Hospital and Research Centre']","[Shaukat Khanum Memorial Cancer Hospital and Research Center, Boston University]"
92,NaN,[]
93,NaN,[]
94,['Georgetown University Medical Center'],[Georgetown University Medical Center]
95,['University of South Florida'],[University of South Florida]
96,['Johns Hopkins Oncology Center'],[]
97,"['Albert Einstein Cancer Center', 'Montefiore Medical Center']","[Albert Einstein Cancer Center at Montefiore, Montefiore Medical Center]"
98,['General Hospital Manuel Gea Gonzalez'],[Hospital General Dr. Manuel Gea Gonzalez]
99,['University Hospital Leiden'],[Leiden University]
100,['Paul Scherrer Institute'],[Paul Scherrer Institute]
101,['Wayne State University'],[Wayne State University]
102,[],[]

In [160]:
df_2[["Institutions_man", "Institutions_db_name", "Unmatched_INS"]]

,Institutions_man,Institutions_db_name,Unmatched_INS
0,NaN,[],[]
1,NaN,[],[]
2,"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of British Columbia, i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto, Institute of Molecular Pathology and Immunology of the University of Porto, University of Porto]","[Hereditary Cancer, BC Cancer]"
3,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[Cincinnati Children's Hospital Medical Center, University of Cincinnati, Children's Healthcare of Atlanta, Emory University, Children's Hospital of Los Angeles]","[Aflac Cancer and Blood Disorders Center, GoBroad Hospital]"
4,"['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[University of Pennsylvania, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, University of Memphis, Battelle Memorial Institute, University of Chicago, University of Buffalo, Rutgers Institute for Nicotine & Tobacco Studies, Rutgers Biomedical and Health Sciences]","[Independent Contractor, TSET Health Promotion Research Center]"
5,"['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[CONAHCYT, Universidad Nacional Autónoma de México]","[Center for Research on Population Health, National Institute of Public Health, Institute for Research in Applied Mathematics and Systems, Harvard T. H. Chan, Center for Research on Evaluation and Surveys]"
6,"['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[ANR, Université de Toulouse, Inserm, CNRS, Centre de Recherche en Cancérologie de Toulouse, University Cancer Institute Toulouse Oncopole]","[Labex TOUCAN, Equipe SigDYN, Hubert Curien, Oncopole de Toulouse, TOUCAN, Curien, Joliot - Curie]"
7,['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University],[]
8,"['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw],[Institute of Developmental Biology and Biomedical Sciences]
9,"['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']","[Chang Gung University, Linkou Chang Gung Memorial Hospital, Chang Gung Memorial Hospital]",[]
10,"['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']","[Ruhr University Bochum, BG University Hospital Bergmannsheil Bochum, Ludwig-Maximilians-Universität in Munich, Medical Genetics Center]",[Friedrich - Baur - Institute]
11,"['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[IRCCS Ospedale San Raffaele, Università Vita-Salute San Raffaele]",[Diabetes Research Institute]
12,"['University of Adelaide', 'Queen Elizabeth Hospital']","[University of Adelaide, Queen Elizabeth Hospital]",[]
13,['University of Zimbabwe'],[University of Zimbabwe],[]
14,['University of Tokyo Hospital'],[University of Tokyo Hospital],[]
15,['University Hospital Centre of Grenoble'],[Grenoble University Hospital Centre],[]
16,['Harvard'],[Harvard University],[]
17,['University of Washington'],[University of Washington],[]
18,['University of Würzburg'],[University of Würzburg],[]
19,"['Mannheim Medical Center', 'University of Heidelberg']",[],"[Mannheim Medical Center, University of Heidelberg]"
20,NaN,[],[]
21,['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology],[]
22,['Duke University Medical Center'],[Duke University Medical Center],[]
23,"['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]","[Hewitt Centre for Reproductive Medicine, Liverpool Women's Hospital]",[]
24,['University of Rochester'],[University of Rochester],[]
25,['Stavanger University Hospital'],[Stavanger University Hospital],[]
26,['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[],[Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii]
27,['Akademii Medycznej w Gdańsku'],[],[Akademii Medycznej w Gdańsku]
28,['Vienna Medical University'],[Medical University of Vienna],[]
29,"['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]",[]
30,NaN,[],[]
31,"['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University],[Center for Gerontology and Health Care Research]
32,"['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital],[Tianjin Lung Cancer Institute]
33,"['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University],[Evidence Based Medicine Center]
34,NaN,[],[]
35,['Royal North Brisbane Hospital'],[],[Royal North Brisbane Hospital]
36,['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[Azienda Ospedaliero Universitaria Maggiore della Carita],[]
37,['Universitá degli Studi di Palermo'],[Università degli Studi di Palermo],[]
38,['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf],[]
39,NaN,[],[]
40,"['Institute of Medical Microbiology', 'Charles University']",[Charles University],[Institute of Medical Microbiology]
41,['Queensland Institute of Medical Research'],[Queensland Institute of Medical Research],[]
42,['University of Porto'],[University of Porto],[]
43,"['University of Liverpool', 'Linda McCartney Centre', 'Royal Liverpool University Hospital']","[University of Liverpool, Royal Liverpool University Hospital]",[Linda McCartney Centre]
44,"['University of Leipzig Medical Center', 'University Medical Center Hamburg-Eppendorf', 'Institute for Medical Biostatistics, Epidemiology and Informatics', 'University of Mainz Medical Center', 'University Hospital of Essen', ""Children's Hospital""]","[University Medical Center Hamburg-Eppendorf, Kantonsspital St. Gallen, University of Würzburg, University Medical Center Göttingen, Essen University Hospital, Institute for Medical Informatics and Biostatistics, Children's Hospital, University Hospital Bonn, Düsseldorf University Hospital]","[University of Leipzig Medical Center, University of Mainz Medical Center, University of Bonn Medical Center, Clinic and Policlinic for Radiation Therapy and Radiooncology]"
45,"['Northwestern Memorial Hospital', 'Robert H. Lurie Comprehensive Cancer Center', 'Northwestern University']","[Northwestern Memorial Hospital, Robert H. Lurie Comprehensive Cancer Center, Northwestern University]",[]
46,"['First Affiliated Hospital', 'Nanchang University']",[First Affiliated Hospital of Nanchang University],[]
47,"['Suzhou Municipal Hospital', 'Affiliated Suzhou Hospital', 'Nanjing Medical University', ""Shaoxing People's Hospital"", 'Shaoxing Hospital', 'Zhejiang University']","[Suzhou Municipal Hospital, Second Affiliated Hospital of Nanjing Medical University, Shaoxing People's Hospital, Children's Hospital of Zhejiang University]",[]
48,NaN,[],[]
49,NaN,[],[]
50,"['Institute of Biomedical and Genetic Engineering (IBGE)', 'International Islamic University']","[Institute of Biomedical and Genetic Engineering, International Islamic University, Islamabad]",[]
51,"['Istanbul University', 'Institute of Experimental Medicine', 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital']","[Istanbul University, Yeditepe University]","[Institute of Experimental Medicine, Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital]"
52,NaN,[],[]
53,NaN,[],[]
54,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', 'Cancer and Blood Disease Institute', ""Boston Children's Hospital"", 'Harvard']","[University of Cincinnati, Cincinnati Children's Hospital Medical Center, Boston Children's Museum, Harvard University]","[Cancer and Blood Disease Institute, Hospital]"
55,"['Erasmus MC', 'Utrecht University', 'Erasmus MC Cancer Institute']","[Utrecht University, Erasmus MC Cancer Institute, Erasmus MC]",[]
56,NaN,[],[]
57,NaN,[],[]
58,"['Queen Elizabeth Hospital', 'Royal Victoria Infirmary', 'Medical Research Council Clinical Trials Unit', 'University College London']","[Medical Research Council, University College London, Queen Elizabeth Hospital, Royal Victoria Infirmary]",[]
59,"['Centro Nacional de Investigaciones Oncológicas (CNIO)', 'Center for Molecular Biology of Heidelberg University (ZMBH)', 'Centro de Investigación en Red de Enfermedades Neurodegenerativas (CIBERNED)', 'University of Cantabria', 'IDIVAL', 'Center for Biomedicine and Medical Technology Mannheim (CBTM)', 'Heidelberg University', 'German Cancer Research Center (DKFZ)', 'Hope Center for Neurological Diseases', 'Washington University']","[Heidelberg University, Center for Molecular Biology Severo Ochoa, Centro de Investigación Biomédica en Red, Enfermedades Neurodegenerativas, University of Cantabria, IDIVAL, Centro Nacional de Investigaciones Oncológicas, German Cancer Research Center, DKFZ-ZMBH Alliance]","[Center for Biomedicine and Medical Technology Mannheim ( CBTM ), Hope Center for Neurological Diseases, Washington University, Heidelberg University ( ZMBH )]"
60,"[""King's College London"", 'Comprehensive Biomedical Research Centre', ""Guy's and St Thomas NHS Foundation Trust"", 'Uppsala University', 'Medical Products Agency', 'Karolinska Insituet']","[Karolinska Institutet, UCL Biomedical Research Centre, Guy's and St Thomas' NHS Foundation Trust, King's College London, Uppsala University, Medical Products Agency]",[]
61,"['August Pi i Sunyer Biomedical Research Institute', 'Hospital Clínic', 'Sant Joan de Deu Childrens Hospital', 'University of Barcelona', 'Nihon University School of Medicine', 'University of Lausanne', 'University of Pennsylvania', 'Catalan Institution for Research and Advanced Studies']","[Sant Joan de Déu-Barcelona Children’s Hospital, University of Barcelona, Nihon University, University of Lausanne, University of Pennsylvania, Catalan Institution for Research and Advanced Studies]","[August Pi i Sunyer Biomedical Research Institute, Hospital Clínic, . R. R, University, Research, D]"
62,['Delhi State Cancer Institute'],[Delhi State Cancer Institute],[]
63,"['Kushiro Rosai Hospital', 'Kanagawa Cancer Center', 'Keio University', 'Sapporo Medical University', 'Hijirigaoka Hospital', 'National Hospital Organization', 'Osaka National Hospital', 'Hiroshima University', 'University of Tokyo', 'Tokai Central Hospital', 'Translational Research and Clinical Trial Center', 'Hokkaido University Hospital', 'Japanese Foundation for Multidisciplinary Treatment of Cancer']","[Keio University, Japanese Foundation for Multidisciplinary Treatment of Cancer, Kanagawa Cancer Center, Kushiro Rosai Hospital, The University of Tokyo, National Hospital Organization, Osaka National Hospital, Sapporo Medical University, Hokkaido University Hospital, Tokai Central Hospital, Hiroshima University]","[Translational Research and Clinical Trial Center, Hijirigaoka Hospital]"
64,['Life Raft Group'],[],[]
65,['Washington State University'],[Washington State University],[]
66,"['Addis Ababa University', 'Karolinska Institutet', 'Karolinska University Hospital', 'Center for Innovative Drug Development and Therapeutic Trials', 'Armauer Hansen Research Institute']","[Karolinska Institutet, Armauer Hansen Research Institute, Addis Ababa University, Karolinska University Hospital]",[for Innovative Drug Development and Therapeutic Trials]
67,[nan],[],"[Unità di Biochimica, Unità di Fisiologia Generale]"
68,"['Tulane University', 'Louisiana State University Health Sciences Center']","[Tulane University, Louisiana State University Health Sciences Center New Orleans]",[]
69,"['Hebei Medical University', 'Bethune International Peace Hospital', 'Hebei University of Chinese Medicine']","[Bethune International Peace Hospital, Hebei Medical University, Hebei University of Chinese Medicine]",[]
70,"[""Henan Provincial People's Hospital"", ""Zhengzhou University People's Hospital"", ""Henan University People's Hospital"", 'Institute of Hematology']","[Shanghai Institute of Hematology, Henan Provincial People's Hospital, Zhengzhou People's Hospital, Peking University People's Hospital]",[]
71,"['Huazhong University of Science and Technology Union Shenzhen Hospital (Nanshan Hospital)', ""Shenzhen Second People's Hospital"", 'First Affiliated Hospital', 'Shenzhen University']","[Shenzhen Second People's Hospital, Huazhong University of Science and Technology]",[Shenzhen Hospital ( Nanshan Hospital )]
72,['Medical University of Innsbruck'],[Innsbruck Medical University],[]
73,"['Stanton L. Young Biomedical Research Center', 'University of Oklahoma Health Science Center']",[University of Oklahoma Health Sciences Center],"[Cancer, Oklahoma Stanton L. Young Biomedical Research Center]"
74,"['Center for Bioengineering and Tissue Regeneration', 'University of California', 'Gladstone Institutes', 'Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research', 'Helen Diller Family Comprehensive Cancer Center']","[Gladstone Institutes, UCSF Helen Diller Family Comprehensive Cancer Center]","[Center for Bioengineering and Tissue Regeneration, University of California, Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research]"
75,"['Northwestern University', 'Robert H. Lurie Comprehensive Cancer Center']","[Northwestern University, Robert H. Lurie Comprehensive Cancer Center]",[]
76,"['Qilu Hospital', 'Shandong University', 'Central Hospital', 'Zaozhuang Coal Mining Group', 'Jinan integrative medicine hospital']","[Integrative Medicine Hospital of Nanchang, Qilu Hospital of Shandong University]",[Central Hospital of Zaozhuang Coal Mining Group]
77,"[""St. Jude Children's Research Hospital"", 'Cornell', 'University of Chicago', 'Howard Hughes Medical Institute']","[University of Chicago, St. Jude Children's Research Hospital, Weill Cornell Medicine, Howard Hughes Medical Institute, Memphis Zoo]","[Cellular Screening Center, Preclinical, ']"
78,['Baylor College of Medicine'],[Baylor College of Medicine],[]
79,['University of California'],[],[University of California]
80,NaN,[],[]
81,NaN,[],[]
82,"['Second Affiliated Hospital', 'Fujian Medical University', 'Nanjing Medical University']","[Second Affiliated Hospital of Fujian Medical University, Nanjing Medical University]",[]
83,"['Universidade de São Paulo', 'Universidade do Oeste Paulista UNOESTE', 'Center of Translational Research in Oncology (LIM24)', 'Instituto do Cancer do Estado de Sao Paulo (ICESP)']","[Universidade de São Paulo, Universidade do Oeste Paulista, Instituto do Câncer do Estado de São Paulo]","[Prudente, Center of Translational Research in Oncology (, )]"
84,"['Hepatic Surgery Center', 'Tongji Hospital', 'Huazhong University of Science and Technology', 'Shanxi Bethune Hospital', 'Shanxi Academy of Medical Sciences', 'Shanxi Medical University', 'Shanxi Tongji Hospital']","[Tongji Hospital, Huazhong University of Science and Technology, Bethune Second Hospital, Shanxi Academy of Medical Sciences, Shanxi Medical University]",[Hepatic Surgery Center]
85,"['Centre de Recherche des Cordeliers', 'INSERM', 'Sorbonne Université', 'Université Paris Cité', 'Institut universitaire de France', 'Institut Gustave Roussy', 'Centre de Recherche des Cordeliers', 'Klinikum Rechts der Isar', 'Technical University of Munich', 'Institute of Biophysics', 'Czech Academy of Sciences', 'CNRS', 'Institut Polytechnique de Paris', 'Université Paris-Saclay', 'Université Sorbonne Paris Nord', 'Institut du Cancer Paris CARPEM', 'Hôpital Européen Georges Pompidou']","[Czech Academy of Sciences, Université Sorbonne Paris Nord, Klinikum rechts der Isar, Technical University of Munich, Institut Gustave Roussy, Centre de Recherche des Cordeliers, INSERM, Sorbonne Université, Université Paris Cité, Institut Universitaire de France, Hôpital Européen Georges-Pompidou, CNRS, Université Paris-Saclay, École Polytechnique, Institut Polytechnique de Paris]","[Institute of Biophysics, Institut du Cancer Paris CARPEM]"
86,"['Norwegian University of Science and Technology', 'St. Olavs Hospital', 'Center for Oral Health Services and Research Mid-Norway (TkMidt)', 'Clinic of Medicine', 'K.G. Jebsen Centre for Genetic Epidemiology']",[Norwegian University of Science and Technology],"[K. G. Jebsen Centre for Genetic Epidemiology, Center for Oral Health Services and Research Mid - Norway ( TkMidt ), St. Olavs Hospital, Trondheim University Hospital]"
87,['Mayo Clinic'],[Mayo Clinic],[]
88,"['University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca', 'Biotechnology Research Center', 'Life Sciences Institute King Michael I of Romania', 'Babeș-Bolyai University']","[University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca, Universitatea Babeș-Bolyai, Banat University of Agricultural Sciences and Veterinary Medicine, Biotechnology Research Center]","[Life Sciences Institute "" King Michael I of Romania ""]"
89,"['Graduate Institute of Biomedical Science', 'China Medical University', 'Taichung Tzu Chi Hospital', 'Buddhist Tzu Chi Medical Foundation', 'China Medical University Hospital', 'Asia University', 'Institute of New Drug Development']","[Asia University, China Medical University, China Medical University Hospital, Taichung Hospital, Buddhist Tzu Chi Medical Foundation, Tzu Chi University]","[Graduate Institute of Biomedical Science, Institute of New Drug Development]"
90,"['Chongqing University Three Gorges Hospital', 'Center for Medicine Research and Translation', ""Chengdu Fifth People's Hospital""]","[Chongqing Three Gorges University, Chengdu Fifth People's Hospital]",[Center for Medicine Research and Translation]
91,"['Boston University', 'Shaukat Khanum Memorial Cancer Hospital and Research Centre']","[Shaukat Khanum Memorial Cancer Hospital and Research Center, Boston University]",[]
92,NaN,[],[]
93,NaN,[],[]
94,['Georgetown University Medical Center'],[Georgetown University Medical Center],[]
95,['University of South Florida'],[University of South Florida],[]
96,['Johns Hopkins Oncology Center'],[],[Johns Hopkins Oncology Center]
97,"['Albert Einstein Cancer Center', 'Montefiore Medical Center']","[Albert Einstein Cancer Center at Montefiore, Montefiore Medical Center]",[]
98,['General Hospital Manuel Gea Gonzalez'],[Hospital General Dr. Manuel Gea Gonzalez],[]
99,['University Hospital Leiden'],[Leiden University],[]
100,['Paul Scherrer Institute'],[Paul Scherrer Institute],[]
101,['Wayne State University'],[Wayne State University],[]
102,[],[],[]

In [162]:
df_2.at[51,"NER_BERT"]

"[{'entity_group': 'INS', 'score': np.float32(0.9999027), 'word': 'Istanbul University', 'start': 0, 'end': 19}, {'entity_group': 'INS', 'score': np.float32(0.99982023), 'word': 'Institute of Experimental Medicine', 'start': 54, 'end': 88}, {'entity_group': 'SUBC', 'score': np.float32(0.9965587), 'word': 'Istanbul', 'start': 89, 'end': 97}, {'entity_group': 'COU', 'score': np.float32(0.9951475), 'word': 'Turkey', 'start': 98, 'end': 104}, {'entity_group': 'INS', 'score': np.float32(0.9999207), 'word': 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital', 'start': 107, 'end': 181}, {'entity_group': 'SUBC', 'score': np.float32(0.99876803), 'word': 'Istanbul', 'start': 222, 'end': 230}, {'entity_group': 'COU', 'score': np.float32(0.9979699), 'word': 'Turkey', 'start': 231, 'end': 237}, {'entity_group': 'INS', 'score': np.float32(0.99949986), 'word': 'Istanbul University', 'start': 240, 'end': 259}, {'entity_group': 'INS', 'score': np.float32(0.99983823), 'word': 'Institute of Experimental Medicine', 'start': 294, 'end': 328}, {'entity_group': 'SUBC', 'score': np.float32(0.99928814), 'word': 'Istanbul', 'start': 329, 'end': 337}, {'entity_group': 'COU', 'score': np.float32(0.94255334), 'word': 'Turkey', 'start': 338, 'end': 344}, {'entity_group': 'EMA', 'score': np.float32(0.99992406), 'word': 'ecoskunpinar @ gmail. com', 'start': 345, 'end': 367}, {'entity_group': 'INS', 'score': np.float32(0.9998201), 'word': 'Yeditepe University', 'start': 370, 'end': 389}, {'entity_group': 'SUBC', 'score': np.float32(0.9837863), 'word': 'Istanbul', 'start': 441, 'end': 449}, {'entity_group': 'COU', 'score': np.float32(0.87121433), 'word': 'Turkey', 'start': 450, 'end': 456}, {'entity_group': 'INS', 'score': np.float32(0.9996519), 'word': 'Istanbul University', 'start': 459, 'end': 478}, {'entity_group': 'SUBC', 'score': np.float32(0.9989672), 'word': 'Istanbul', 'start': 538, 'end': 546}, {'entity_group': 'COU', 'score': np.float32(0.9993606), 'word': 'Turkey', 'start': 547, 'end': 553}]"

In [147]:
df.at[33,"Authors"]

"[{'Name': 'Huiling Guo', 'Affiliation': ['Evidence Based Medicine Center of Lanzhou University, Lanzhou 730000, China; The Second Clinical Medical college of Lanzhou University, Lanzhou 730000, China.']}, {'Name': 'Rongfang Zhang', 'Affiliation': []}, {'Name': 'Qimei Yang', 'Affiliation': []}, {'Name': 'Lingjuan Zhang', 'Affiliation': []}, {'Name': 'Kehu Yang', 'Affiliation': []}, {'Name': 'Jinhui Tian', 'Affiliation': []}]"

In [161]:
counter_hits(df_2)

(272, 208)

In [119]:
df["Institutions_man"] == df_2["Institutions_man"]

0      False
1      False
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20     False
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
30     False
31      True
32      True
33      True
34     False
35      True
36      True
37      True
38      True
39     False
40      True
41      True
42      True
43      True
44      True
45      True
46      True
47      True
48     False
49     False
50      True
51      True
52     False
53     False
54      True
55      True
56     False
57     False
58      True
59      True
60      True
61      True
62      True
63      True
64      True
65      True
66      True
67      True
68      True
69      True
70      True
71      True
72      True
73      True
74      True
75      True
76      True
77      True
78      True
79      True
80     False
81     False
82      True
83      True
84      True
85      True
86      True
87      True
88      True
89      True
90      True
91      True
92     False
93     False
94      True
95      True
96      True
97      True
98      True
99      True
100     True
101     True
102     True
Name: Institutions_man, dtype: bool

In [120]:
df["Institutions_db_name"] == df_2["Institutions_db_name"]

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22     False
23      True
24      True
25      True
26      True
27      True
28      True
29      True
30      True
31      True
32      True
33      True
34      True
35      True
36      True
37      True
38      True
39      True
40      True
41      True
42      True
43      True
44      True
45      True
46      True
47      True
48      True
49      True
50      True
51      True
52      True
53      True
54      True
55      True
56      True
57      True
58      True
59      True
60      True
61      True
62      True
63      True
64      True
65      True
66      True
67      True
68      True
69      True
70      True
71      True
72      True
73      True
74      True
75      True
76      True
77      True
78      True
79      True
80      True
81      True
82      True
83      True
84      True
85      True
86      True
87      True
88      True
89     False
90      True
91      True
92      True
93      True
94      True
95      True
96      True
97      True
98      True
99      True
100     True
101     True
102     True
Name: Institutions_db_name, dtype: bool

# CURRENT SOTA: RESOLVE VIA RELATIONSHIPS, ADD TO CANDIDATES TO CONSIDER (FUZZY) ONLY THOSE MATCHING COU OR SUBCOU

In [301]:
from collections import OrderedDict
import psycopg2
import pandas as pd
import ast
import re
from tqdm import tqdm

# -----------------------
# CACHE (LRU size = 1000)
# -----------------------
CACHE_SIZE = 1000
institution_cache = OrderedDict()

# -----------------------
# PRE-CREATE RESULT COLUMNS
# -----------------------
df_2['Institutions_db_id'] = [[] for _ in range(len(df_2))]
df_2['Institutions_db_name'] = [[] for _ in range(len(df_2))]
df_2['Institutions_db_country'] = [[] for _ in range(len(df_2))]
df_2['Unmatched_INS'] = [[] for _ in range(len(df_2))]

# -----------------------
# DB CONNECTION
# -----------------------
connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)

cursor = connection.cursor()
cursor.execute("SET pg_trgm.similarity_threshold = 0.6")

# -----------------------
# LOAD DATABASE TABLES INTO MEMORY
# -----------------------
print("Loading institution_names...")
cursor.execute("SELECT institution_id, name FROM institution_names")
rows = cursor.fetchall()
name_index = {}
for inst_id, name in rows:
    name_index.setdefault(name, []).append((inst_id, name))

print("Loading institution_locations...")
cursor.execute("""
    SELECT institution_id, city_name, country_name, subdivision_name
    FROM institution_locations
""")
rows = cursor.fetchall()
location_index = {r[0]: (r[1], r[2], r[3]) for r in rows}

print("Loading institution_relationships...")
cursor.execute("""
    SELECT child_institution_id, parent_institution_id
    FROM institution_relationships
""")
rows = cursor.fetchall()
relationship_index = set()
for child_id, parent_id in rows:
    relationship_index.add((child_id, parent_id))
    relationship_index.add((parent_id, child_id))

print("Indices loaded.")

# -----------------------
# MAIN LOOP
# -----------------------
for row in tqdm(range(len(df_2))):

    if pd.isna(df_2.at[row, "NER_BERT"]):
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df_2.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = {ner.get('word') for ner in ner_results if ner.get('entity_group') == 'SUBC'}
    cou_ner_results = {ner.get('word') for ner in ner_results if ner.get('entity_group') == 'COU'}

    # -----------------------
    # EXTRACT UNIQUE INS
    # -----------------------
    seen_queries = set()
    ins_queries = []

    for ner in ner_results:
        if ner.get('entity_group') != 'INS':
            continue
        query = ner.get('word')
        if query == "Harvard":
            query = "Harvard University"
        query = query.replace("’", "'").replace(" ' s", "'s").strip()
        if query not in seen_queries:
            seen_queries.add(query)
            ins_queries.append(query)

    found_institutions = []
    unmatched_queries = []

    # -----------------------
    # PROCESS EACH QUERY
    # -----------------------
    for query in ins_queries:

        matched = False  # Track whether this query was successfully resolved
        resolved = []

        # -----------------------
        # CACHE LOOKUP
        # -----------------------
        if query in institution_cache:
            ids, names, countries = institution_cache[query]
            for inst in zip(ids, names, countries):
                found_institutions.append(inst)
            institution_cache.move_to_end(query)
            matched = True
            continue

        # -----------------------
        # EXACT MATCH
        # -----------------------
        records_exact = name_index.get(query, [])
        candidates = {r[0]: r[1] for r in records_exact}

        # =========================
        # EXACT MATCH: ONE
        # =========================
        if len(candidates) == 1:
            inst_id = next(iter(candidates))
            location = location_index.get(inst_id)
            if location:
                city, country, subdivision = location
                if (cou_ner_results or subc_ner_results):
                    if country in cou_ner_results or city in subc_ner_results or subdivision in subc_ner_results:
                        resolved.append((inst_id, candidates[inst_id], country))
                        matched = True
                else:
                    resolved.append((inst_id, candidates[inst_id], country))
                    matched = True

        # =========================
        # EXACT MATCH: MULTIPLE
        # =========================
        elif len(candidates) > 1:
            candidate_ids = list(candidates.keys())
            location_map = {inst_id: location_index.get(inst_id) for inst_id in candidate_ids if inst_id in location_index}

            # Step 1: Filter candidates by location match
            location_matches = []
            for inst_id, inst_name in candidates.items():
                loc = location_map.get(inst_id)
                if not loc:
                    continue
                city, country, subdivision = loc
                if country in cou_ner_results or city in subc_ner_results or subdivision in subc_ner_results:
                    location_matches.append((inst_id, inst_name, country))

            # Step 2: Resolve if exactly one match
            if len(location_matches) == 1:
                resolved.append(location_matches[0])
                matched = True

            # Step 3: Multiple matches: use relationship
            elif len(location_matches) > 1:
                found = False
                for i, (inst_id_i, name_i, country_i) in enumerate(location_matches):
                    for j, (inst_id_j, name_j, country_j) in enumerate(location_matches):
                        if i == j:
                            continue
                        if (inst_id_i, inst_id_j) in relationship_index:
                            resolved.append((inst_id_i, name_i, country_i))
                            matched = True
                            found = True
                            break
                    if found:
                        break

        # =========================
        # FUZZY SEARCH
        # =========================
        elif len(candidates) == 0:
            cursor.execute(
                """
                SELECT institution_id, name, similarity(name, %s) AS sim
                FROM institution_names
                WHERE name %% %s
                AND similarity(name, %s) >= 0.6
                ORDER BY sim DESC
                LIMIT 10
                """,
                (query, query, query)
            )
            records_fuzzy = cursor.fetchall()
            candidates_fuzzy = {r[0]: r[1] for r in records_fuzzy}
            candidate_ids = list(candidates_fuzzy.keys())
            location_map = {inst_id: location_index[inst_id] for inst_id in candidate_ids if inst_id in location_index}

            matching_candidates = []
            for inst_id, inst_name in candidates_fuzzy.items():
                if inst_id not in location_map:
                    continue
                city, country, subdivision = location_map[inst_id]
                if country in cou_ner_results or city in subc_ner_results or subdivision in subc_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

            # Accept if one location match
            if len(matching_candidates) == 1:
                resolved.append(matching_candidates[0])
                matched = True

            # FALLBACK
            elif len(candidates_fuzzy) > 0:
                matching_ids = [inst_id for inst_id, _, _ in matching_candidates]
                deduped = {}
                for inst_id, name, sim in records_fuzzy:
                    if inst_id not in matching_ids:
                        continue
                    if inst_id not in deduped or sim > deduped[inst_id][1]:
                        deduped[inst_id] = (name, sim)

                if len(deduped) > 0:
                    deduped_sorted = sorted(deduped.items(), key=lambda x: x[1][1], reverse=True)
                    top_id, (top_name, top_sim) = deduped_sorted[0]
                    second_sim = deduped_sorted[1][1][1] if len(deduped_sorted) > 1 else None
                    sim_gap = top_sim - second_sim if second_sim is not None else 0
                    location = location_index.get(top_id)
                    if location:
                        city, country, subdivision = location
                        location_match = country in cou_ner_results or city in subc_ner_results or subdivision in subc_ner_results

                        # STANDARD ACCEPTANCE
                        if top_sim >= 0.6 and (location_match or sim_gap >= 0.2):
                            resolved.append((top_id, top_name, country))
                            matched = True

                        # ACCEPT BASED ON SIM DISTANCE
                        elif second_sim is not None and sim_gap < 0.2 and location_match:
                            second_id = deduped_sorted[1][0]
                            if (top_id, second_id) in relationship_index:
                                resolved.append((top_id, top_name, country))
                                matched = True

                        # ALL RELATED -> PICK PARENT
                        elif len(deduped_sorted) > 1:
                            all_ids = [inst_id for inst_id, _ in deduped_sorted]
                            all_related = all(
                                (all_ids[i], all_ids[j]) in relationship_index
                                for i in range(len(all_ids))
                                for j in range(i + 1, len(all_ids))
                            )
                            if all_related:
                                parent_id = None
                                for cid in all_ids:
                                    for pid in all_ids:
                                        if (cid, pid) in relationship_index and cid != pid:
                                            parent_id = pid
                                            break
                                    if parent_id:
                                        break
                                if parent_id:
                                    parent_name = name_index.get(parent_id, [(None,)])[0][0]
                                    parent_loc = location_index.get(parent_id)
                                    parent_country = parent_loc[1] if parent_loc else None
                                    resolved.append((parent_id, parent_name, parent_country))
                                    matched = True

        # -----------------------
        # CACHE OR UNMATCHED
        # -----------------------
        if resolved:
            ids, names, countries = zip(*resolved)
            institution_cache[query] = (list(ids), list(names), list(countries))
            if len(institution_cache) > CACHE_SIZE:
                institution_cache.popitem(last=False)
            for inst in resolved:
                found_institutions.append(inst)

        if not matched:
            unmatched_queries.append(query)

    # -----------------------
    # WRITE RESULTS
    # -----------------------
    if found_institutions:
        unique_dict = {}
        for inst_id, inst_name, country in found_institutions:
            if inst_id not in unique_dict:
                unique_dict[inst_id] = (inst_name, country)
        ids = list(unique_dict.keys())
        names = [v[0] for v in unique_dict.values()]
        countries = [v[1] for v in unique_dict.values()]
        df_2.at[row, 'Institutions_db_id'] = ids
        df_2.at[row, 'Institutions_db_name'] = names
        df_2.at[row, 'Institutions_db_country'] = countries

    if unmatched_queries:
        df_2.at[row, 'Unmatched_INS'] = unmatched_queries

# -----------------------
# CLOSE CONNECTION
# -----------------------
cursor.close()
connection.close()

Loading institution_names...
Loading institution_locations...
Loading institution_relationships...
Indices loaded.

100%|████████████████████████████████████████████████████████████████████████████████| 103/103 [00:06<00:00, 15.27it/s]

In [232]:
cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[61, "NER_BERT"])


ner_results = ast.literal_eval(cleaned)

subc_ner_results = {
    ner.get('word')
    for ner in ner_results
    if ner.get('entity_group') == 'SUBC'
}

cou_ner_results = {
    ner.get('word')
    for ner in ner_results
    if ner.get('entity_group') == 'COU'
}

query = "CTRC"

connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)

cursor = connection.cursor()

cursor.execute(
    """
    SELECT institution_id, name, similarity(name, %s) AS sim
    FROM institution_names
    WHERE name %% %s
    AND similarity(name, %s) >= 0.6
    ORDER BY sim DESC
    LIMIT 10
    """,
    (query, query, query)
)

records_fuzzy = cursor.fetchall()


cursor.close()
connection.close()

candidates_fuzzy = {r[0]: r[1] for r in records_fuzzy}

candidate_ids = list(candidates_fuzzy.keys())

location_map = {
    inst_id: location_index[inst_id]
    for inst_id in candidate_ids
    if inst_id in location_index
}

matching_candidates = []

matching_ids = [inst_id for inst_id, _, _ in matching_candidates]

for inst_id, inst_name in candidates_fuzzy.items():

    if inst_id not in location_map:
        continue

    city, country, subdivision = location_map[inst_id]

    if country in cou_ner_results:
        matching_candidates.append((inst_id, inst_name, country))

    elif city in subc_ner_results or subdivision in subc_ner_results:
        matching_candidates.append((inst_id, inst_name, country))

matching_candidates

#deduped = {}
#            
#for inst_id, name, sim in records_fuzzy:
#
#    # Only include in deduped if the candidate passed location matching
#    if inst_id not in matching_ids:
#        continue
#                        
#    if inst_id not in deduped or sim > deduped[inst_id][1]:
#        deduped[inst_id] = (name, sim)
#            
#deduped_sorted = sorted(
#    deduped.items(),
#    key=lambda x: x[1][1],
#    reverse=True
#)
#            
#top_id, (top_name, top_sim) = deduped_sorted[0]
#            
#second_sim = deduped_sorted[1][1][1] if len(deduped_sorted) > 1 else None
#sim_gap = top_sim - second_sim if second_sim is not None else 0
#            
#location = location_index.get(top_id)
#            
#if location:
#    city, country, subdivision = location
#            
#    location_match = (
#        country in cou_ner_results
#        or city in subc_ner_results
#        or subdivision in subc_ner_results
#    )
#
#if top_sim >= 0.6 and (location_match or sim_gap >= 0.2):
#    resolved.append((top_id, top_name, country))
#
#location_match

[]

In [300]:
df_2[["Institutions_man", "Institutions_db_name"]]

,Institutions_man,Institutions_db_name
0,NaN,[]
1,NaN,[]
2,"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of British Columbia, i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto, Institute of Molecular Pathology and Immunology of the University of Porto, University of Porto]"
3,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[Cincinnati Children's Hospital Medical Center, University of Cincinnati, Children's Healthcare of Atlanta, Emory University, Children's Hospital of Los Angeles]"
4,"['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[University of Pennsylvania, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, University of Memphis, University of Chicago, University of Buffalo, Rutgers Institute for Nicotine & Tobacco Studies]"
5,"['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[CONAHCYT, Universidad Nacional Autónoma de México]"
6,"['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[Université de Toulouse, Inserm, CNRS, Centre de Recherche en Cancérologie de Toulouse, University Cancer Institute Toulouse Oncopole]"
7,['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University]
8,"['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw]
9,"['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']","[Chang Gung University, Linkou Chang Gung Memorial Hospital, Chang Gung Memorial Hospital]"
10,"['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']","[Ruhr University Bochum, BG University Hospital Bergmannsheil Bochum, Ludwig-Maximilians-Universität in Munich, Medical Genetics Center]"
11,"['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[IRCCS Ospedale San Raffaele, Università Vita-Salute San Raffaele]"
12,"['University of Adelaide', 'Queen Elizabeth Hospital']","[University of Adelaide, Queen Elizabeth Hospital]"
13,['University of Zimbabwe'],[University of Zimbabwe]
14,['University of Tokyo Hospital'],[University of Tokyo Hospital]
15,['University Hospital Centre of Grenoble'],[Grenoble University Hospital Centre]
16,['Harvard'],[]
17,['University of Washington'],[University of Washington]
18,['University of Würzburg'],[University of Würzburg]
19,"['Mannheim Medical Center', 'University of Heidelberg']",[Heidelberg University]
20,NaN,[]
21,['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology]
22,['Duke University Medical Center'],[Duke University Medical Center]
23,"['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]","[Hewitt Centre for Reproductive Medicine, Liverpool Women's Hospital]"
24,['University of Rochester'],[University of Rochester]
25,['Stavanger University Hospital'],[Stavanger University Hospital]
26,['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[]
27,['Akademii Medycznej w Gdańsku'],[]
28,['Vienna Medical University'],[Medical University of Vienna]
29,"['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]"
30,NaN,[]
31,"['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University]
32,"['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital]
33,"['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University]
34,NaN,[]
35,['Royal North Brisbane Hospital'],[Royal North Brisbane Hospital]
36,['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[Azienda Ospedaliero Universitaria Maggiore della Carita]
37,['Universitá degli Studi di Palermo'],[Università degli Studi di Palermo]
38,['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf]
39,NaN,[]
40,"['Institute of Medical Microbiology', 'Charles University']",[Charles University]
41,['Queensland Institute of Medical Research'],[Queensland Institute of Medical Research]
42,['University of Porto'],[University of Porto]
43,"['University of Liverpool', 'Linda McCartney Centre', 'Royal Liverpool University Hospital']","[University of Liverpool, Royal Liverpool University Hospital]"
44,"['University of Leipzig Medical Center', 'University Medical Center Hamburg-Eppendorf', 'Institute for Medical Biostatistics, Epidemiology and Informatics', 'University of Mainz Medical Center', 'University Hospital of Essen', ""Children's Hospital""]","[University Medical Center Hamburg-Eppendorf, Kantonsspital St. Gallen, University of Würzburg, University Medical Center Göttingen, Essen University Hospital, Institute for Medical Informatics and Biostatistics, University Hospital Bonn, Düsseldorf University Hospital]"
45,"['Northwestern Memorial Hospital', 'Robert H. Lurie Comprehensive Cancer Center', 'Northwestern University']","[Northwestern Memorial Hospital, Robert H. Lurie Comprehensive Cancer Center, Northwestern University]"
46,"['First Affiliated Hospital', 'Nanchang University']",[First Affiliated Hospital of Nanchang University]
47,"['Suzhou Municipal Hospital', 'Affiliated Suzhou Hospital', 'Nanjing Medical University', ""Shaoxing People's Hospital"", 'Shaoxing Hospital', 'Zhejiang University']","[Suzhou Municipal Hospital, Second Affiliated Hospital of Nanjing Medical University, Shaoxing People's Hospital, Children's Hospital of Zhejiang University]"
48,NaN,[]
49,NaN,[]
50,"['Institute of Biomedical and Genetic Engineering (IBGE)', 'International Islamic University']","[Institute of Biomedical and Genetic Engineering, International Islamic University, Islamabad]"
51,"['Istanbul University', 'Institute of Experimental Medicine', 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital']","[Istanbul University, Yeditepe University]"
52,NaN,[]
53,NaN,[]
54,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', 'Cancer and Blood Disease Institute', ""Boston Children's Hospital"", 'Harvard']","[University of Cincinnati, Cincinnati Children's Hospital Medical Center, Boston Children's Museum, Harvard University]"
55,"['Erasmus MC', 'Utrecht University', 'Erasmus MC Cancer Institute']","[Utrecht University, Erasmus MC Cancer Institute, Erasmus MC]"
56,NaN,[]
57,NaN,[]
58,"['Queen Elizabeth Hospital', 'Royal Victoria Infirmary', 'Medical Research Council Clinical Trials Unit', 'University College London']","[Medical Research Council, University College London, Queen Elizabeth Hospital, Royal Victoria Infirmary]"
59,"['Centro Nacional de Investigaciones Oncológicas (CNIO)', 'Center for Molecular Biology of Heidelberg University (ZMBH)', 'Centro de Investigación en Red de Enfermedades Neurodegenerativas (CIBERNED)', 'University of Cantabria', 'IDIVAL', 'Center for Biomedicine and Medical Technology Mannheim (CBTM)', 'Heidelberg University', 'German Cancer Research Center (DKFZ)', 'Hope Center for Neurological Diseases', 'Washington University']","[Heidelberg University, Center for Molecular Biology Severo Ochoa, Centro de Investigación Biomédica en Red, Enfermedades Neurodegenerativas, University of Cantabria, IDIVAL, Centro Nacional de Investigaciones Oncológicas, German Cancer Research Center, DKFZ-ZMBH Alliance]"
60,"[""King's College London"", 'Comprehensive Biomedical Research Centre', ""Guy's and St Thomas NHS Foundation Trust"", 'Uppsala University', 'Medical Products Agency', 'Karolinska Insituet']","[Karolinska Institutet, UCL Biomedical Research Centre, Guy's and St Thomas' NHS Foundation Trust, King's College London, Uppsala University, Medical Products Agency]"
61,"['August Pi i Sunyer Biomedical Research Institute', 'Hospital Clínic', 'Sant Joan de Deu Childrens Hospital', 'University of Barcelona', 'Nihon University School of Medicine', 'University of Lausanne', 'University of Pennsylvania', 'Catalan Institution for Research and Advanced Studies']","[Sant Joan de Déu-Barcelona Children’s Hospital, University of Barcelona, University of Lausanne, University of Pennsylvania, Catalan Institution for Research and Advanced Studies]"
62,['Delhi State Cancer Institute'],[Delhi State Cancer Institute]
63,"['Kushiro Rosai Hospital', 'Kanagawa Cancer Center', 'Keio University', 'Sapporo Medical University', 'Hijirigaoka Hospital', 'National Hospital Organization', 'Osaka National Hospital', 'Hiroshima University', 'University of Tokyo', 'Tokai Central Hospital', 'Translational Research and Clinical Trial Center', 'Hokkaido University Hospital', 'Japanese Foundation for Multidisciplinary Treatment of Cancer']","[Keio University, Japanese Foundation for Multidisciplinary Treatment of Cancer, Kanagawa Cancer Center, Kushiro Rosai Hospital, The University of Tokyo, National Hospital Organization, Osaka National Hospital, Sapporo Medical University, Hokkaido University Hospital, Tokai Central Hospital, Hiroshima University]"
64,['Life Raft Group'],[]
65,['Washington State University'],[Washington State University]
66,"['Addis Ababa University', 'Karolinska Institutet', 'Karolinska University Hospital', 'Center for Innovative Drug Development and Therapeutic Trials', 'Armauer Hansen Research Institute']","[Karolinska Institutet, Armauer Hansen Research Institute, Addis Ababa University, Karolinska University Hospital]"
67,[nan],[]
68,"['Tulane University', 'Louisiana State University Health Sciences Center']","[Tulane University, Louisiana State University Health Sciences Center New Orleans]"
69,"['Hebei Medical University', 'Bethune International Peace Hospital', 'Hebei University of Chinese Medicine']","[Bethune International Peace Hospital, Hebei Medical University, Hebei University of Chinese Medicine]"
70,"[""Henan Provincial People's Hospital"", ""Zhengzhou University People's Hospital"", ""Henan University People's Hospital"", 'Institute of Hematology']","[Shanghai Institute of Hematology, Henan Provincial People's Hospital, Zhengzhou People's Hospital, Peking University People's Hospital]"
71,"['Huazhong University of Science and Technology Union Shenzhen Hospital (Nanshan Hospital)', ""Shenzhen Second People's Hospital"", 'First Affiliated Hospital', 'Shenzhen University']","[Shenzhen Second People's Hospital, Huazhong University of Science and Technology]"
72,['Medical University of Innsbruck'],[Innsbruck Medical University]
73,"['Stanton L. Young Biomedical Research Center', 'University of Oklahoma Health Science Center']",[University of Oklahoma Health Sciences Center]
74,"['Center for Bioengineering and Tissue Regeneration', 'University of California', 'Gladstone Institutes', 'Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research', 'Helen Diller Family Comprehensive Cancer Center']","[Gladstone Institutes, UCSF Helen Diller Family Comprehensive Cancer Center]"
75,"['Northwestern University', 'Robert H. Lurie Comprehensive Cancer Center']","[Northwestern University, Robert H. Lurie Comprehensive Cancer Center]"
76,"['Qilu Hospital', 'Shandong University', 'Central Hospital', 'Zaozhuang Coal Mining Group', 'Jinan integrative medicine hospital']","[Integrative Medicine Hospital of Nanchang, Qilu Hospital of Shandong University]"
77,"[""St. Jude Children's Research Hospital"", 'Cornell', 'University of Chicago', 'Howard Hughes Medical Institute']","[University of Chicago, St. Jude Children's Research Hospital, Weill Cornell Medicine, Memphis Zoo]"
78,['Baylor College of Medicine'],[Baylor College of Medicine]
79,['University of California'],[]
80,NaN,[]
81,NaN,[]
82,"['Second Affiliated Hospital', 'Fujian Medical University', 'Nanjing Medical University']","[Second Affiliated Hospital of Fujian Medical University, Nanjing Medical University]"
83,"['Universidade de São Paulo', 'Universidade do Oeste Paulista UNOESTE', 'Center of Translational Research in Oncology (LIM24)', 'Instituto do Cancer do Estado de Sao Paulo (ICESP)']","[Universidade de São Paulo, Universidade do Oeste Paulista, Instituto do Câncer do Estado de São Paulo]"
84,"['Hepatic Surgery Center', 'Tongji Hospital', 'Huazhong University of Science and Technology', 'Shanxi Bethune Hospital', 'Shanxi Academy of Medical Sciences', 'Shanxi Medical University', 'Shanxi Tongji Hospital']","[Tongji Hospital, Huazhong University of Science and Technology, Bethune Second Hospital, Shanxi Academy of Medical Sciences, Shanxi Medical University]"
85,"['Centre de Recherche des Cordeliers', 'INSERM', 'Sorbonne Université', 'Université Paris Cité', 'Institut universitaire de France', 'Institut Gustave Roussy', 'Centre de Recherche des Cordeliers', 'Klinikum Rechts der Isar', 'Technical University of Munich', 'Institute of Biophysics', 'Czech Academy of Sciences', 'CNRS', 'Institut Polytechnique de Paris', 'Université Paris-Saclay', 'Université Sorbonne Paris Nord', 'Institut du Cancer Paris CARPEM', 'Hôpital Européen Georges Pompidou']","[Université Sorbonne Paris Nord, Klinikum rechts der Isar, Technical University of Munich, Institut Gustave Roussy, Centre de Recherche des Cordeliers, INSERM, Sorbonne Université, Université Paris Cité, Institut Universitaire de France, Hôpital Européen Georges-Pompidou, CNRS, Université Paris-Saclay, École Polytechnique, Institut Polytechnique de Paris]"
86,"['Norwegian University of Science and Technology', 'St. Olavs Hospital', 'Center for Oral Health Services and Research Mid-Norway (TkMidt)', 'Clinic of Medicine', 'K.G. Jebsen Centre for Genetic Epidemiology']",[Norwegian University of Science and Technology]
87,['Mayo Clinic'],[Mayo Clinic]
88,"['University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca', 'Biotechnology Research Center', 'Life Sciences Institute King Michael I of Romania', 'Babeș-Bolyai University']","[University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca, Universitatea Babeș-Bolyai, Banat University of Agricultural Sciences and Veterinary Medicine]"
89,"['Graduate Institute of Biomedical Science', 'China Medical University', 'Taichung Tzu Chi Hospital', 'Buddhist Tzu Chi Medical Foundation', 'China Medical University Hospital', 'Asia University', 'Institute of New Drug Development']","[Asia University, China Medical University, China Medical University Hospital, Taichung Hospital, Tzu Chi University]"
90,"['Chongqing University Three Gorges Hospital', 'Center for Medicine Research and Translation', ""Chengdu Fifth People's Hospital""]","[Chongqing Three Gorges University, Chengdu Fifth People's Hospital]"
91,"['Boston University', 'Shaukat Khanum Memorial Cancer Hospital and Research Centre']","[Shaukat Khanum Memorial Cancer Hospital and Research Center, Boston University]"
92,NaN,[]
93,NaN,[]
94,['Georgetown University Medical Center'],[Georgetown University Medical Center]
95,['University of South Florida'],[University of South Florida]
96,['Johns Hopkins Oncology Center'],[]
97,"['Albert Einstein Cancer Center', 'Montefiore Medical Center']","[Albert Einstein Cancer Center at Montefiore, Montefiore Medical Center]"
98,['General Hospital Manuel Gea Gonzalez'],[Hospital General Dr. Manuel Gea Gonzalez]
99,['University Hospital Leiden'],[Leiden University]
100,['Paul Scherrer Institute'],[Paul Scherrer Institute]
101,['Wayne State University'],[Wayne State University]
102,[],[]

In [306]:
df_2[["Countries_man", "Institutions_db_country"]]

,Countries_man,Institutions_db_country
0,NaN,[]
1,NaN,[]
2,"['Portugal', 'Portugal', 'Canada', 'Canada', 'Portugal']","[Canada, Portugal, Portugal, Portugal]"
3,"['United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'China', 'China']","[United States, United States, United States, United States, United States]"
4,"['United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States']","[United States, United States, United States, United States, United States, United States, United States]"
5,"['Mexico', 'Mexico', 'Mexico', 'Mexico', 'Mexico', 'Mexico', 'United States']","[Mexico, Mexico]"
6,"['France', 'France', 'France', 'France', 'France', 'France', 'France']","[France, France, France, France, France]"
7,['China'],[China]
8,"['Poland', 'Poland']",[Poland]
9,"['Taiwan', 'Taiwan']","[Taiwan, Taiwan, Taiwan]"
10,"['Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Switzerland', 'Germany', 'Germany', 'Germany']","[Germany, Germany, Germany, Germany]"
11,"['Italy', 'Italy', 'Italy']","[Italy, Italy]"
12,"['Autralia', 'Autralia']","[Australia, Australia]"
13,['Zimbabwe'],[Zimbabwe]
14,['Japan'],[Japan]
15,['France'],[France]
16,['United States'],[]
17,['United States'],[United States]
18,['Germany'],[Germany]
19,"['Germany', 'Germany']",[Germany]
20,NaN,[]
21,['Norway'],[Norway]
22,['United States'],[United States]
23,"['United Kingdom', 'United Kingdom']","[United Kingdom, United Kingdom]"
24,['United States'],[United States]
25,['Norway'],[Norway]
26,['Poland'],[]
27,['Poland'],[]
28,['Austria'],[Austria]
29,"['China', 'China']","[China, China]"
30,NaN,[]
31,"['United States', 'United States']",[United States]
32,"['China', 'China']",[China]
33,"['China', 'China']",[China]
34,['New Zealand'],[]
35,['Australia'],[Australia]
36,['Italy'],[Italy]
37,['Italy'],[Italy]
38,['Germany'],[Germany]
39,NaN,[]
40,"['Czechia', 'Czechia']",[Czechia]
41,['Australia'],[Australia]
42,['Portugal'],[Portugal]
43,"['United Kingdom', 'United Kingdom', 'United Kingdom']","[United Kingdom, United Kingdom]"
44,"['Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany']","[Germany, Switzerland, Germany, Germany, Germany, Switzerland, Germany, Germany]"
45,"['United States', 'United States', 'United States']","[United States, United States, United States]"
46,"['China', 'China']",[China]
47,"['China', 'China', 'China', 'China', 'China', 'China']","[China, China, China, China]"
48,NaN,[]
49,NaN,[]
50,"['Pakistan', 'Pakistan']","[Pakistan, Pakistan]"
51,"['Türkiye', 'Türkiye', 'Türkiye']","[Türkiye, Türkiye]"
52,NaN,[]
53,NaN,[]
54,"['United States', 'United States', 'United States', 'United States', 'United States']","[United States, United States, United States, United States]"
55,"['The Netherlands', 'The Netherlands', 'The Netherlands']","[The Netherlands, The Netherlands, The Netherlands]"
56,NaN,[]
57,NaN,[]
58,"['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']","[United Kingdom, United Kingdom, Australia, United Kingdom]"
59,"['Spain', 'Germany', 'Spain', 'Spain', 'Spain', 'Germany', 'Germany', 'Germany', 'United States', 'United States']","[Germany, Spain, Spain, Spain, Spain, Spain, Germany, Germany]"
60,"['United Kingdom', 'United Kingdom', 'United Kingdom', 'Sweden', 'Sweden', 'Sweden']","[Sweden, United Kingdom, United Kingdom, United Kingdom, Sweden, Sweden]"
61,"['Spain', 'Spain', 'Spain', 'Spain', 'Japan', 'Switzerland', 'United States', 'Spain']","[Spain, Spain, Switzerland, United States, Spain]"
62,['India'],[India]
63,"['Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan']","[Japan, Japan, Japan, Japan, Japan, Japan, Japan, Japan, Japan, Japan, Japan]"
64,['United States'],[]
65,['United States'],[United States]
66,"['Ethiopia', 'Sweden', 'Sweden', 'Ethiopia', 'Ethiopia']","[Sweden, Ethiopia, Ethiopia, Sweden]"
67,['Italy'],[]
68,"['United States', 'United States']","[United States, United States]"
69,"['China', 'China', 'China']","[China, China, China]"
70,"['China', 'China', 'China', 'China']","[China, China, China, China]"
71,"['China', 'China', 'China', 'China']","[China, China]"
72,['Austria'],[Austria]
73,"['United States', 'United States']",[United States]
74,"['United States', 'United States', 'United States', 'United States', 'United States']","[United States, United States]"
75,"['United States', 'United States']","[United States, United States]"
76,"['China', 'China', 'China', 'China', 'China']","[China, China]"
77,"['United States', 'United States', 'United States', 'United States']","[United States, United States, United States, United States]"
78,['United States'],[United States]
79,['United States'],[]
80,NaN,[]
81,NaN,[]
82,"['China', 'China', 'China']","[China, China]"
83,"['Brazil', 'Brazil', 'Brazil', 'Brazil']","[Brazil, Brazil, Brazil]"
84,"['China', 'China', 'China', 'China', 'China', 'China', 'China']","[China, China, China, China, China]"
85,"['France', 'France', 'France', 'France', 'France', 'France', 'France', 'Germany', 'Germany', 'Czechia', 'Czechia', 'France', 'France', 'France', 'France', 'France', 'France']","[France, Germany, Germany, France, France, France, France, France, France, France, France, France, France, France]"
86,"['Norway', 'Norway', 'Norway', 'Norway', 'Norway']",[Norway]
87,['United States'],[United States]
88,"['Romania', 'Romania', 'Romania', 'Romania']","[Romania, Romania, Romania]"
89,"['Taiwan', 'Taiwan', 'Taiwan', 'Taiwan', 'Taiwan', 'Taiwan', 'Taiwan']","[Taiwan, Taiwan, Taiwan, Taiwan, Taiwan]"
90,"['China', 'China', 'China']","[China, China]"
91,"['United States', 'Pakistan']","[Pakistan, United States]"
92,NaN,[]
93,NaN,[]
94,['United States'],[United States]
95,['United States'],[United States]
96,['United States'],[]
97,"['United States', 'United States']","[United States, United States]"
98,['Mexico'],[Mexico]
99,['The Netherlands'],[The Netherlands]
100,['Switzerland'],[Switzerland]
101,['United States'],[United States]
102,[],[]

In [304]:
df_2[["Institutions_man", "Institutions_db_name", "Unmatched_INS"]]

,Institutions_man,Institutions_db_name,Unmatched_INS
0,NaN,[],[]
1,NaN,[],[]
2,"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of British Columbia, i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto, Institute of Molecular Pathology and Immunology of the University of Porto, University of Porto]","[Hereditary Cancer, BC Cancer]"
3,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[Cincinnati Children's Hospital Medical Center, University of Cincinnati, Children's Healthcare of Atlanta, Emory University, Children's Hospital of Los Angeles]","[Aflac Cancer and Blood Disorders Center, GoBroad Hospital]"
4,"['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[University of Pennsylvania, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, University of Memphis, University of Chicago, University of Buffalo, Rutgers Institute for Nicotine & Tobacco Studies]","[Independent Contractor, TSET Health Promotion Research Center, Battelle Memorial Institute, Rutgers Biomedical and Health Sciences]"
5,"['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[CONAHCYT, Universidad Nacional Autónoma de México]","[Center for Research on Population Health, National Institute of Public Health, Institute for Research in Applied Mathematics and Systems, Harvard T. H. Chan, Center for Research on Evaluation and Surveys]"
6,"['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[Université de Toulouse, Inserm, CNRS, Centre de Recherche en Cancérologie de Toulouse, University Cancer Institute Toulouse Oncopole]","[Labex TOUCAN, ANR, Equipe SigDYN, Hubert Curien, Oncopole de Toulouse, TOUCAN, Curien, Joliot - Curie]"
7,['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University],[]
8,"['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw],[Institute of Developmental Biology and Biomedical Sciences]
9,"['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']","[Chang Gung University, Linkou Chang Gung Memorial Hospital, Chang Gung Memorial Hospital]",[]
10,"['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']","[Ruhr University Bochum, BG University Hospital Bergmannsheil Bochum, Ludwig-Maximilians-Universität in Munich, Medical Genetics Center]",[Friedrich - Baur - Institute]
11,"['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[IRCCS Ospedale San Raffaele, Università Vita-Salute San Raffaele]",[Diabetes Research Institute]
12,"['University of Adelaide', 'Queen Elizabeth Hospital']","[University of Adelaide, Queen Elizabeth Hospital]",[]
13,['University of Zimbabwe'],[University of Zimbabwe],[]
14,['University of Tokyo Hospital'],[University of Tokyo Hospital],[]
15,['University Hospital Centre of Grenoble'],[Grenoble University Hospital Centre],[]
16,['Harvard'],[],[Harvard University]
17,['University of Washington'],[University of Washington],[]
18,['University of Würzburg'],[University of Würzburg],[]
19,"['Mannheim Medical Center', 'University of Heidelberg']",[Heidelberg University],[Mannheim Medical Center]
20,NaN,[],[]
21,['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology],[]
22,['Duke University Medical Center'],[Duke University Medical Center],[]
23,"['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]","[Hewitt Centre for Reproductive Medicine, Liverpool Women's Hospital]",[]
24,['University of Rochester'],[University of Rochester],[]
25,['Stavanger University Hospital'],[Stavanger University Hospital],[]
26,['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[],[Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii]
27,['Akademii Medycznej w Gdańsku'],[],[Akademii Medycznej w Gdańsku]
28,['Vienna Medical University'],[Medical University of Vienna],[]
29,"['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]",[]
30,NaN,[],[]
31,"['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University],[Center for Gerontology and Health Care Research]
32,"['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital],[Tianjin Lung Cancer Institute]
33,"['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University],[Evidence Based Medicine Center]
34,NaN,[],[]
35,['Royal North Brisbane Hospital'],[Royal North Brisbane Hospital],[]
36,['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[Azienda Ospedaliero Universitaria Maggiore della Carita],[]
37,['Universitá degli Studi di Palermo'],[Università degli Studi di Palermo],[]
38,['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf],[]
39,NaN,[],[]
40,"['Institute of Medical Microbiology', 'Charles University']",[Charles University],[Institute of Medical Microbiology]
41,['Queensland Institute of Medical Research'],[Queensland Institute of Medical Research],[]
42,['University of Porto'],[University of Porto],[]
43,"['University of Liverpool', 'Linda McCartney Centre', 'Royal Liverpool University Hospital']","[University of Liverpool, Royal Liverpool University Hospital]",[Linda McCartney Centre]
44,"['University of Leipzig Medical Center', 'University Medical Center Hamburg-Eppendorf', 'Institute for Medical Biostatistics, Epidemiology and Informatics', 'University of Mainz Medical Center', 'University Hospital of Essen', ""Children's Hospital""]","[University Medical Center Hamburg-Eppendorf, Kantonsspital St. Gallen, University of Würzburg, University Medical Center Göttingen, Essen University Hospital, Institute for Medical Informatics and Biostatistics, University Hospital Bonn, Düsseldorf University Hospital]","[University of Leipzig Medical Center, University of Mainz Medical Center, University of Bonn Medical Center, Children's Hospital, Clinic and Policlinic for Radiation Therapy and Radiooncology]"
45,"['Northwestern Memorial Hospital', 'Robert H. Lurie Comprehensive Cancer Center', 'Northwestern University']","[Northwestern Memorial Hospital, Robert H. Lurie Comprehensive Cancer Center, Northwestern University]",[]
46,"['First Affiliated Hospital', 'Nanchang University']",[First Affiliated Hospital of Nanchang University],[]
47,"['Suzhou Municipal Hospital', 'Affiliated Suzhou Hospital', 'Nanjing Medical University', ""Shaoxing People's Hospital"", 'Shaoxing Hospital', 'Zhejiang University']","[Suzhou Municipal Hospital, Second Affiliated Hospital of Nanjing Medical University, Shaoxing People's Hospital, Children's Hospital of Zhejiang University]",[]
48,NaN,[],[]
49,NaN,[],[]
50,"['Institute of Biomedical and Genetic Engineering (IBGE)', 'International Islamic University']","[Institute of Biomedical and Genetic Engineering, International Islamic University, Islamabad]",[]
51,"['Istanbul University', 'Institute of Experimental Medicine', 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital']","[Istanbul University, Yeditepe University]","[Institute of Experimental Medicine, Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital]"
52,NaN,[],[]
53,NaN,[],[]
54,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', 'Cancer and Blood Disease Institute', ""Boston Children's Hospital"", 'Harvard']","[University of Cincinnati, Cincinnati Children's Hospital Medical Center, Boston Children's Museum, Harvard University]","[Cancer and Blood Disease Institute, Hospital]"
55,"['Erasmus MC', 'Utrecht University', 'Erasmus MC Cancer Institute']","[Utrecht University, Erasmus MC Cancer Institute, Erasmus MC]",[]
56,NaN,[],[]
57,NaN,[],[]
58,"['Queen Elizabeth Hospital', 'Royal Victoria Infirmary', 'Medical Research Council Clinical Trials Unit', 'University College London']","[Medical Research Council, University College London, Queen Elizabeth Hospital, Royal Victoria Infirmary]",[]
59,"['Centro Nacional de Investigaciones Oncológicas (CNIO)', 'Center for Molecular Biology of Heidelberg University (ZMBH)', 'Centro de Investigación en Red de Enfermedades Neurodegenerativas (CIBERNED)', 'University of Cantabria', 'IDIVAL', 'Center for Biomedicine and Medical Technology Mannheim (CBTM)', 'Heidelberg University', 'German Cancer Research Center (DKFZ)', 'Hope Center for Neurological Diseases', 'Washington University']","[Heidelberg University, Center for Molecular Biology Severo Ochoa, Centro de Investigación Biomédica en Red, Enfermedades Neurodegenerativas, University of Cantabria, IDIVAL, Centro Nacional de Investigaciones Oncológicas, German Cancer Research Center, DKFZ-ZMBH Alliance]","[Center for Biomedicine and Medical Technology Mannheim ( CBTM ), Hope Center for Neurological Diseases, Washington University]"
60,"[""King's College London"", 'Comprehensive Biomedical Research Centre', ""Guy's and St Thomas NHS Foundation Trust"", 'Uppsala University', 'Medical Products Agency', 'Karolinska Insituet']","[Karolinska Institutet, UCL Biomedical Research Centre, Guy's and St Thomas' NHS Foundation Trust, King's College London, Uppsala University, Medical Products Agency]",[]
61,"['August Pi i Sunyer Biomedical Research Institute', 'Hospital Clínic', 'Sant Joan de Deu Childrens Hospital', 'University of Barcelona', 'Nihon University School of Medicine', 'University of Lausanne', 'University of Pennsylvania', 'Catalan Institution for Research and Advanced Studies']","[Sant Joan de Déu-Barcelona Children’s Hospital, University of Barcelona, University of Lausanne, University of Pennsylvania, Catalan Institution for Research and Advanced Studies]","[August Pi i Sunyer Biomedical Research Institute, Hospital Clínic, Nihon University, . R. R, University, Research, D]"
62,['Delhi State Cancer Institute'],[Delhi State Cancer Institute],[]
63,"['Kushiro Rosai Hospital', 'Kanagawa Cancer Center', 'Keio University', 'Sapporo Medical University', 'Hijirigaoka Hospital', 'National Hospital Organization', 'Osaka National Hospital', 'Hiroshima University', 'University of Tokyo', 'Tokai Central Hospital', 'Translational Research and Clinical Trial Center', 'Hokkaido University Hospital', 'Japanese Foundation for Multidisciplinary Treatment of Cancer']","[Keio University, Japanese Foundation for Multidisciplinary Treatment of Cancer, Kanagawa Cancer Center, Kushiro Rosai Hospital, The University of Tokyo, National Hospital Organization, Osaka National Hospital, Sapporo Medical University, Hokkaido University Hospital, Tokai Central Hospital, Hiroshima University]","[Translational Research and Clinical Trial Center, Hijirigaoka Hospital]"
64,['Life Raft Group'],[],[]
65,['Washington State University'],[Washington State University],[]
66,"['Addis Ababa University', 'Karolinska Institutet', 'Karolinska University Hospital', 'Center for Innovative Drug Development and Therapeutic Trials', 'Armauer Hansen Research Institute']","[Karolinska Institutet, Armauer Hansen Research Institute, Addis Ababa University, Karolinska University Hospital]",[for Innovative Drug Development and Therapeutic Trials]
67,[nan],[],"[Unità di Biochimica, Unità di Fisiologia Generale]"
68,"['Tulane University', 'Louisiana State University Health Sciences Center']","[Tulane University, Louisiana State University Health Sciences Center New Orleans]",[]
69,"['Hebei Medical University', 'Bethune International Peace Hospital', 'Hebei University of Chinese Medicine']","[Bethune International Peace Hospital, Hebei Medical University, Hebei University of Chinese Medicine]",[]
70,"[""Henan Provincial People's Hospital"", ""Zhengzhou University People's Hospital"", ""Henan University People's Hospital"", 'Institute of Hematology']","[Shanghai Institute of Hematology, Henan Provincial People's Hospital, Zhengzhou People's Hospital, Peking University People's Hospital]",[]
71,"['Huazhong University of Science and Technology Union Shenzhen Hospital (Nanshan Hospital)', ""Shenzhen Second People's Hospital"", 'First Affiliated Hospital', 'Shenzhen University']","[Shenzhen Second People's Hospital, Huazhong University of Science and Technology]",[Shenzhen Hospital ( Nanshan Hospital )]
72,['Medical University of Innsbruck'],[Innsbruck Medical University],[]
73,"['Stanton L. Young Biomedical Research Center', 'University of Oklahoma Health Science Center']",[University of Oklahoma Health Sciences Center],"[Cancer, Oklahoma Stanton L. Young Biomedical Research Center]"
74,"['Center for Bioengineering and Tissue Regeneration', 'University of California', 'Gladstone Institutes', 'Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research', 'Helen Diller Family Comprehensive Cancer Center']","[Gladstone Institutes, UCSF Helen Diller Family Comprehensive Cancer Center]","[Center for Bioengineering and Tissue Regeneration, University of California, Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research]"
75,"['Northwestern University', 'Robert H. Lurie Comprehensive Cancer Center']","[Northwestern University, Robert H. Lurie Comprehensive Cancer Center]",[]
76,"['Qilu Hospital', 'Shandong University', 'Central Hospital', 'Zaozhuang Coal Mining Group', 'Jinan integrative medicine hospital']","[Integrative Medicine Hospital of Nanchang, Qilu Hospital of Shandong University]",[Central Hospital of Zaozhuang Coal Mining Group]
77,"[""St. Jude Children's Research Hospital"", 'Cornell', 'University of Chicago', 'Howard Hughes Medical Institute']","[University of Chicago, St. Jude Children's Research Hospital, Weill Cornell Medicine, Memphis Zoo]","[Cellular Screening Center, Howard Hughes Medical Institute, Preclinical, ']"
78,['Baylor College of Medicine'],[Baylor College of Medicine],[]
79,['University of California'],[],[University of California]
80,NaN,[],[]
81,NaN,[],[]
82,"['Second Affiliated Hospital', 'Fujian Medical University', 'Nanjing Medical University']","[Second Affiliated Hospital of Fujian Medical University, Nanjing Medical University]",[]
83,"['Universidade de São Paulo', 'Universidade do Oeste Paulista UNOESTE', 'Center of Translational Research in Oncology (LIM24)', 'Instituto do Cancer do Estado de Sao Paulo (ICESP)']","[Universidade de São Paulo, Universidade do Oeste Paulista, Instituto do Câncer do Estado de São Paulo]","[Prudente, Center of Translational Research in Oncology (, )]"
84,"['Hepatic Surgery Center', 'Tongji Hospital', 'Huazhong University of Science and Technology', 'Shanxi Bethune Hospital', 'Shanxi Academy of Medical Sciences', 'Shanxi Medical University', 'Shanxi Tongji Hospital']","[Tongji Hospital, Huazhong University of Science and Technology, Bethune Second Hospital, Shanxi Academy of Medical Sciences, Shanxi Medical University]",[Hepatic Surgery Center]
85,"['Centre de Recherche des Cordeliers', 'INSERM', 'Sorbonne Université', 'Université Paris Cité', 'Institut universitaire de France', 'Institut Gustave Roussy', 'Centre de Recherche des Cordeliers', 'Klinikum Rechts der Isar', 'Technical University of Munich', 'Institute of Biophysics', 'Czech Academy of Sciences', 'CNRS', 'Institut Polytechnique de Paris', 'Université Paris-Saclay', 'Université Sorbonne Paris Nord', 'Institut du Cancer Paris CARPEM', 'Hôpital Européen Georges Pompidou']","[Université Sorbonne Paris Nord, Klinikum rechts der Isar, Technical University of Munich, Institut Gustave Roussy, Centre de Recherche des Cordeliers, INSERM, Sorbonne Université, Université Paris Cité, Institut Universitaire de France, Hôpital Européen Georges-Pompidou, CNRS, Université Paris-Saclay, École Polytechnique, Institut Polytechnique de Paris]","[Institute of Biophysics, Czech Academy of Sciences, Institut du Cancer Paris CARPEM]"
86,"['Norwegian University of Science and Technology', 'St. Olavs Hospital', 'Center for Oral Health Services and Research Mid-Norway (TkMidt)', 'Clinic of Medicine', 'K.G. Jebsen Centre for Genetic Epidemiology']",[Norwegian University of Science and Technology],"[K. G. Jebsen Centre for Genetic Epidemiology, Center for Oral Health Services and Research Mid - Norway ( TkMidt ), St. Olavs Hospital, Trondheim University Hospital]"
87,['Mayo Clinic'],[Mayo Clinic],[]
88,"['University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca', 'Biotechnology Research Center', 'Life Sciences Institute King Michael I of Romania', 'Babeș-Bolyai University']","[University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca, Universitatea Babeș-Bolyai, Banat University of Agricultural Sciences and Veterinary Medicine]","[Biotechnology Research Center, Life Sciences Institute "" King Michael I of Romania ""]"
89,"['Graduate Institute of Biomedical Science', 'China Medical University', 'Taichung Tzu Chi Hospital', 'Buddhist Tzu Chi Medical Foundation', 'China Medical University Hospital', 'Asia University', 'Institute of New Drug Development']","[Asia University, China Medical University, China Medical University Hospital, Taichung Hospital, Tzu Chi University]","[Graduate Institute of Biomedical Science, Institute of New Drug Development, Buddhist Tzu Chi Medical Foundation]"
90,"['Chongqing University Three Gorges Hospital', 'Center for Medicine Research and Translation', ""Chengdu Fifth People's Hospital""]","[Chongqing Three Gorges University, Chengdu Fifth People's Hospital]",[Center for Medicine Research and Translation]
91,"['Boston University', 'Shaukat Khanum Memorial Cancer Hospital and Research Centre']","[Shaukat Khanum Memorial Cancer Hospital and Research Center, Boston University]",[]
92,NaN,[],[]
93,NaN,[],[]
94,['Georgetown University Medical Center'],[Georgetown University Medical Center],[]
95,['University of South Florida'],[University of South Florida],[]
96,['Johns Hopkins Oncology Center'],[],[Johns Hopkins Oncology Center]
97,"['Albert Einstein Cancer Center', 'Montefiore Medical Center']","[Albert Einstein Cancer Center at Montefiore, Montefiore Medical Center]",[]
98,['General Hospital Manuel Gea Gonzalez'],[Hospital General Dr. Manuel Gea Gonzalez],[]
99,['University Hospital Leiden'],[Leiden University],[]
100,['Paul Scherrer Institute'],[Paul Scherrer Institute],[]
101,['Wayne State University'],[Wayne State University],[]
102,[],[],[]

In [302]:
counter_hits(df_2)

(272, 200)

In [269]:
df_2.at[61,"NER_BERT"]

"[{'entity_group': 'INS', 'score': np.float32(0.99986506), 'word': 'August Pi i Sunyer Biomedical Research Institute', 'start': 60, 'end': 108}, {'entity_group': 'INS', 'score': np.float32(0.9982741), 'word': 'Hospital Clínic', 'start': 110, 'end': 125}, {'entity_group': 'INS', 'score': np.float32(0.9998502), 'word': 'Sant Joan de Deu Childrens Hospital', 'start': 225, 'end': 260}, {'entity_group': 'INS', 'score': np.float32(0.99936914), 'word': 'University of Barcelona', 'start': 275, 'end': 298}, {'entity_group': 'COU', 'score': np.float32(0.9965491), 'word': 'Spain', 'start': 300, 'end': 305}, {'entity_group': 'INS', 'score': np.float32(0.9995256), 'word': 'Nihon University', 'start': 361, 'end': 377}, {'entity_group': 'INS', 'score': np.float32(0.98499215), 'word': 'University of Lausanne ( M. S. )', 'start': 405, 'end': 434}, {'entity_group': 'COU', 'score': np.float32(0.974667), 'word': 'Switzerland', 'start': 436, 'end': 447}, {'entity_group': 'INS', 'score': np.float32(0.99937075), 'word': 'University of Pennsylvania', 'start': 489, 'end': 515}, {'entity_group': 'SUBC', 'score': np.float32(0.99910295), 'word': 'Philadelphia', 'start': 517, 'end': 529}, {'entity_group': 'INS', 'score': np.float32(0.99906456), 'word': 'Catalan Institution for Research and Advanced Studies ( J. D. )', 'start': 535, 'end': 595}, {'entity_group': 'SUBC', 'score': np.float32(0.9927516), 'word': 'Barcelona', 'start': 597, 'end': 606}, {'entity_group': 'COU', 'score': np.float32(0.99932873), 'word': 'Spain', 'start': 608, 'end': 613}, {'entity_group': 'INS', 'score': np.float32(0.9998571), 'word': 'August Pi i Sunyer Biomedical Research Institute', 'start': 676, 'end': 724}, {'entity_group': 'INS', 'score': np.float32(0.9941374), 'word': 'Hospital Clínic', 'start': 726, 'end': 741}, {'entity_group': 'INS', 'score': np.float32(0.74241), 'word': '. R. R', 'start': 792, 'end': 796}, {'entity_group': 'INS', 'score': np.float32(0.9998589), 'word': 'Sant Joan de Deu Childrens Hospital', 'start': 841, 'end': 876}, {'entity_group': 'INS', 'score': np.float32(0.99968034), 'word': 'University of Barcelona', 'start': 891, 'end': 914}, {'entity_group': 'COU', 'score': np.float32(0.96431303), 'word': 'Spain', 'start': 916, 'end': 921}, {'entity_group': 'INS', 'score': np.float32(0.9998399), 'word': 'Nihon University', 'start': 977, 'end': 993}, {'entity_group': 'INS', 'score': np.float32(0.9944571), 'word': 'University of Lausanne ( M. S. )', 'start': 1021, 'end': 1050}, {'entity_group': 'COU', 'score': np.float32(0.98761797), 'word': 'Switzerland', 'start': 1052, 'end': 1063}, {'entity_group': 'INS', 'score': np.float32(0.9497266), 'word': 'University', 'start': 1105, 'end': 1115}, {'entity_group': 'SUBC', 'score': np.float32(0.5670025), 'word': 'Pennsylvania', 'start': 1119, 'end': 1131}, {'entity_group': 'SUBC', 'score': np.float32(0.81518286), 'word': 'Philadelphia', 'start': 1133, 'end': 1145}, {'entity_group': 'INS', 'score': np.float32(0.6264231), 'word': 'Research', 'start': 1175, 'end': 1183}, {'entity_group': 'INS', 'score': np.float32(0.4781894), 'word': 'D', 'start': 1208, 'end': 1209}, {'entity_group': 'SUBC', 'score': np.float32(0.5408628), 'word': 'Barcelona', 'start': 1213, 'end': 1222}]"

In [257]:
df_2[["Institutions_man", "Institutions_db_country"]]

,Countries_man,Institutions_db_country
0,NaN,[]
1,NaN,[]
2,"['Portugal', 'Portugal', 'Canada', 'Canada', 'Portugal']","[Canada, Portugal, Portugal, Portugal]"
3,"['United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'China', 'China']","[United States, United States, United States, United States, United States]"
4,"['United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States']","[United States, United States, United States, United States, United States, United States, United States]"
5,"['Mexico', 'Mexico', 'Mexico', 'Mexico', 'Mexico', 'Mexico', 'United States']","[Mexico, Mexico]"
6,"['France', 'France', 'France', 'France', 'France', 'France', 'France']","[France, France, France, France, France]"
7,['China'],[China]
8,"['Poland', 'Poland']",[Poland]
9,"['Taiwan', 'Taiwan']","[Taiwan, Taiwan, Taiwan]"
10,"['Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Switzerland', 'Germany', 'Germany', 'Germany']","[Germany, Germany, Germany, Germany]"
11,"['Italy', 'Italy', 'Italy']","[Italy, Italy]"
12,"['Autralia', 'Autralia']","[Australia, Australia]"
13,['Zimbabwe'],[Zimbabwe]
14,['Japan'],[Japan]
15,['France'],[France]
16,['United States'],[]
17,['United States'],[United States]
18,['Germany'],[Germany]
19,"['Germany', 'Germany']",[Germany]
20,NaN,[]
21,['Norway'],[Norway]
22,['United States'],[United States]
23,"['United Kingdom', 'United Kingdom']","[United Kingdom, United Kingdom]"
24,['United States'],[United States]
25,['Norway'],[Norway]
26,['Poland'],[]
27,['Poland'],[]
28,['Austria'],[Austria]
29,"['China', 'China']","[China, China]"
30,NaN,[]
31,"['United States', 'United States']",[United States]
32,"['China', 'China']",[China]
33,"['China', 'China']",[China]
34,['New Zealand'],[]
35,['Australia'],[Australia]
36,['Italy'],[Italy]
37,['Italy'],[Italy]
38,['Germany'],[Germany]
39,NaN,[]
40,"['Czechia', 'Czechia']",[Czechia]
41,['Australia'],[Australia]
42,['Portugal'],[Portugal]
43,"['United Kingdom', 'United Kingdom', 'United Kingdom']","[United Kingdom, United Kingdom]"
44,"['Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany']","[Germany, Switzerland, Germany, Germany, Germany, Switzerland, Germany, Germany]"
45,"['United States', 'United States', 'United States']","[United States, United States, United States]"
46,"['China', 'China']",[China]
47,"['China', 'China', 'China', 'China', 'China', 'China']","[China, China, China, China]"
48,NaN,[]
49,NaN,[]
50,"['Pakistan', 'Pakistan']","[Pakistan, Pakistan]"
51,"['Türkiye', 'Türkiye', 'Türkiye']","[Türkiye, Türkiye]"
52,NaN,[]
53,NaN,[]
54,"['United States', 'United States', 'United States', 'United States', 'United States']","[United States, United States, United States, United States]"
55,"['The Netherlands', 'The Netherlands', 'The Netherlands']","[The Netherlands, The Netherlands, The Netherlands]"
56,NaN,[]
57,NaN,[]
58,"['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']","[United Kingdom, United Kingdom, Australia, United Kingdom]"
59,"['Spain', 'Germany', 'Spain', 'Spain', 'Spain', 'Germany', 'Germany', 'Germany', 'United States', 'United States']","[Germany, Spain, Spain, Spain, Spain, Spain, Germany, Germany]"
60,"['United Kingdom', 'United Kingdom', 'United Kingdom', 'Sweden', 'Sweden', 'Sweden']","[Sweden, United Kingdom, United Kingdom, United Kingdom, Sweden, Sweden]"
61,"['Spain', 'Spain', 'Spain', 'Spain', 'Japan', 'Switzerland', 'United States', 'Spain']","[Spain, Spain, Switzerland, United States, Spain]"
62,['India'],[India]
63,"['Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan']","[Japan, Japan, Japan, Japan, Japan, Japan, Japan, Japan, Japan, Japan, Japan]"
64,['United States'],[]
65,['United States'],[United States]
66,"['Ethiopia', 'Sweden', 'Sweden', 'Ethiopia', 'Ethiopia']","[Sweden, Ethiopia, Ethiopia, Sweden]"
67,['Italy'],[]
68,"['United States', 'United States']","[United States, United States]"
69,"['China', 'China', 'China']","[China, China, China]"
70,"['China', 'China', 'China', 'China']","[China, China, China, China]"
71,"['China', 'China', 'China', 'China']","[China, China]"
72,['Austria'],[Austria]
73,"['United States', 'United States']",[United States]
74,"['United States', 'United States', 'United States', 'United States', 'United States']","[United States, United States]"
75,"['United States', 'United States']","[United States, United States]"
76,"['China', 'China', 'China', 'China', 'China']","[China, China]"
77,"['United States', 'United States', 'United States', 'United States']","[United States, United States, United States, United States]"
78,['United States'],[United States]
79,['United States'],[]
80,NaN,[]
81,NaN,[]
82,"['China', 'China', 'China']","[China, China]"
83,"['Brazil', 'Brazil', 'Brazil', 'Brazil']","[Brazil, Brazil, Brazil]"
84,"['China', 'China', 'China', 'China', 'China', 'China', 'China']","[China, China, China, China, China]"
85,"['France', 'France', 'France', 'France', 'France', 'France', 'France', 'Germany', 'Germany', 'Czechia', 'Czechia', 'France', 'France', 'France', 'France', 'France', 'France']","[France, Germany, Germany, France, France, France, France, France, France, France, France, France, France, France]"
86,"['Norway', 'Norway', 'Norway', 'Norway', 'Norway']",[Norway]
87,['United States'],[United States]
88,"['Romania', 'Romania', 'Romania', 'Romania']","[Romania, Romania, Romania]"
89,"['Taiwan', 'Taiwan', 'Taiwan', 'Taiwan', 'Taiwan', 'Taiwan', 'Taiwan']","[Taiwan, Taiwan, Taiwan, Taiwan, Taiwan]"
90,"['China', 'China', 'China']","[China, China]"
91,"['United States', 'Pakistan']","[Pakistan, United States]"
92,NaN,[]
93,NaN,[]
94,['United States'],[United States]
95,['United States'],[United States]
96,['United States'],[]
97,"['United States', 'United States']","[United States, United States]"
98,['Mexico'],[Mexico]
99,['The Netherlands'],[The Netherlands]
100,['Switzerland'],[Switzerland]
101,['United States'],[United States]
102,[],[]

In [299]:
clean = ast.literal_eval(re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[61, "NER_BERT"]))

clean1 = set([el['word'] for el in clean if el['entity_group'] == 'COU'])
clean2 = set([el['word'] for el in clean if el['entity_group'] == 'SUBC'])

print(clean1, clean2)

{'Spain', 'Switzerland'} {'Barcelona', 'Philadelphia', 'Pennsylvania'}

In [252]:
df["Institutions_db_name"] == df_2["Institutions_db_name"]

0       True
1       True
2      False
3       True
4      False
5       True
6      False
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16     False
17      True
18      True
19     False
20      True
21      True
22     False
23     False
24      True
25      True
26      True
27      True
28      True
29      True
30      True
31      True
32      True
33      True
34      True
35     False
36      True
37      True
38      True
39      True
40      True
41      True
42      True
43      True
44     False
45      True
46      True
47      True
48      True
49      True
50      True
51      True
52      True
53      True
54      True
55      True
56      True
57      True
58      True
59      True
60      True
61     False
62      True
63      True
64      True
65      True
66      True
67      True
68      True
69      True
70      True
71      True
72      True
73      True
74      True
75      True
76      True
77     False
78      True
79      True
80      True
81      True
82      True
83      True
84      True
85     False
86      True
87      True
88     False
89     False
90      True
91      True
92      True
93      True
94      True
95      True
96      True
97      True
98      True
99      True
100     True
101     True
102     True
Name: Institutions_db_name, dtype: bool

# SOLVE FALSE POSITIVES WHEN ONLY 1 EXACT MATCH WHILE SOLVING FALSE NEGATIVES WHILE 1 MATCH WHITHOUT COU OR SUBCOU INFORMATION

# ENRICH COU AND/OR SUBCOU WITH EMAIL DOMAINS

# WHEN SEVERAL MATCHES IN EXACT OR FUZZY PASS THE COUNTRY FILTER, DISAMBIGUATE VIA SUBCOUNTRY

# DISAMBIGUATE VIA AUTHOR SEARCH IN ANY DB

# SOLVE FOR DISAMBIGUATION OF UNIVERSITY OF CALIFORNIA

In [307]:
DF_input_new = input().strip()

 C:\Users\svalb\OneDrive\Escritorio\Data_40_years_cancer_studies\preparedInstitutionsTestDatabaseAccess_v2.csv

In [308]:
df_new = pd.read_csv(DF_input_new)

In [309]:
df_new

,PMID,Authors,NER_BERT,Country,Institutions_man,Countries_man
0,20301377,"[{'Name': 'Katy Phelan', 'Affiliation': ['Director of Genetics, Florida Cancer Specialists and Research Institute, Fort Myers, Florida']}, {'Name': 'R Curtis Rogers', 'Affiliation': ['Senior Clinical Geneticist, RCR Genetics, Greenville, South Carolina']}, {'Name': 'Luigi Boccuto', 'Affiliation': ['Clinical Associate Professor, Clemson University, Clemson, South Carolina']}]","[{'entity_group': 'INS', 'score': np.float32(0.9981718), 'word': 'RCR Genetics', 'start': 28, 'end': 40}, {'entity_group': 'SUBC', 'score': np.float32(0.99934596), 'word': 'Greenville', 'start': 42, 'end': 52}, {'entity_group': 'SUBC', 'score': np.float32(0.99422634), 'word': 'South Carolina', 'start': 54, 'end': 68}, {'entity_group': 'INS', 'score': np.float32(0.9998832), 'word': 'Florida Cancer Specialists and Research Institute', 'start': 92, 'end': 141}, {'entity_group': 'SUBC', 'score':...",United States,"['Florida Cancer Specialists and Research Institute', 'RCR Genetics', 'Clemson University']","['United States', 'United States', 'United States']"
1,20301398,"[{'Name': 'Alex F Nisbet', 'Affiliation': [""Children's Hospital of Philadelphia, Philadelphia, Pennsylvania"", 'Perelman School of Medicine, University of Pennsylvania, Philadelphia, Pennsylvania']}, {'Name': 'Evan R Hathaway', 'Affiliation': [""Children's Hospital of Philadelphia, Philadelphia, Pennsylvania""]}, {'Name': 'Jennifer M Kalish', 'Affiliation': [""Children's Hospital of Philadelphia, Philadelphia, Pennsylvania"", 'Perelman School of Medicine, University of Pennsylvania, Philadelphia,...","[{'entity_group': 'INS', 'score': np.float32(0.9996674), 'word': 'University of Pennsylvania', 'start': 29, 'end': 55}, {'entity_group': 'SUBC', 'score': np.float32(0.99971586), 'word': 'Philadelphia', 'start': 57, 'end': 69}, {'entity_group': 'SUBC', 'score': np.float32(0.9786365), 'word': 'Pennsylvania', 'start': 71, 'end': 83}, {'entity_group': 'INS', 'score': np.float32(0.99981433), 'word': ""Children ' s Hospital of Philadelphia"", 'start': 85, 'end': 120}, {'entity_group': 'SUBC', 'score...",United States,"[""Children's Hospital of Philadelphia"", 'University of Pennsylvania']","['United States', 'United States']"
2,39290119,"[{'Name': 'Ali Najafi', 'Affiliation': ['Molecular Biology Research Center, Biomedicine Technologies Institute, Baqiyatallah University of Medical Sciences, Tehran, Iran.']}, {'Name': 'Mohammad Hossein Ataee', 'Affiliation': ['Molecular Biology Research Center, Biomedicine Technologies Institute, Baqiyatallah University of Medical Sciences, Tehran, Iran.']}, {'Name': 'Mahdieh Farzanehpour', 'Affiliation': ['Applied Virology Research Center, Biomedicine Technologies Institute, Baqiyatallah Un...","[{'entity_group': 'INS', 'score': np.float32(0.999895), 'word': 'Applied Virology Research Center', 'start': 0, 'end': 32}, {'entity_group': 'INS', 'score': np.float32(0.9998443), 'word': 'Biomedicine Technologies Institute', 'start': 34, 'end': 68}, {'entity_group': 'INS', 'score': np.float32(0.9999261), 'word': 'Baqiyatallah University of Medical Sciences', 'start': 70, 'end': 113}, {'entity_group': 'SUBC', 'score': np.float32(0.99943334), 'word': 'Tehran', 'start': 115, 'end': 121}, {'ent...",Iran,"['Molecular Biology Research Center', 'Biomedicine Technologies Institute', 'Baqiyatallah University of Medical Sciences', 'Applied Virology Research Center', 'Research Institute of Petroleum Industry (RIPI)']","['Iran', 'Iran', 'Iran', 'Iran', 'Iran']"
3,39290121,"[{'Name': 'Marziyeh Ghanemi', 'Affiliation': ['Department of Orthodontics, School of Dentistry, Shahed University, Tehran, Iran.']}, {'Name': 'Aminollah Pourshohod', 'Affiliation': ['Department of Biochemistry, Cellular and Molecular Research Center, Ahvaz Jundishapur University of Medical Sciences, Medical School, Ahvaz, Iran.']}, {'Name': 'Majid Zeinali', 'Affiliation': ['Biotechnology Research Center, Research Institute of Petroleum Industry (RIPI), Tehran, Iran.']}, {'Name': 'Ebrahim Bar...","[{'entity_group': 'INS', 'score': np.float32(0.9997722), 'word': 'Abadan University of Medical Sciences', 'start': 44, 'end': 81}, {'entity_group': 'SUBC', 'score': np.float32(0.99980026), 'word': 'Abadan', 'start': 83, 'end': 89}, {'entity_group': 'COU', 'score': np.float32(0.99980277), 'word': 'Iran', 'start': 91, 'end': 95}, {'entity_group': 'EMA', 'score': np.float32(0.99585605), 'word': 'mjamalanbiochem @ abadanums. ac. ir.', 'start': 104, 'end': 136}, {'entity_group': 'INS', 'score': n...",Iran,"['Shahed University', 'Cellular and Molecular Research Center', 'Ahvaz Jundishapur University of Medical Sciences', 'Biotechnology Research Center', 'Medical Biology Research Center', 'Health Technology Institute', 'Kermanshah University of Medical Sciences', 'Abadan University of Medical Sciences']","['Iran', 'Iran', 'Iran', 'Iran', 'Iran', 'Iran', 'Iran', 'Iran']"
4,39979457,"[{'Name': 'Kollin Schultz', 'Affiliation': ['Abramson Family Cancer Research Institute, Perelman School of Medicine, University of Pennsylvania, Philadelphia, PA, USA. kollin.schultz@pennmedicine.upenn.edu.', 'Graduate Group in Biochemistry, Biophysics and Chemical Biology, Perelman School of Medicine, University of Pennsylvania, Philadelphia, PA, USA. kollin.schultz@pennmedicine.upenn.edu.']}, {'Name': 'Pedro Costa-Pinheiro', 'Affiliation': ['Abramson Family Cancer Research Institute, Perel...","[{'entity_group': 'INS', 'score': np.float32(0.99983245), 'word': 'University of Pennsylvania', 'start': 59, 'end': 85}, {'entity_group': 'SUBC', 'score': np.float32(0.9994265), 'word': 'Philadelphia', 'start': 87, 'end': 99}, {'entity_group': 'COU', 'score': np.float32(0.9990584), 'word': 'USA', 'start': 105, 'end': 108}, {'entity_group': 'INS', 'score': np.float32(0.99990195), 'word': 'Abramson Family Cancer Research Institute', 'start': 111, 'end': 152}, {'entity_group': 'INS', 'score': n...",United States,"['Abramson Family Cancer Research Institute', 'University of Pennsylvania']","['United States', 'United States']"
5,39979460,"[{'Name': 'Justin Langerman', 'Affiliation': ['Department of Biological Chemistry, David Geffen School of Medicine at the University of California Los Angeles, Los Angeles, CA, USA.']}, {'Name': 'Sevana Baghdasarian', 'Affiliation': ['Department of Chemical and Biomolecular Engineering, University of California Los Angeles, Los Angeles, CA, USA.']}, {'Name': 'Rene Yu-Hong Cheng', 'Affiliation': [""Center of Immunotherapy and Immunity, Seattle Children's Research Institute, Seattle, WA, USA."",...","[{'entity_group': 'INS', 'score': np.float32(0.9998769), 'word': 'University of Washington', 'start': 42, 'end': 66}, {'entity_group': 'SUBC', 'score': np.float32(0.99774605), 'word': 'Seattle', 'start': 68, 'end': 75}, {'entity_group': 'COU', 'score': np.float32(0.9959745), 'word': 'USA', 'start': 81, 'end': 84}, {'entity_group': 'INS', 'score': np.float32(0.9972469), 'word': 'University of California Los Angeles', 'start': 162, 'end': 198}, {'entity_group': 'SUBC', 'score': np.float32(0.99...",United States,"['University of California', 'Center of Immunotherapy and Immunity', ""Seattle Children's Research Institute"", 'Molecular Engineering and Science Institute', 'University of Washington', 'Brotman-Baty Institute for Precision Medicine', 'Molecular Biology Institute', 'Jonsson Comprehensive Cancer Center', 'Brain Research Institute', 'Eli and Edythe Broad Center of Regenerative Medicine and Stem Cell Research', 'Partillion Bioscience Corporation', 'California NanoSystems Institute (CNSI)']","['United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States']"
6,40651609,"[{'Name': 'Aila Akosua Kattner', 'Affiliation': []}]",[],NaN,NaN,NaN
7,40651610,"[{'Name': 'Thales Hein Da Rosa', 'Affiliation': ['Department of Medicine, Kao Autoimmunity Institute, Cedars-Sinai Medical Center, Los Angeles, California, USA.']}, {'Name': 'Sterling H Ramsey', 'Affiliation': ['Department of Medicine, University of California, San Diego, La Jolla, California, USA.']}, {'Name': 'Judy J Lee', 'Affiliation': ['Department of Medicine, Kao Autoimmunity Institute, Cedars-Sinai Medical Center, Los Angeles, California, USA.']}, {'Name': 'Natalia Y Kozlova', 'Affili...","[{'entity_group': 'INS', 'score': np.float32(0.9999077), 'word': 'Cedars - Sinai Medical Center', 'start': 68, 'end': 95}, {'entity_group': 'SUBC', 'score': np.float32(0.99883276), 'word': 'Los Angeles', 'start': 97, 'end': 108}, {'entity_group': 'SUBC', 'score': np.float32(0.99934953), 'word': 'California', 'start': 110, 'end': 120}, {'entity_group': 'COU', 'score': np.float32(0.99932075), 'word': 'USA', 'start': 122, 'end': 125}, {'entity_group': 'INS', 'score': np.float32(0.9998512), 'wor...",United States,"['Kao Autoimmunity Institute', 'Cedars-Sinai Medical Center', 'University of California', 'Samuel Oschin Comprehensive Cancer Institute']","['United States', 'United States', 'United States', 'United States']"
8,25905309,"[{'Name': 'Michail Savvas K. Magklis', 'Affiliation': []}, {'Name': 'Nicolas C. Nicolaides', 'Affiliation': ['Medical School, University of Cyprus']}, {'Name': 'George P. Chrousos', 'Affiliation': ['Professor of Pediatrics and Endocrinology, holder, UNESCO Chair on Adolescent Health Care, National and Kapodistrian University of Athens Medical School, ""Aghia Sophia"" Children\'s Hospital, and Director, Division of Endocrinology and Metabolism, Center of Clinical, Experimental Surgery and Trans...","[{'entity_group': 'INS', 'score': np.float32(0.9996116), 'word': 'National and Kapodistrian University of Athens', 'start': 91, 'end': 137}, {'entity_group': 'INS', 'score': np.float32(0.9416255), 'word': '"" Aghia Sophia "" Children \' s Hospital', 'start': 154, 'end': 188}, {'entity_group': 'INS', 'score': np.float32(0.9064649), 'word': 'of Clinical, Experimental Surgery and Translational Research', 'start': 253, 'end': 313}, {'entity_group': 'INS', 'score': np.float32(0.98334646), 'word': '...",United States,"['University of Cyprus', 'National and Kapodistrian University of Athens', ""'Aghia Sophia' Children's Hospital"", 'Center of Clinical, Experimental Surgery and Translational Research', 'Biomedical Research Foundation', 'Academy of Athens', 'NICHD', 'NIH']","['Cyprus', 'Greece', 'Greece', 'Greece', 'Greece', 'Greece', 'United States', 'United States']"
9,26561699,"[{'Name': 'Megan C. Herink', 'Affiliation': ['Associate Clinical Professor, College of Pharmacy, Oregon State University/Oregon Health & Sciences University College of Pharmacy']}]","[{'entity_group': 'INS', 'score': np.float32(0.9967541), 'word': 'Oregon State University', 'start': 51, 'end': 74}, {'entity_group': 'INS', 'score': np.float32(0.9998077), 'word': 'Oregon Health & Sciences University', 'start': 75, 'end': 110}]",United States,"['Oregon State University', 'Oregon Health & Sciences University']","['United States', 'United States']"
10,1279132,"[{'Name': 'G Karp', 'Affiliation': ['Department of Medicine, UMDNJ-Robert Wood Johnson Medical School.']}, {'Name': 'K Nahum', 'Affiliation': []}]","[{'entity_group': 'INS', 'score': np.float32(0.99991405), 'word': 'UMDNJ', 'start': 24, 'end': 29}, {'entity_group': 'INS', 'score': np.float32(0.99986017), 'word': 'Robert Wood Johnson Medical School', 'start': 30, 'end': 64}]",United States,['UMDNJ'],['United States']
11,1279148,"[{'Name': 'M Bullinger', 'Affiliation': ['Biometric Centre in Therapeutic Studies, Munich, Germany.']}]","[{'entity_group': 'INS', 'score': np.float32(0.99990815), 'word': 'Biometric Centre in Therapeutic Studies', 'start': 0, 'end': 39}, {'entity_group': 'SUBC', 'score': np.float32(0.9994955), 'word': 'Munich', 'start': 41, 'end': 47}, {'entity_group': 'COU', 'score': np.float32(0.9997831), 'word': 'Germany', 'start': 49, 'end': 56}]",Germany,['Biometric Centre in Therapeutic Studies'],['Germany']
12,11267981,"[{'Name': 'N Uchida', 'Affiliation': ['Central Laboratory and Radiation Biology, Aichi Cancer Center Research Institute, Nagoya, Japan. nuchida@aichi-cc.pref.aichi.jp']}, {'Name': 'H Kumimoto', 'Affiliation': []}, {'Name': 'K Nishizawa', 'Affiliation': []}, {'Name': 'S Tokumasu', 'Affiliation': []}, {'Name': 'H Harada', 'Affiliation': []}, {'Name': 'Y Shimada', 'Affiliation': []}, {'Name': 'K Ishizaki', 'Affiliation': []}]","[{'entity_group': 'INS', 'score': np.float32(0.99988556), 'word': 'Aichi Cancer Center Research Institute', 'start': 42, 'end': 80}, {'entity_group': 'SUBC', 'score': np.float32(0.99950993), 'word': 'Nagoya', 'start': 82, 'end': 88}, {'entity_group': 'COU', 'score': np.float32(0.9996674), 'word': 'Japan', 'start': 90, 'end': 95}, {'entity_group': 'EMA', 'score': np.float32(0.99993014), 'word': 'nuchida @ aichi - cc. pref. aichi. jp', 'start': 97, 'end': 127}]",Japan,['Aichi Cancer Center Research Institute'],['Japan']
13,11267982,"[{'Name': 'Y Connolly', 'Affiliation': ['Paterson Institute for Cancer Research, Christie CRC Research Centre, Manchester, United Kingdom.']}, {'Name': 'E Littler', 'Affiliation': []}, {'Name': 'N Sun', 'Affiliation': []}, {'Name': 'X Chen', 'Affiliation': []}, {'Name': 'P C Huang', 'Affiliation': []}, {'Name': 'S N Stacey', 'Affiliation': []}, {'Name': 'J R Arrand', 'Affiliation': []}]","[{'entity_group': 'INS', 'score': np.float32(0.99988425), 'word': 'Paterson Institute for Cancer Research', 'start': 0, 'end': 38}, {'entity_group': 'INS', 'score': np.float32(0.99989104), 'word': 'Christie CRC Research Centre', 'start': 40, 'end': 68}, {'entity_group': 'SUBC', 'score': np.float32(0.9994293), 'word': 'Manchester', 'start': 70, 'end': 80}, {'entity_group': 'COU', 'score': np.float32(0.9987502), 'word': 'United Kingdom', 'start': 82, 'end': 96}]",United Kingdom,"['Paterson Institute for Cancer Research', 'Christie CRC Research Centre']","['United Kingdom', 'United Kingdom']"
14,12110349,"[{'Name': 'Kay S Amin', 'Affiliation': ['Division of Oral, Head, and Neck Pathology, Department of Pathology, The University of Texas Health Science Center at San Antonio, 7703 Floyd Curl Drive, 78229-7750, USA. amin@pathology.uthscsa.edu']}, {'Name': 'Aamir Ehsan', 'Affiliation': []}, {'Name': 'H Stan McGuff', 'Affiliation': []}, {'Name': 'Steven C Albright', 'Affiliation': []}]","[{'entity_group': 'INS', 'score': np.float32(0.99974376), 'word': 'University of Texas Health Science Center at San Antonio', 'start': 73, 'end': 129}, {'entity_group': 'COU', 'score': np.float32(0.9924534), 'word': 'USA', 'start': 166, 'end': 169}, {'entity_group': 'EMA', 'score': np.float32(0.99991184), 'word': 'amin @ pathology. uthscsa. edu', 'start': 171, 'end': 197}]",United States,['University of Texas Health Science Center'],['United States']
15,12110376,"[{'Name': 'Loukas Tatidis', 'Affiliation': ['Division of Clinical Pharmacology, Department of Medicine, Karolinska Institute & Hospital, Stockholm, Sweden. loukas.tatidis@ks.se']}, {'Name': 'Michèle Masquelier', 'Affiliation': []}, {'Name': 'Sigurd Vitols', 'Affiliation': []}]","[{'entity_group': 'INS', 'score': np.float32(0.99989575), 'word': 'Karolinska Institute & Hospital', 'start': 59, 'end': 90}, {'entity_group': 'SUBC', 'score': np.float32(0.99968386), 'word': 'Stockholm', 'start': 92, 'end': 101}, {'entity_group': 'COU', 'score': np.float32(0.99758744), 'word': 'Sweden', 'start': 103, 'end': 109}, {'entity_group': 'EMA', 'score': np.float32(0.99991864), 'word': 'loukas. tatidis @ ks. se', 'start': 111, 'end': 131}]",Sweden,['Karolinska Institute & Hospital'],['Sweden']
16,14509956,"[{'Name': 'Ingrid Elena Dumitriu', 'Affiliation': ['Institute for Clinical Immunology, Department of Medicine III, Friedrich Alexander University of Erlangen-Nuremberg, Erlangen, Germany. martin.herrmann@med3.imed.uni-erlangen.de']}, {'Name': 'Franz Roedel', 'Affiliation': []}, {'Name': 'Thomas D Beyer', 'Affiliation': []}, {'Name': 'Udo S Gaipl', 'Affiliation': []}, {'Name': 'Joachim R Kalden', 'Affiliation': []}, {'Name': 'Martin Herrmann', 'Affiliation': []}]","[{'entity_group': 'INS', 'score': np.float32(0.9999131), 'word': 'Institute for Clinical Immunology', 'start': 0, 'end': 33}, {'entity_group': 'INS', 'score': np.float32(0.9998187), 'word': 'University of Erlangen - Nuremberg', 'start': 83, 'end': 115}, {'entity_group': 'SUBC', 'score': np.float32(0.99975795), 'word': 'Erlangen', 'start': 117, 'end': 125}, {'entity_group': 'COU', 'score': np.float32(0.99964297), 'word': 'Germany', 'start': 127, 'end': 134}, {'entity_group': 'EMA', 'score': n...",Germany,"['Institute for Clinical Immunology', 'Friedrich Alexander University of Erlangen-Nuremberg']","['Germany', 'Germany']"
17,14509957,"[{'Name': 'Eric Lopatta', 'Affiliation': ['Klinik für Radiologie, Abteilung für Strahlentherapie, Friedrich-Schiller-Universität Jena. eric.lopatta@med.uni-jena.de']}, {'Name': 'Susie-Maria Liesenfeld', 'Affiliation': []}, {'Name': 'Priska Bank', 'Affiliation': []}, {'Name': 'Reinhard Wurm', 'Affiliation': []}, {'Name': 'Robert Günther', 'Affiliation': []}, {'Name': 'Tilo Wiezorek', 'Affiliation': []}, {'Name': 'Thomas G Wendt', 'Affiliation': []}]","[{'entity_group': 'INS', 'score': np.float32(0.99991393), 'word': 'Klinik für Radiologie', 'start': 0, 'end': 21}, {'entity_group': 'INS', 'score': np.float32(0.9998618), 'word': 'Friedrich - Schiller - Universität Jena', 'start': 55, 'end': 90}, {'entity_group': 'EMA', 'score': np.float32(0.99992806), 'word': 'eric. lopatta @ med. uni - jena. de', 'start': 92, 'end': 120}]",Germany,"['Klinik für Radiologie', 'Friedrich-Schiller-Universität Jena']","['Germany', 'Germany']"
18,15551344,"[{'Name': 'Young-Woon Chang', 'Affiliation': ['Department of Gastroenterology, Kyung Hee University College of Medicine, Seoul, South Korea. cywgi@chollian.net']}, {'Name': 'Jae-Young Jang', 'Affiliation': []}, {'Name': 'Nam-Hoon Kim', 'Affiliation': []}, {'Name': 'Jae Won Lee', 'Affiliation': []}, {'Name': 'Hyo Jung Lee', 'Affiliation': []}, {'Name': 'Woon Won Jung', 'Affiliation': []}, {'Name': 'Seok-Ho Dong', 'Affiliation': []}, {'Name': 'Hyo-Jong Kim', 'Affiliation': []}, {'Name': 'Byung...","[{'entity_group': 'INS', 'score': np.float32(0.9998672), 'word': 'Kyung Hee University', 'start': 32, 'end': 52}, {'entity_group': 'SUBC', 'score': np.float32(0.99964917), 'word': 'Seoul', 'start': 74, 'end': 79}, {'entity_group': 'COU', 'score': np.float32(0.9991506), 'word': 'South Korea', 'start': 81, 'end': 92}, {'entity_group': 'EMA', 'score': np.float32(0.9999283), 'word': 'cywgi @ chollian. net', 'start': 94, 'end': 112}]",South Korea,['Kyung Hee University'],['South Korea']
19,15551349,"[{'Name': 'Shizuo Machida', 'Affiliation': ['Department of Obstetrics and Gynecology, Jichi Medical School, Yakushiji, Minami-kawachi, Tochigi 329-0498, Japan. smachi@jichi.ac.jp']}, {'Name': 'Yasushi Saga', 'Affiliation': []}, {'Name': 'Yuji Takei', 'Affiliation': []}, {'Name': 'Izumi Mizuno', 'Affiliation': []}, {'Name': 'Takeshi Takayama', 'Affiliation': []}, {'Name': 'Takahiro Kohno', 'Affiliation': []}, {'Name': 'Ryo Konno', 'Affiliation': []}, {'Name': 'Michitaka Ohwada', 'Affiliation'...","[{'entity_group': 'INS', 'score': np.float32(0.99987555), 'word': 'Jichi Medical School', 'start': 41, 'end': 61}, {'entity_group': 'SUBC', 'score': np.float32(0.9994369), 'word': 'Yakushiji', 'start': 63, 'end': 72}, {'entity_group': 'SUBC', 'score': np.float32(0.99955195), 'word': 'Minami - kawachi', 'start': 74, 'end': 88}, {'entity_group': 'SUBC', 'score': np.float32(0.9997646), 'word': 'Tochigi', 'start': 90, 'end': 97}, {'entity_group': 'COU', 'score': np.float32(0.99949646), 'word': '...",Japan,['Jichi Medical School'],['Japan']

In [313]:
from collections import OrderedDict
import psycopg2
import pandas as pd
import ast
import re
from tqdm import tqdm

# -----------------------
# CACHE (LRU size = 1000)
# -----------------------
CACHE_SIZE = 1000
institution_cache = OrderedDict()

# -----------------------
# PRE-CREATE RESULT COLUMNS
# -----------------------
df_new['Institutions_db_id'] = [[] for _ in range(len(df_new))]
df_new['Institutions_db_name'] = [[] for _ in range(len(df_new))]
df_new['Institutions_db_country'] = [[] for _ in range(len(df_new))]
df_new['Unmatched_INS'] = [[] for _ in range(len(df_new))]

# -----------------------
# DB CONNECTION
# -----------------------
connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)

cursor = connection.cursor()
cursor.execute("SET pg_trgm.similarity_threshold = 0.6")

# -----------------------
# LOAD DATABASE TABLES INTO MEMORY
# -----------------------
print("Loading institution_names...")
cursor.execute("SELECT institution_id, name FROM institution_names")
rows = cursor.fetchall()
name_index = {}
for inst_id, name in rows:
    name_index.setdefault(name, []).append((inst_id, name))

print("Loading institution_locations...")
cursor.execute("""
    SELECT institution_id, city_name, country_name, subdivision_name
    FROM institution_locations
""")
rows = cursor.fetchall()
location_index = {r[0]: (r[1], r[2], r[3]) for r in rows}

print("Loading institution_relationships...")
cursor.execute("""
    SELECT child_institution_id, parent_institution_id
    FROM institution_relationships
""")
rows = cursor.fetchall()
relationship_index = set()
for child_id, parent_id in rows:
    relationship_index.add((child_id, parent_id))
    relationship_index.add((parent_id, child_id))

print("Indices loaded.")

# -----------------------
# MAIN LOOP
# -----------------------
for row in tqdm(range(len(df_new))):

    if pd.isna(df_new.at[row, "NER_BERT"]):
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df_new.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = {ner.get('word') for ner in ner_results if ner.get('entity_group') == 'SUBC'}
    cou_ner_results = {ner.get('word') for ner in ner_results if ner.get('entity_group') == 'COU'}

    # -----------------------
    # EXTRACT UNIQUE INS
    # -----------------------
    seen_queries = set()
    ins_queries = []

    for ner in ner_results:
        if ner.get('entity_group') != 'INS':
            continue
        query = ner.get('word')
        if query == "Harvard":
            query = "Harvard University"
        query = query.replace("’", "'").replace(" ' s", "'s").strip()
        if query not in seen_queries:
            seen_queries.add(query)
            ins_queries.append(query)

    found_institutions = []
    unmatched_queries = []

    # -----------------------
    # PROCESS EACH QUERY
    # -----------------------
    for query in ins_queries:

        matched = False  # Track whether this query was successfully resolved
        resolved = []

        # -----------------------
        # CACHE LOOKUP
        # -----------------------
        if query in institution_cache:
            ids, names, countries = institution_cache[query]
            for inst in zip(ids, names, countries):
                found_institutions.append(inst)
            institution_cache.move_to_end(query)
            matched = True
            continue

        # -----------------------
        # EXACT MATCH
        # -----------------------
        records_exact = name_index.get(query, [])
        candidates = {r[0]: r[1] for r in records_exact}

        # =========================
        # EXACT MATCH: ONE
        # =========================
        if len(candidates) == 1:
            inst_id = next(iter(candidates))
            location = location_index.get(inst_id)
            if location:
                city, country, subdivision = location
                if (cou_ner_results or subc_ner_results):
                    if country in cou_ner_results or city in subc_ner_results or subdivision in subc_ner_results:
                        resolved.append((inst_id, candidates[inst_id], country))
                        matched = True
                else:
                    resolved.append((inst_id, candidates[inst_id], country))
                    matched = True

        # =========================
        # EXACT MATCH: MULTIPLE
        # =========================
        elif len(candidates) > 1:
            candidate_ids = list(candidates.keys())
            location_map = {inst_id: location_index.get(inst_id) for inst_id in candidate_ids if inst_id in location_index}

            # Step 1: Filter candidates by location match
            location_matches = []
            for inst_id, inst_name in candidates.items():
                loc = location_map.get(inst_id)
                if not loc:
                    continue
                city, country, subdivision = loc
                if country in cou_ner_results or city in subc_ner_results or subdivision in subc_ner_results:
                    location_matches.append((inst_id, inst_name, country))

            # Step 2: Resolve if exactly one match
            if len(location_matches) == 1:
                resolved.append(location_matches[0])
                matched = True

            # Step 3: Multiple matches: use relationship
            elif len(location_matches) > 1:
                found = False
                for i, (inst_id_i, name_i, country_i) in enumerate(location_matches):
                    for j, (inst_id_j, name_j, country_j) in enumerate(location_matches):
                        if i == j:
                            continue
                        if (inst_id_i, inst_id_j) in relationship_index:
                            resolved.append((inst_id_i, name_i, country_i))
                            matched = True
                            found = True
                            break
                    if found:
                        break

        # =========================
        # FUZZY SEARCH
        # =========================
        elif len(candidates) == 0:
            cursor.execute(
                """
                SELECT institution_id, name, similarity(name, %s) AS sim
                FROM institution_names
                WHERE name %% %s
                AND similarity(name, %s) >= 0.6
                ORDER BY sim DESC
                LIMIT 10
                """,
                (query, query, query)
            )
            records_fuzzy = cursor.fetchall()
            candidates_fuzzy = {r[0]: r[1] for r in records_fuzzy}
            candidate_ids = list(candidates_fuzzy.keys())
            location_map = {inst_id: location_index[inst_id] for inst_id in candidate_ids if inst_id in location_index}

            matching_candidates = []
            for inst_id, inst_name in candidates_fuzzy.items():
                if inst_id not in location_map:
                    continue
                city, country, subdivision = location_map[inst_id]
                if country in cou_ner_results or city in subc_ner_results or subdivision in subc_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

            # Accept if one location match
            if len(matching_candidates) == 1:
                resolved.append(matching_candidates[0])
                matched = True

            # FALLBACK
            elif len(candidates_fuzzy) > 0:
                matching_ids = [inst_id for inst_id, _, _ in matching_candidates]
                deduped = {}
                for inst_id, name, sim in records_fuzzy:
                    if inst_id not in matching_ids:
                        continue
                    if inst_id not in deduped or sim > deduped[inst_id][1]:
                        deduped[inst_id] = (name, sim)

                if len(deduped) > 0:
                    deduped_sorted = sorted(deduped.items(), key=lambda x: x[1][1], reverse=True)
                    top_id, (top_name, top_sim) = deduped_sorted[0]
                    second_sim = deduped_sorted[1][1][1] if len(deduped_sorted) > 1 else None
                    sim_gap = top_sim - second_sim if second_sim is not None else 0
                    location = location_index.get(top_id)
                    if location:
                        city, country, subdivision = location
                        location_match = country in cou_ner_results or city in subc_ner_results or subdivision in subc_ner_results

                        # STANDARD ACCEPTANCE
                        if top_sim >= 0.6 and (location_match or sim_gap >= 0.2):
                            resolved.append((top_id, top_name, country))
                            matched = True

                        # ACCEPT BASED ON SIM DISTANCE
                        elif second_sim is not None and sim_gap < 0.2 and location_match:
                            second_id = deduped_sorted[1][0]
                            if (top_id, second_id) in relationship_index:
                                resolved.append((top_id, top_name, country))
                                matched = True

                        # ALL RELATED -> PICK PARENT
                        elif len(deduped_sorted) > 1:
                            all_ids = [inst_id for inst_id, _ in deduped_sorted]
                            all_related = all(
                                (all_ids[i], all_ids[j]) in relationship_index
                                for i in range(len(all_ids))
                                for j in range(i + 1, len(all_ids))
                            )
                            if all_related:
                                parent_id = None
                                for cid in all_ids:
                                    for pid in all_ids:
                                        if (cid, pid) in relationship_index and cid != pid:
                                            parent_id = pid
                                            break
                                    if parent_id:
                                        break
                                if parent_id:
                                    parent_name = name_index.get(parent_id, [(None,)])[0][0]
                                    parent_loc = location_index.get(parent_id)
                                    parent_country = parent_loc[1] if parent_loc else None
                                    resolved.append((parent_id, parent_name, parent_country))
                                    matched = True

        # -----------------------
        # CACHE OR UNMATCHED
        # -----------------------
        if resolved:
            ids, names, countries = zip(*resolved)
            institution_cache[query] = (list(ids), list(names), list(countries))
            if len(institution_cache) > CACHE_SIZE:
                institution_cache.popitem(last=False)
            for inst in resolved:
                found_institutions.append(inst)

        if not matched:
            unmatched_queries.append(query)

    # -----------------------
    # WRITE RESULTS
    # -----------------------
    if found_institutions:
        unique_dict = {}
        for inst_id, inst_name, country in found_institutions:
            if inst_id not in unique_dict:
                unique_dict[inst_id] = (inst_name, country)
        ids = list(unique_dict.keys())
        names = [v[0] for v in unique_dict.values()]
        countries = [v[1] for v in unique_dict.values()]
        df_new.at[row, 'Institutions_db_id'] = ids
        df_new.at[row, 'Institutions_db_name'] = names
        df_new.at[row, 'Institutions_db_country'] = countries

    if unmatched_queries:
        df_new.at[row, 'Unmatched_INS'] = unmatched_queries

# -----------------------
# CLOSE CONNECTION
# -----------------------
cursor.close()
connection.close()

Loading institution_names...
Loading institution_locations...
Loading institution_relationships...
Indices loaded.

100%|████████████████████████████████████████████████████████████████████████████████| 102/102 [00:05<00:00, 19.84it/s]

In [314]:
df_new[["Institutions_man", "Institutions_db_name"]]

,Institutions_man,Institutions_db_name
0,"['Florida Cancer Specialists and Research Institute', 'RCR Genetics', 'Clemson University']","[Florida Cancer Specialists & Research Institute, Clemson University]"
1,"[""Children's Hospital of Philadelphia"", 'University of Pennsylvania']","[University of Pennsylvania, Children's Hospital of Philadelphia]"
2,"['Molecular Biology Research Center', 'Biomedicine Technologies Institute', 'Baqiyatallah University of Medical Sciences', 'Applied Virology Research Center', 'Research Institute of Petroleum Industry (RIPI)']",[Baqiyatallah University of Medical Sciences]
3,"['Shahed University', 'Cellular and Molecular Research Center', 'Ahvaz Jundishapur University of Medical Sciences', 'Biotechnology Research Center', 'Medical Biology Research Center', 'Health Technology Institute', 'Kermanshah University of Medical Sciences', 'Abadan University of Medical Sciences']","[Abadan University of Medical Sciences, Shahed University, Biotechnology Research Center, Kermanshah University of Medical Sciences, Ahvaz Jundishapur University of Medical Sciences]"
4,"['Abramson Family Cancer Research Institute', 'University of Pennsylvania']","[University of Pennsylvania, Abramson Cancer Institute]"
5,"['University of California', 'Center of Immunotherapy and Immunity', ""Seattle Children's Research Institute"", 'Molecular Engineering and Science Institute', 'University of Washington', 'Brotman-Baty Institute for Precision Medicine', 'Molecular Biology Institute', 'Jonsson Comprehensive Cancer Center', 'Brain Research Institute', 'Eli and Edythe Broad Center of Regenerative Medicine and Stem Cell Research', 'Partillion Bioscience Corporation', 'California NanoSystems Institute (CNSI)']","[University of Washington, University of California, Los Angeles, California NanoSystems Institute, Jonsson Comprehensive Cancer Center]"
6,NaN,[]
7,"['Kao Autoimmunity Institute', 'Cedars-Sinai Medical Center', 'University of California', 'Samuel Oschin Comprehensive Cancer Institute']","[Cedars-Sinai Medical Center, University of California, Riverside]"
8,"['University of Cyprus', 'National and Kapodistrian University of Athens', ""'Aghia Sophia' Children's Hospital"", 'Center of Clinical, Experimental Surgery and Translational Research', 'Biomedical Research Foundation', 'Academy of Athens', 'NICHD', 'NIH']",[NICHD]
9,"['Oregon State University', 'Oregon Health & Sciences University']",[Oregon State University]
10,['UMDNJ'],[]
11,['Biometric Centre in Therapeutic Studies'],[]
12,['Aichi Cancer Center Research Institute'],[]
13,"['Paterson Institute for Cancer Research', 'Christie CRC Research Centre']",[Paterson Institute for Cancer Research]
14,['University of Texas Health Science Center'],[]
15,['Karolinska Institute & Hospital'],[Karolinska Institutet]
16,"['Institute for Clinical Immunology', 'Friedrich Alexander University of Erlangen-Nuremberg']","[Institute of Clinical Neuroimmunology, University of Erlangen-Nuremberg]"
17,"['Klinik für Radiologie', 'Friedrich-Schiller-Universität Jena']",[]
18,['Kyung Hee University'],[Kyung Hee University]
19,['Jichi Medical School'],[]
20,"['National University Corporation', 'University of Toyama']","[National University Corporation Tottori University, University of Toyama]"
21,"['Academy of Medical Sciences and Technology', 'Academy Charity Teaching Hospital']",[University of Medical Sciences and Technology]
22,"['Clinical Center for Tumor Therapy', '2nd Affiliated Hospital', 'Institute of Ultrasonic Engineering in Medicine', 'Chongqing University of Medical Sciences']",[Chongqing University of Medical Sciences]
23,['Niigata University'],[Niigata University]
24,['National Tuberculosis and Lung Diseases Research Institute'],[]
25,['Radboud University Nijmegen Medical Centre'],[Radboud University Nijmegen Medical Centre]
26,"['Stem Cell Research Center', 'Korea Research Institute of Bioscience and Biotechnology']",[Korea Research Institute of Bioscience and Biotechnology]
27,['Wooridul Spine Hospital'],[Wooridul Hospital]
28,['University of Veterinary Medicine'],[]
29,['University of Applied Sciences'],[]
30,"['Guangdong Lung Cancer Institute', 'Guangdong General Hospital', 'Guangdong Academy of Medical Sciences']","[Guangdong General Hospital, Guangdong Academy of Medical Sciences]"
31,"['Shanghai Chest Hospital', 'Shanghai Jiaotong University']","[Shanghai Chest Hospital, Shanghai Jiaotong University]"
32,['National University Hospital'],[National University Hospital]
33,['Boston University Medical Center'],[]
34,['Semmelweis University'],[Semmelweis University]
35,"['Clinic of Transplantation and Surgery', 'Semmelweis University']",[Semmelweis University]
36,['Georgia Health Sciences University'],[]
37,['University of Sydney'],[University of Sydney]
38,"['Haartman Institute', 'University of Helsinki', 'Helsinki University Central Hospital']","[University of Helsinki, Helsinki University Hospital]"
39,['Kyung Hee University'],[Kyung Hee University]
40,"['Comissão de Controle de Infecção Hospitalar', 'Hospital das Clínicas', 'Universidade de São Paulo']",[]
41,['Johns Hopkins University'],[Johns Hopkins University]
42,"['Erasmus MC Cancer Institute', 'Radboud University Nijmegen Medical Center']","[Radboud University Nijmegen Medical Centre, Erasmus MC Cancer Institute]"
43,"['China Medical University Hospital', 'Taipei Medical University', 'China Medical University', 'Chi-Mei Hospital', 'Taipei Medical University Hospital']","[China Medical University Hospital, China Medical University, Taipei Medical University Hospital, Taipei Medical University, Chi Mei Hospital]"
44,"['Nanjing First Hospital', 'Nanjing Medical University']","[Nanjing Chest Hospital, Nanjing Medical University]"
45,['Tumor Hospital'],[Jilin Province Tumor Hospital]
46,NaN,[]
47,NaN,[]
48,"['Zahedan University of Medical Sciences', 'Cellular and Molecular Research Center', 'Genetic of non-communicable disease research Center', 'University of Manitoba']","[Zahedan University of Medical Sciences, University of Manitoba]"
49,"['Payame Noor University', 'Shahid Beheshti University of Medical Sciences', 'Pediatric Infections Research Center', 'Mofid Children Hospital', 'Zabol University of Medical Sciences']","[Zabol University of Medical Sciences, Payame Noor University]"
50,NaN,[]
51,NaN,[]
52,"['Hospital for Sick Children', 'University of Toronto', 'Research Institute', 'Princess Margaret Hospital']","[Hospital for Sick Children, University of Toronto, Princess Margaret Hospital]"
53,['University of Kansas'],[University of Kansas]
54,NaN,[]
55,NaN,[]
56,"['St John of God Hospital', ""St Vincent's Hospital"", 'University of Melbourne', 'Olivia Newton-John Cancer Research Institute', 'La Trobe University', 'Peter MacCallum Cancer Centre']","[St John of God Hospital, St Vincent's Hospital, Peter MacCallum Cancer Centre, University of Melbourne, La Trobe University]"
57,"['Seoul National University Hospital', 'SMG-SNU Boramae Medical Center', 'Kyunghee University Hospital', 'Seoul National University']","[Boramae Medical Center, Seoul National University Hospital, Seoul National University, Kyung Hee University Dental Hospital]"
58,NaN,[]
59,NaN,[]
60,['Shiraz University of Medical Sciences'],[Shiraz University of Medical Sciences]
61,['Hamadan University of Medical Sciences'],[Hamedan University of Medical Sciences]
62,"['Capital Medical University Cancer Center', 'Beijing Shijitan Hospital', 'Beijing Institute of Biotechnology', 'Jilin University']","[Jilin University, Beijing Institute of Technology, Capital Medical University, Beijing Shijitan Hospital]"
63,"['Bakirkoy Dr. Sadi Konuk Education and Research Hospital', 'Gazi University', 'Akdeniz University', 'Ankara Numune Education and Research Hospital']","[Akdeniz University, Gazi University]"
64,"['Nicolaus Copernicus University', 'Kuyavian and Pomeranian Pulmonology Centre']","[WSNoZ Bydgoszcz, Nicolaus Copernicus University]"
65,"[""King's College London"", 'Global Health Institute', 'American University of Beirut', 'London School of Hygiene and Tropical Medicine', 'Institute of Cancer Policy']","[King's College London, George Institute for Global Health, American University of Beirut]"
66,"['Shanghai University', 'Fudan Institute of Urology', 'Fudan University']","[Shanghai University, Fudan University]"
67,"['Sapienza University of Rome', 'Istituto Pasteur Italia', 'Fondazione Cenci Bolognetti', 'Regina Elena National Cancer Institute', ""University G. d'Annunzio""]","[Sapienza University of Rome, Universitat Gabriele d'Annunzio]"
68,"['Danish Cancer Society Research Center', 'Center for Autophagy, Recycling and Disease', 'University of Copenhagen', 'Novo Nordisk Foundation Center for Protein Research']","[University of Copenhagen, NovoNordisk Foundation Center for Basic Metabolic Research, Danish Cancer Society]"
69,"['Sarah W. Stedman Nutrition and Metabolism Center', 'Duke University Medical Center', 'Duke Molecular Physiology Institute', 'Genomics Institute of the Novartis Research Foundation']","[Duke University Medical Center, Rare Genomics Institute]"
70,"['Tongji Hospital', 'Huazhong University of Science and Technology']","[Tongji Hospital, Huazhong University of Science and Technology]"
71,['Sichuan University'],[Sichuan University]
72,"['Indiana University', 'Purdue University', 'Center for Health Services Research', 'Regenstrief Institute, Inc.']",[Regenstrief Institute]
73,"[""Zengcheng District People's Hospital"", 'BoJi-Affiliated Hospital', 'Sun Yat-sen University', 'Sun Yat-sen Memorial Hospital']","[Sun Yat-sen Memorial Hospital, Sun Yat-sen University, Wangcheng District People's Hospital, 8th Affiliated Hospital of Sun Yat-sen University]"
74,"['Institute of Antibody Engineering', 'Southern Medical University', ""First People's Hospital"", 'Sun Yat-Sen Memorial Hospital', 'Sun Yat-Sen University', 'Guangzhou Darui Biotechnology Co., Ltd.']","[Hunan Institute of Engineering, Southern Medical University, First People's Hospital of Foshan, Sun Yat-sen Memorial Hospital, Sun Yat-sen University]"
75,"['Southwest Hospital', 'Army Medical University', 'Third Military Medical University']","[Southwest Hospital, Army Medical University]"
76,"['First Affiliated Hospital', ""Xi'an Jiaotong University""]",[]
77,"['National Cancer Institute', 'University of California', 'Stanford University']","[National Cancer Institute, University of California, Riverside]"
78,['Wake Forest University'],[Wake Forest University]
79,['UCLA'],[]
80,"['Center for Artificial Intelligence in Drug Discovery', 'Case Western Reserve University', 'Center for Science, Health, and Society', 'Center for Clinical Informatics Research and Education', 'MetroHealth System', 'Case Comprehensive Cancer Center']","[Case Western Reserve University, Case Comprehensive Cancer Center, MetroHealth]"
81,NaN,[]
82,"['Zhengzhou University', 'Research Center for Eco-Environmental Sciences', 'Chinese Academy of Sciences', 'Beijing drainage group research center', 'Beijing Municipal Sewage Recycling Engineering Technology Research Center']","[Tianjin Academy of Environmental Sciences, Zhengzhou University, Research Center for Eco-Environmental Sciences, Chinese Academy of Sciences]"
83,"['Anhui Medical University', 'Ministry of Education', 'First Affiliated Hospital', 'Anhui Provincial Cancer Institute']","[Anhui Medical University, State Council of the People's Republic of China, First Affiliated Hospital of Anhui Medical University, NHC, China CDC]"
84,"['University of New Mexico', ""St. Jude Children's Research Hospital"", 'University of Texas Health Science Center']","[St. Jude Children's Research Hospital, University of New Mexico]"
85,"['Shanghai Public Health Clinical Center', 'Fudan University']","[Shanghai Public Health Clinical Center, Fudan University]"
86,"[""Peking University People's Hospital"", 'Peking University International Hospital']","[Peking University People's Hospital, Peking University International Hospital]"
87,"['Icahn School of Medicine at Mount Sinai', 'Tisch Cancer Institute']","[Tisch Cancer Institute, Mount Sinai Queens]"
88,"['University Hospital Brussels', 'University Hospitals Leuven']",[University Hospital Brussels]
89,"['iBiMED-Institute of Biomedicine and Department of Medical Science', 'University of Aveiro', 'University of Porto']","[University of Porto, University of Aveiro]"
90,"['Munich Institute of Biomedical Engineering', 'Technical University of Munich', 'Institute of Virology', 'German Cancer Research Center (DKFZ)', 'German Center for Infection Research (DZIF)']","[Technical University of Munich, German Cancer Research Center, German Center for Infection Research]"
91,"['Biomedical Research Imaging Center', 'UNC Lineberger Comprehensive Cancer Center', 'University of North Carolina', 'LED Radiofluidics Corp.']","[Pennington Biomedical Research Center, UNC Lineberger Comprehensive Cancer Center, University of North Carolina System]"
92,NaN,[]
93,NaN,[]
94,['National Cancer Center Hospital'],[]
95,['Memorial Sloan-Kettering Cancer Center'],[Memorial Sloan Kettering Cancer Center]
96,"['Tampere University Hospital', 'University of Tampere']","[Tampere University Hospital, University of Tampere]"
97,NaN,[]
98,"['Cancer Research Institute', 'Tohoku College of Pharmaceutical Sciences']",[]
99,['Oita Medical University'],[Oita University]
100,['University of Kentucky'],[University of Kentucky]
101,"['Ludwig Institute for Cancer Research', 'Centre Hospitalier Universitaire Vaudois']","[Ludwig Institute for Cancer Research, Centre Hospitalier Universitaire Vaudois]"

In [316]:
df_new[["Institutions_man", "Institutions_db_name", "Countries_man", "Unmatched_INS"]]

,Institutions_man,Institutions_db_name,Countries_man,Unmatched_INS
0,"['Florida Cancer Specialists and Research Institute', 'RCR Genetics', 'Clemson University']","[Florida Cancer Specialists & Research Institute, Clemson University]","['United States', 'United States', 'United States']",[RCR Genetics]
1,"[""Children's Hospital of Philadelphia"", 'University of Pennsylvania']","[University of Pennsylvania, Children's Hospital of Philadelphia]","['United States', 'United States']",[]
2,"['Molecular Biology Research Center', 'Biomedicine Technologies Institute', 'Baqiyatallah University of Medical Sciences', 'Applied Virology Research Center', 'Research Institute of Petroleum Industry (RIPI)']",[Baqiyatallah University of Medical Sciences],"['Iran', 'Iran', 'Iran', 'Iran', 'Iran']","[Applied Virology Research Center, Biomedicine Technologies Institute, Molecular Biology Research Center]"
3,"['Shahed University', 'Cellular and Molecular Research Center', 'Ahvaz Jundishapur University of Medical Sciences', 'Biotechnology Research Center', 'Medical Biology Research Center', 'Health Technology Institute', 'Kermanshah University of Medical Sciences', 'Abadan University of Medical Sciences']","[Abadan University of Medical Sciences, Shahed University, Biotechnology Research Center, Kermanshah University of Medical Sciences, Ahvaz Jundishapur University of Medical Sciences]","['Iran', 'Iran', 'Iran', 'Iran', 'Iran', 'Iran', 'Iran', 'Iran']","[Research Institute of Petroleum Industry ( RIPI ), Medical Biology Research Center, Health Technology Institute, Cellular and Molecular Research Center]"
4,"['Abramson Family Cancer Research Institute', 'University of Pennsylvania']","[University of Pennsylvania, Abramson Cancer Institute]","['United States', 'United States']",[Family Cancer Research]
5,"['University of California', 'Center of Immunotherapy and Immunity', ""Seattle Children's Research Institute"", 'Molecular Engineering and Science Institute', 'University of Washington', 'Brotman-Baty Institute for Precision Medicine', 'Molecular Biology Institute', 'Jonsson Comprehensive Cancer Center', 'Brain Research Institute', 'Eli and Edythe Broad Center of Regenerative Medicine and Stem Cell Research', 'Partillion Bioscience Corporation', 'California NanoSystems Institute (CNSI)']","[University of Washington, University of California, Los Angeles, California NanoSystems Institute, Jonsson Comprehensive Cancer Center]","['United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States']","[University of California, Molecular Engineering and Science Institute, Center of Immunotherapy and Immunity, Seattle Children's Research Institute, Molecular Biology Institute, Brain Research Institute, Eli and Edythe Broad Center of Regenerative Medicine and Stem Cell Research, Brotman - Baty Institute for Precision Medicine, Partillion Bioscience Corporation]"
6,NaN,[],NaN,[]
7,"['Kao Autoimmunity Institute', 'Cedars-Sinai Medical Center', 'University of California', 'Samuel Oschin Comprehensive Cancer Institute']","[Cedars-Sinai Medical Center, University of California, Riverside]","['United States', 'United States', 'United States', 'United States']","[Samuel Oschin Comprehensive Cancer Institute, Kao Autoimmunity Institute]"
8,"['University of Cyprus', 'National and Kapodistrian University of Athens', ""'Aghia Sophia' Children's Hospital"", 'Center of Clinical, Experimental Surgery and Translational Research', 'Biomedical Research Foundation', 'Academy of Athens', 'NICHD', 'NIH']",[NICHD],"['Cyprus', 'Greece', 'Greece', 'Greece', 'Greece', 'Greece', 'United States', 'United States']","[National and Kapodistrian University of Athens, "" Aghia Sophia "" Children's Hospital, of Clinical, Experimental Surgery and Translational Research, Biomedical Research Foundation of the Academy of Athens, NIH Bethesda, University of Cyprus]"
9,"['Oregon State University', 'Oregon Health & Sciences University']",[Oregon State University],"['United States', 'United States']",[Oregon Health & Sciences University]
10,['UMDNJ'],[],['United States'],"[UMDNJ, Robert Wood Johnson Medical School]"
11,['Biometric Centre in Therapeutic Studies'],[],['Germany'],[Biometric Centre in Therapeutic Studies]
12,['Aichi Cancer Center Research Institute'],[],['Japan'],[Aichi Cancer Center Research Institute]
13,"['Paterson Institute for Cancer Research', 'Christie CRC Research Centre']",[Paterson Institute for Cancer Research],"['United Kingdom', 'United Kingdom']",[Christie CRC Research Centre]
14,['University of Texas Health Science Center'],[],['United States'],[University of Texas Health Science Center at San Antonio]
15,['Karolinska Institute & Hospital'],[Karolinska Institutet],['Sweden'],[]
16,"['Institute for Clinical Immunology', 'Friedrich Alexander University of Erlangen-Nuremberg']","[Institute of Clinical Neuroimmunology, University of Erlangen-Nuremberg]","['Germany', 'Germany']",[]
17,"['Klinik für Radiologie', 'Friedrich-Schiller-Universität Jena']",[],"['Germany', 'Germany']","[Klinik für Radiologie, Friedrich - Schiller - Universität Jena]"
18,['Kyung Hee University'],[Kyung Hee University],['South Korea'],[]
19,['Jichi Medical School'],[],['Japan'],[Jichi Medical School]
20,"['National University Corporation', 'University of Toyama']","[National University Corporation Tottori University, University of Toyama]","['Japan', 'Japan']",[]
21,"['Academy of Medical Sciences and Technology', 'Academy Charity Teaching Hospital']",[University of Medical Sciences and Technology],"['Sudan', 'Sudan']",[Academy Charity Teaching Hospital]
22,"['Clinical Center for Tumor Therapy', '2nd Affiliated Hospital', 'Institute of Ultrasonic Engineering in Medicine', 'Chongqing University of Medical Sciences']",[Chongqing University of Medical Sciences],"['China', 'China', 'China', 'China']","[Clinical Center for Tumor Therapy, 2nd Affiliated Hospital, Institute of Ultrasonic Engineering in Medicine]"
23,['Niigata University'],[Niigata University],['Japan'],[]
24,['National Tuberculosis and Lung Diseases Research Institute'],[],['Poland'],[National Tuberculosis and Lung Diseases Research Institute]
25,['Radboud University Nijmegen Medical Centre'],[Radboud University Nijmegen Medical Centre],['The Netherlands'],[]
26,"['Stem Cell Research Center', 'Korea Research Institute of Bioscience and Biotechnology']",[Korea Research Institute of Bioscience and Biotechnology],"['South Korea', 'South Korea']",[Stem Cell Research Center]
27,['Wooridul Spine Hospital'],[Wooridul Hospital],['South Korea'],[]
28,['University of Veterinary Medicine'],[],['Germany'],[University of Veterinary Medicine]
29,['University of Applied Sciences'],[],['Switzerland'],[University of Applied Sciences]
30,"['Guangdong Lung Cancer Institute', 'Guangdong General Hospital', 'Guangdong Academy of Medical Sciences']","[Guangdong General Hospital, Guangdong Academy of Medical Sciences]","['China', 'China', 'China']",[Guangdong Lung Cancer Institute]
31,"['Shanghai Chest Hospital', 'Shanghai Jiaotong University']","[Shanghai Chest Hospital, Shanghai Jiaotong University]","['China', 'China']",[]
32,['National University Hospital'],[National University Hospital],['Singapore'],[]
33,['Boston University Medical Center'],[],['United States'],[Boston University Medical Center]
34,['Semmelweis University'],[Semmelweis University],['Hungary'],[]
35,"['Clinic of Transplantation and Surgery', 'Semmelweis University']",[Semmelweis University],"['Hungary', 'Hungary']",[]
36,['Georgia Health Sciences University'],[],['United States'],[Georgia Health Sciences University]
37,['University of Sydney'],[University of Sydney],['Australia'],[]
38,"['Haartman Institute', 'University of Helsinki', 'Helsinki University Central Hospital']","[University of Helsinki, Helsinki University Hospital]","['Finland', 'Finland', 'Finland']",[Haartman Institute]
39,['Kyung Hee University'],[Kyung Hee University],['South Korea'],[]
40,"['Comissão de Controle de Infecção Hospitalar', 'Hospital das Clínicas', 'Universidade de São Paulo']",[],"['Brazil', 'Brazil', 'Brazil']","[Comissão de Controle de Infecção Hospitalar, Hospital das Clínicas, Universidade de São Paulo]"
41,['Johns Hopkins University'],[Johns Hopkins University],['United States'],[]
42,"['Erasmus MC Cancer Institute', 'Radboud University Nijmegen Medical Center']","[Radboud University Nijmegen Medical Centre, Erasmus MC Cancer Institute]","['The Netherlands', 'The Netherlands']",[]
43,"['China Medical University Hospital', 'Taipei Medical University', 'China Medical University', 'Chi-Mei Hospital', 'Taipei Medical University Hospital']","[China Medical University Hospital, China Medical University, Taipei Medical University Hospital, Taipei Medical University, Chi Mei Hospital]","['Taiwan', 'Taiwan', 'Taiwan', 'Taiwan', 'Taiwan']",[]
44,"['Nanjing First Hospital', 'Nanjing Medical University']","[Nanjing Chest Hospital, Nanjing Medical University]","['China', 'China']",[]
45,['Tumor Hospital'],[Jilin Province Tumor Hospital],['China'],[]
46,NaN,[],NaN,[]
47,NaN,[],NaN,[]
48,"['Zahedan University of Medical Sciences', 'Cellular and Molecular Research Center', 'Genetic of non-communicable disease research Center', 'University of Manitoba']","[Zahedan University of Medical Sciences, University of Manitoba]","['Iran', 'Iran', 'Iran', 'Canada']","[Zahedan University of Medical Sciences Cellular and Molecular Research Center, Zahedan University of Medical Sciences Genetic of non & mdash ; communicable disease research Center]"
49,"['Payame Noor University', 'Shahid Beheshti University of Medical Sciences', 'Pediatric Infections Research Center', 'Mofid Children Hospital', 'Zabol University of Medical Sciences']","[Zabol University of Medical Sciences, Payame Noor University]","['Iran', 'Iran', 'Iran', 'Iran', 'Iran']","[Shahid Beheshti University of Medical Sciences Pediatric Infections Research Center, Mofid Children Hospital]"
50,NaN,[],NaN,[]
51,NaN,[],NaN,[]
52,"['Hospital for Sick Children', 'University of Toronto', 'Research Institute', 'Princess Margaret Hospital']","[Hospital for Sick Children, University of Toronto, Princess Margaret Hospital]","['Canada', 'Canada', 'Canada', 'Canada']",[]
53,['University of Kansas'],[University of Kansas],['United States'],[]
54,NaN,[],NaN,[]
55,NaN,[],NaN,[]
56,"['St John of God Hospital', ""St Vincent's Hospital"", 'University of Melbourne', 'Olivia Newton-John Cancer Research Institute', 'La Trobe University', 'Peter MacCallum Cancer Centre']","[St John of God Hospital, St Vincent's Hospital, Peter MacCallum Cancer Centre, University of Melbourne, La Trobe University]","['Australia', 'Australia', 'Australia', 'Australia', 'Australia', 'Australia']",[Olivia Newton - John Cancer Research Institute]
57,"['Seoul National University Hospital', 'SMG-SNU Boramae Medical Center', 'Kyunghee University Hospital', 'Seoul National University']","[Boramae Medical Center, Seoul National University Hospital, Seoul National University, Kyung Hee University Dental Hospital]","['South Korea', 'South Korea', 'South Korea', 'South Korea']",[]
58,NaN,[],NaN,[]
59,NaN,[],NaN,[]
60,['Shiraz University of Medical Sciences'],[Shiraz University of Medical Sciences],['Iran'],[]
61,['Hamadan University of Medical Sciences'],[Hamedan University of Medical Sciences],['Iran'],[]
62,"['Capital Medical University Cancer Center', 'Beijing Shijitan Hospital', 'Beijing Institute of Biotechnology', 'Jilin University']","[Jilin University, Beijing Institute of Technology, Capital Medical University, Beijing Shijitan Hospital]","['China', 'China', 'China', 'China']",[]
63,"['Bakirkoy Dr. Sadi Konuk Education and Research Hospital', 'Gazi University', 'Akdeniz University', 'Ankara Numune Education and Research Hospital']","[Akdeniz University, Gazi University]","['Türkiye', 'Türkiye', 'Türkiye', 'Türkiye']","[Ankara Numune Education and Research Hospital, Bakirkoy Dr. Sadi Konuk Education and Research Hospital]"
64,"['Nicolaus Copernicus University', 'Kuyavian and Pomeranian Pulmonology Centre']","[WSNoZ Bydgoszcz, Nicolaus Copernicus University]","['Poland', 'Poland']",[Kuyavian and Pomeranian Pulmonology Centre]
65,"[""King's College London"", 'Global Health Institute', 'American University of Beirut', 'London School of Hygiene and Tropical Medicine', 'Institute of Cancer Policy']","[King's College London, George Institute for Global Health, American University of Beirut]","['United Kingdom', 'Lebanon', 'Lebanon', 'United Kingdom', 'United Kingdom']",[Institute of Cancer Policy]
66,"['Shanghai University', 'Fudan Institute of Urology', 'Fudan University']","[Shanghai University, Fudan University]","['China', 'China', 'China']",[Fudan Institute of Urology]
67,"['Sapienza University of Rome', 'Istituto Pasteur Italia', 'Fondazione Cenci Bolognetti', 'Regina Elena National Cancer Institute', ""University G. d'Annunzio""]","[Sapienza University of Rome, Universitat Gabriele d'Annunzio]","['Italy', 'Italy', 'Italy', 'Italy', 'Italy']","[Regina Elena National Cancer Institute, Istituto Pasteur Italia - Fondazione Cenci Bolognetti]"
68,"['Danish Cancer Society Research Center', 'Center for Autophagy, Recycling and Disease', 'University of Copenhagen', 'Novo Nordisk Foundation Center for Protein Research']","[University of Copenhagen, NovoNordisk Foundation Center for Basic Metabolic Research, Danish Cancer Society]","['Denmark', 'Denmark', 'Denmark', 'Denmark']","[Center for Autophagy, Recycling and Disease]"
69,"['Sarah W. Stedman Nutrition and Metabolism Center', 'Duke University Medical Center', 'Duke Molecular Physiology Institute', 'Genomics Institute of the Novartis Research Foundation']","[Duke University Medical Center, Rare Genomics Institute]","['United States', 'United States', 'United States', 'United States']","[Sarah W. Stedman Nutrition and Metabolism Center, Duke Molecular Physiology Institute, Novartis Research Foundation]"
70,"['Tongji Hospital', 'Huazhong University of Science and Technology']","[Tongji Hospital, Huazhong University of Science and Technology]","['China', 'China']",[]
71,['Sichuan University'],[Sichuan University],['China'],"[Department of Lung Cancer Center, West China Hospital]"
72,"['Indiana University', 'Purdue University', 'Center for Health Services Research', 'Regenstrief Institute, Inc.']",[Regenstrief Institute],"['United States', 'United States', 'United States', 'United States']","[Indiana University, Purdue University, Center for Health Services Research]"
73,"[""Zengcheng District People's Hospital"", 'BoJi-Affiliated Hospital', 'Sun Yat-sen University', 'Sun Yat-sen Memorial Hospital']","[Sun Yat-sen Memorial Hospital, Sun Yat-sen University, Wangcheng District People's Hospital, 8th Affiliated Hospital of Sun Yat-sen University]","['China', 'China', 'China', 'China']",[BoJi - Affiliated Hospital]
74,"['Institute of Antibody Engineering', 'Southern Medical University', ""First People's Hospital"", 'Sun Yat-Sen Memorial Hospital', 'Sun Yat-Sen University', 'Guangzhou Darui Biotechnology Co., Ltd.']","[Hunan Institute of Engineering, Southern Medical University, First People's Hospital of Foshan, Sun Yat-sen Memorial Hospital, Sun Yat-sen University]","['China', 'China', 'China', 'China', 'China', 'China']","[Guangzhou Darui Biotechnology Co., Ltd., Guangzhou XGene Co., Ltd.]"
75,"['Southwest Hospital', 'Army Medical University', 'Third Military Medical University']","[Southwest Hospital, Army Medical University]","['China', 'China', 'China']",[]
76,"['First Affiliated Hospital', ""Xi'an Jiaotong University""]",[],"['China', 'China']","[First Affiliated Hospital, Xi ' an Jiaotong University]"
77,"['National Cancer Institute', 'University of California', 'Stanford University']","[National Cancer Institute, University of California, Riverside]","['United States', 'United States', 'United States']",[Stanford University]
78,['Wake Forest University'],[Wake Forest University],['United States'],[]
79,['UCLA'],[],['United States'],[UCLA]
80,"['Center for Artificial Intelligence in Drug Discovery', 'Case Western Reserve University', 'Center for Science, Health, and Society', 'Center for Clinical Informatics Research and Education', 'MetroHealth System', 'Case Comprehensive Cancer Center']","[Case Western Reserve University, Case Comprehensive Cancer Center, MetroHealth]","['United States', 'United States', 'United States', 'United States', 'United States', 'United States']","[Center for Artificial Intelligence in Drug Discovery, Center for Science, Health, and Society, Center for Clinical Informatics Research and Education]"
81,NaN,[],NaN,[]
82,"['Zhengzhou University', 'Research Center for Eco-Environmental Sciences', 'Chinese Academy of Sciences', 'Beijing drainage group research center', 'Beijing Municipal Sewage Recycling Engineering Technology Research Center']","[Tianjin Academy of Environmental Sciences, Zhengzhou University, Research Center for Eco-Environmental Sciences, Chinese Academy of Sciences]","['China', 'China', 'China', 'China', 'China']","[Beijing drainage group research center, Beijing Municipal Sewage Recycling Engineering Technology Research Center]"
83,"['Anhui Medical University', 'Ministry of Education', 'First Affiliated Hospital', 'Anhui Provincial Cancer Institute']","[Anhui Medical University, State Council of the People's Republic of China, First Affiliated Hospital of Anhui Medical University, NHC, China CDC]","['China', 'China', 'China', 'China']","[People ', Republic of China, Anhui Provincial Cancer Institute, University]"
84,"['University of New Mexico', ""St. Jude Children's Research Hospital"", 'University of Texas Health Science Center']","[St. Jude Children's Research Hospital, University of New Mexico]","['United States', 'United States', 'United States']",[University of Texas Health Science Center]
85,"['Shanghai Public Health Clinical Center', 'Fudan University']","[Shanghai Public Health Clinical Center, Fudan University]","['China', 'China']",[]
86,"[""Peking University People's Hospital"", 'Peking University International Hospital']","[Peking University People's Hospital, Peking University International Hospital]","['China', 'China']",[]
87,"['Icahn School of Medicine at Mount Sinai', 'Tisch Cancer Institute']","[Tisch Cancer Institute, Mount Sinai Queens]","['United States', 'United States']",[]
88,"['University Hospital Brussels', 'University Hospitals Leuven']",[University Hospital Brussels],"['Belgium', 'Belgium']",[University Hospitals Leuven]
89,"['iBiMED-Institute of Biomedicine and Department of Medical Science', 'University of Aveiro', 'University of Porto']","[University of Porto, University of Aveiro]","['Portugal', 'Portugal', 'Portugal']","[Campus Universitario de Santiago, iBiMED, Institute of Biomedicine]"
90,"['Munich Institute of Biomedical Engineering', 'Technical University of Munich', 'Institute of Virology', 'German Cancer Research Center (DKFZ)', 'German Center for Infection Research (DZIF)']","[Technical University of Munich, German Cancer Research Center, German Center for Infection Research]","['Germany', 'Germany', 'Germany', 'Germany', 'Germany']","[Munich Institute of Biomedical Engineering, Institute of Virology, Helmholtz Munich]"
91,"['Biomedical Research Imaging Center', 'UNC Lineberger Comprehensive Cancer Center', 'University of North Carolina', 'LED Radiofluidics Corp.']","[Pennington Biomedical Research Center, UNC Lineberger Comprehensive Cancer Center, University of North Carolina System]","['United States', 'United States', 'United States', 'United States']",[LED Radiofluidics Corp.]
92,NaN,[],NaN,[]
93,NaN,[],NaN,[]
94,['National Cancer Center Hospital'],[],['Japan'],[National Cancer Center Hospital]
95,['Memorial Sloan-Kettering Cancer Center'],[Memorial Sloan Kettering Cancer Center],['United States'],[]