In [1]:
import psycopg2
import os
import pandas as pd
import ast
import re

from tqdm import tqdm
from dotenv import load_dotenv
load_dotenv()
pd.set_option('display.max_rows', 100000)
pd.set_option("max_colwidth", 500)
KEY_POSTGRES = os.getenv("KEY_POSTGRES")

In [2]:
DF_input = input().strip()

 C:\Users\svalb\OneDrive\Escritorio\Data_40_years_cancer_studies\preparedInstitutionsTestDatabaseAccess.csv

In [3]:
df = pd.read_csv(DF_input)

In [18]:
# Create empty columns
df['Institutions_db_id'] = [[] for _ in range(len(df))]
df['Institutions_db_name'] = [[] for _ in range(len(df))]
df['Countries_db_country'] = [[] for _ in range(len(df))]

# Open ONE connection
connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)
cursor = connection.cursor()

for row in tqdm(range(len(df))):
    found_institutions = []

    if pd.isna(df.at[row, "NER_BERT"]):    
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = [ner.get('word') for ner in ner_results if ner.get('entity_group') == 'SUBC']
    cou_ner_results = [ner.get('word') for ner in ner_results if ner.get('entity_group') == 'COU']

    for ner in ner_results:
        if ner.get('entity_group') != 'INS':
            continue
    
        query = ner.get('word')

        if '\'' in query:
            query = re.sub("\'", "\'\'", query)
        
        # PARAMETERIZED QUERY
        cursor.execute(
            "SELECT institution_id, name FROM institution_names WHERE name = %s;",
            (query,)
        )
        records = cursor.fetchall()

        candidates = {
            el[0]: el[1]
            for el in records
        }


        # -------------------------
        # ---- ONE EXACT MATCH ----
        # -------------------------

        if len(candidates) == 1:
            new_query = list(candidates.keys())[0]
    
            cursor.execute(
                "SELECT country_name FROM institution_locations WHERE institution_id = %s;",
                (new_query,)
            )
            
            location_records = cursor.fetchall()
    
            if location_records:
                found_institutions.append((new_query, list(candidates.values())[0], location_records[0][0]))
                continue


        # -------------------------------------
        # ---- NO MATCHES, TRY FUZZY MATCH ----
        # -------------------------------------

        elif len(candidates) == 0:
            # Call the database again with a fuzzy string match
            cursor.execute(
                "SELECT institution_id, name FROM institution_names WHERE levenshtein(name, %s) <= 2;",
                (query,)
            )
            records = cursor.fetchall()
            
            candidates = {
                el[0]: el[1]
                for el in records
            }
            

            # -------------------------
            # ---- ONE FUZZY MATCH ----
            # -------------------------

            if len(candidates) == 1:
                
                # Find related country via institution_locations
                new_query = list(candidates.keys())[0]
    
                cursor.execute(
                    "SELECT city_name, country_name, subdivision_name FROM institution_locations WHERE institution_id = %s;",
                    (new_query,)
                )
                location_records = cursor.fetchall()
    
                if location_records and (location_records[0][1] in cou_ner_results):
                    found_institutions.append((new_query, list(candidates.values())[0], location_records[0][0]))
                    continue

                elif location_records and ((location_records[0][0] in subc_ner_results) or (location_records[0][2] in subc_ner_results)):
                    found_institutions.append((new_query, list(candidates.values())[0], location_records[0][0]))
                    continue
                else:
                    continue


            # -----------------------------------
            # ---- NO FUZZY MATCHES, GIVE UP ----
            # -----------------------------------

            elif len(candidates) == 0:
                continue

            
            # ------------------------------------------------------------------------------
            # ---- MULTIPLE FUZZY MATCHES, TRY DISAMBIGUATION VIA COUNTRY OR SUBCOUNTRY ----
            # ------------------------------------------------------------------------------

            elif len(candidates) > 1:
                matching_candidates = []

                for inst_id, inst_name in candidates.items():
                    new_query = inst_id    

                    cursor.execute(
                        "SELECT city_name, country_name, subdivision_name FROM institution_locations WHERE institution_id = %s;",
                        (new_query,)
                    )

                    location_records = cursor.fetchall()

                    if location_records and (location_records[0][1] in cou_ner_results):
                        matching_candidates.append((inst_id, 
                                                    inst_name,
                                                    location_records[0][0]))
                    
                    elif location_records and ((location_records[0][0] in subc_ner_results) or (location_records[0][2] in subc_ner_results)):
                        matching_candidates.append((inst_id, 
                                                    inst_name,
                                                    location_records[0][0]))
                    

                if len(matching_candidates) == 1:
                    found_institutions.append(matching_candidates[0])

                # Grow here to add dissambiguation via hierarchies of institutions



        # ------------------------------------------------------------------------------
        # ---- MULTIPLE EXACT MATCHES, TRY DISAMBIGUATION VIA COUNTRY OR SUBCOUNTRY ----
        # ------------------------------------------------------------------------------
        
        elif len(candidates) > 1:
            matching_candidates = []

            for inst_id, inst_name in candidates.items():
                new_query = inst_id    


                cursor.execute(
                    "SELECT city_name, country_name, subdivision_name FROM institution_locations WHERE institution_id = %s;",
                    (new_query,)
                )

                location_records = cursor.fetchall()

                if location_records and (location_records[0][1] in cou_ner_results):
                    matching_candidates.append((new_query,
                                                inst_name,
                                                location_records[0][0]))
                    
                elif location_records and ((location_records[0][0] in subc_ner_results) or (location_records[0][2] in subc_ner_results)):
                    matching_candidates.append((new_query, 
                                                inst_name,
                                                location_records[0][0]))
                    

            if len(matching_candidates) == 1:
                found_institutions.append(matching_candidates[0])

            # Grow here to add dissambiguation via hierarchies of institutions


    
    if found_institutions:
        found_institutions = list(set(found_institutions))
        ids, names, countries = zip(*found_institutions)

        df.at[row, 'Institutions_db_id'] = list(ids)
        df.at[row, 'Institutions_db_name'] = list(names)
        df.at[row, 'Countries_db_country'] = list(countries)


cursor.close()
connection.close()

100%|████████████████████████████████████████████████████████████████████████████████| 103/103 [03:17<00:00,  1.91s/it]

# Optimization of country queries

In [16]:
# Pre-create result columns
df['Institutions_db_id'] = [[] for _ in range(len(df))]
df['Institutions_db_name'] = [[] for _ in range(len(df))]
df['Countries_db_country'] = [[] for _ in range(len(df))]

connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)

cursor = connection.cursor()

for row in tqdm(range(len(df))):

    if pd.isna(df.at[row, "NER_BERT"]):
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'SUBC'
    }

    cou_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'COU'
    }

    found_institutions = []

    for ner in ner_results:

        if ner.get('entity_group') != 'INS':
            continue

        query = ner.get('word')

        # -----------------------
        # EXACT MATCH QUERY
        # -----------------------

        cursor.execute(
            "SELECT institution_id, name FROM institution_names WHERE name = %s;",
            (query,)
        )

        records = cursor.fetchall()

        candidates = {r[0]: r[1] for r in records}

        # =========================
        # EXACT MATCH: ONE
        # =========================

        if len(candidates) == 1:

            inst_id = next(iter(candidates))

            cursor.execute(
                "SELECT country_name FROM institution_locations WHERE institution_id = %s;",
                (inst_id,)
            )

            location = cursor.fetchone()

            if location:
                found_institutions.append(
                    (inst_id, candidates[inst_id], location[0])
                )

            continue

        # =========================
        # EXACT MATCH: MULTIPLE
        # =========================

        elif len(candidates) > 1:

            candidate_ids = list(candidates.keys())

            cursor.execute(
                """
                SELECT institution_id, city_name, country_name, subdivision_name
                FROM institution_locations
                WHERE institution_id = ANY(%s);
                """,
                (candidate_ids,)
            )

            location_rows = cursor.fetchall()

            location_map = {
                r[0]: r[1:] for r in location_rows
            }

            matching_candidates = []

            for inst_id, inst_name in candidates.items():

                if inst_id not in location_map:
                    continue

                city, country, subdivision = location_map[inst_id]

                if country in cou_ner_results:
                    matching_candidates.append(
                        (inst_id, inst_name, country)
                    )

                elif city in subc_ner_results or subdivision in subc_ner_results:
                    matching_candidates.append(
                        (inst_id, inst_name, country)
                    )

            if len(matching_candidates) == 1:
                found_institutions.append(matching_candidates[0])

            continue

        # =========================
        # EXACT MATCH: ZERO → FUZZY
        # =========================

        elif len(candidates) == 0:

            cursor.execute(
                """
                SELECT institution_id, name
                FROM institution_names
                WHERE levenshtein(name, %s) <= 2;
                """,
                (query,)
            )

            records = cursor.fetchall()

            candidates = {r[0]: r[1] for r in records}

            # -------------------
            # FUZZY: ONE
            # -------------------

            if len(candidates) == 1:

                inst_id = next(iter(candidates))

                cursor.execute(
                    """
                    SELECT city_name, country_name, subdivision_name
                    FROM institution_locations
                    WHERE institution_id = %s;
                    """,
                    (inst_id,)
                )

                location = cursor.fetchone()

                if location:

                    city, country, subdivision = location

                    if (
                        country in cou_ner_results
                        or city in subc_ner_results
                        or subdivision in subc_ner_results
                    ):
                        found_institutions.append(
                            (inst_id, candidates[inst_id], country)
                        )

                continue

            # -------------------
            # FUZZY: MULTIPLE
            # -------------------

            elif len(candidates) > 1:

                candidate_ids = list(candidates.keys())

                cursor.execute(
                    """
                    SELECT institution_id, city_name, country_name, subdivision_name
                    FROM institution_locations
                    WHERE institution_id = ANY(%s);
                    """,
                    (candidate_ids,)
                )

                location_rows = cursor.fetchall()

                location_map = {
                    r[0]: r[1:] for r in location_rows
                }

                matching_candidates = []

                for inst_id, inst_name in candidates.items():

                    if inst_id not in location_map:
                        continue

                    city, country, subdivision = location_map[inst_id]

                    if country in cou_ner_results:
                        matching_candidates.append(
                            (inst_id, inst_name, country)
                        )

                    elif city in subc_ner_results or subdivision in subc_ner_results:
                        matching_candidates.append(
                            (inst_id, inst_name, country)
                        )

                if len(matching_candidates) == 1:
                    found_institutions.append(matching_candidates[0])

                continue

            # -------------------
            # FUZZY: ZERO
            # -------------------

            elif len(candidates) == 0:
                continue

    # =========================
    # WRITE RESULTS
    # =========================

    if found_institutions:
        found_institutions = list(set(found_institutions))
        
        ids, names, countries = zip(*found_institutions)

        df.at[row, 'Institutions_db_id'] = list(ids)
        df.at[row, 'Institutions_db_name'] = list(names)
        df.at[row, 'Countries_db_country'] = list(countries)

cursor.close()
connection.close()

100%|████████████████████████████████████████████████████████████████████████████████| 103/103 [03:12<00:00,  1.87s/it]

# Trigram similarities

In [11]:
from collections import OrderedDict
import pandas as pd
import numpy as np
import psycopg2
import re
import ast
from tqdm import tqdm
from fuzzywuzzy import fuzz
import pickle

CACHE_SIZE = 1000

# -----------------------
# LOAD ALL DATA INTO MEMORY
# -----------------------

connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)

cursor = connection.cursor()

# Load institution_names table
cursor.execute("SELECT institution_id, name FROM institution_names;")
institution_names_rows = cursor.fetchall()

# Load institution_locations table
cursor.execute(
    "SELECT institution_id, city_name, country_name, subdivision_name FROM institution_locations;"
)
institution_locations_rows = cursor.fetchall()

connection.close()

# -----------------------
# BUILD IN-MEMORY INDEXES
# -----------------------

# Index 1: name → [(id, name), ...]
name_to_institutions = {}
for inst_id, name in institution_names_rows:
    if name not in name_to_institutions:
        name_to_institutions[name] = []
    name_to_institutions[name].append((inst_id, name))

# Index 2: id → (city, country, subdivision)
institution_locations_map = {}
for inst_id, city, country, subdivision in institution_locations_rows:
    institution_locations_map[inst_id] = (city, country, subdivision)

# Index 3: all institution names (for fuzzy matching)
all_institution_names = [name for _, name in institution_names_rows]

# Create a reverse lookup: name → [ids] for faster fuzzy matching
fuzzy_name_to_ids = {}
for inst_id, name in institution_names_rows:
    if name not in fuzzy_name_to_ids:
        fuzzy_name_to_ids[name] = []
    fuzzy_name_to_ids[name].append(inst_id)

# -----------------------
# CACHE (LRU, size=1000)
# -----------------------

institution_cache = OrderedDict()

# -----------------------
# HELPER FUNCTIONS
# -----------------------

def fuzzy_match_optimized(query, threshold=0.6):
    """
    Optimized fuzzy matching using precomputed names.
    Returns {inst_id: name} dict for matches above threshold.
    """
    matches = {}
    query_lower = query.lower()
    
    for name in all_institution_names:
        # Quick length-based filter before expensive comparison
        if abs(len(query) - len(name)) > max(len(query), len(name)) * 0.5:
            continue
        
        # Use simple similarity metric (can use Levenshtein if fuzzywuzzy not available)
        similarity = fuzz.ratio(query_lower, name.lower()) / 100.0
        
        if similarity > threshold:
            inst_ids = fuzzy_name_to_ids[name]
            for inst_id in inst_ids:
                matches[inst_id] = name
    
    return matches

def get_candidates_for_query(query):
    """
    Returns {inst_id: name} for exact matches or None.
    """
    return {inst_id: name for inst_id, name in name_to_institutions.get(query, [])}

def resolve_institution(inst_id, inst_name, cou_ner_results, subc_ner_results):
    """
    Check if institution's location matches available context.
    Returns (inst_id, inst_name, country) or None.
    """
    if inst_id not in institution_locations_map:
        return None
    
    city, country, subdivision = institution_locations_map[inst_id]
    
    if country in cou_ner_results or city in subc_ner_results or subdivision in subc_ner_results:
        return (inst_id, inst_name, country)
    
    return None

def get_resolved_institutions(candidates, cou_ner_results, subc_ner_results):
    """
    Filter candidates based on location matching logic.
    Returns list of (inst_id, inst_name, country) tuples.
    """
    resolved = []
    
    if len(candidates) == 1:
        # Single match: only check if location exists
        inst_id = next(iter(candidates))
        if inst_id in institution_locations_map:
            city, country, subdivision = institution_locations_map[inst_id]
            resolved.append((inst_id, candidates[inst_id], country))
    
    elif len(candidates) > 1:
        # Multiple matches: use location context for disambiguation
        for inst_id, inst_name in candidates.items():
            result = resolve_institution(inst_id, inst_name, cou_ner_results, subc_ner_results)
            if result:
                resolved.append(result)
    
    return resolved

# -----------------------
# PRE-CREATE RESULT COLUMNS
# -----------------------

df['Institutions_db_id'] = [[] for _ in range(len(df))]
df['Institutions_db_name'] = [[] for _ in range(len(df))]
df['Countries_db_country'] = [[] for _ in range(len(df))]

# -----------------------
# MAIN PROCESSING LOOP
# -----------------------

for row in tqdm(range(len(df))):
    
    if pd.isna(df.at[row, "NER_BERT"]):
        continue
    
    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)
    
    subc_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'SUBC'
    }
    
    cou_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'COU'
    }
    
    found_institutions = []
    
    for ner in ner_results:
        
        if ner.get('entity_group') != 'INS':
            continue
        
        query = ner.get('word')
        
        # -----------------------
        # CACHE LOOKUP
        # -----------------------
        
        if query in institution_cache:
            
            ids, names, countries = institution_cache[query]
            
            for inst in zip(ids, names, countries):
                found_institutions.append(inst)
            
            institution_cache.move_to_end(query)
            
            continue
        
        # -----------------------
        # EXACT MATCH LOOKUP (in-memory)
        # -----------------------
        
        candidates = get_candidates_for_query(query)
        
        if candidates:
            resolved = get_resolved_institutions(candidates, cou_ner_results, subc_ner_results)
        else:
            # -----------------------
            # FUZZY MATCH (in-memory)
            # -----------------------
            candidates = fuzzy_match_optimized(query, threshold=0.6)
            resolved = get_resolved_institutions(candidates, cou_ner_results, subc_ner_results)
        
        # -----------------------
        # CACHE STORE
        # -----------------------
        
        if resolved:
            
            ids, names, countries = zip(*resolved)
            
            institution_cache[query] = (list(ids), list(names), list(countries))
            
            if len(institution_cache) > CACHE_SIZE:
                institution_cache.popitem(last=False)
            
            for inst in resolved:
                found_institutions.append(inst)
    
    # =========================
    # WRITE RESULTS
    # =========================
    
    if found_institutions:
        
        found_institutions = list(set(found_institutions))
        
        ids, names, countries = zip(*found_institutions)
        
        df.at[row, 'Institutions_db_id'] = list(ids)
        df.at[row, 'Institutions_db_name'] = list(names)
        df.at[row, 'Countries_db_country'] = list(countries)

ModuleNotFoundError: No module named 'fuzzywuzzy'

In [9]:
df[["Institutions_man", "Institutions_db_name"]]

,Institutions_man,Institutions_db_name
0,NaN,[]
1,NaN,[]
2,"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of Porto, University of British Columbia, i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto]"
3,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[Cincinnati Children's Hospital Medical Center, Children's Healthcare of Atlanta, University of Cincinnati, Emory University]"
4,"['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[Stephenson Cancer Center, University of Chicago, University of Memphis, University of Oklahoma Health Sciences Center, Rutgers Biomedical and Health Sciences, Battelle Memorial Institute, University of Pennsylvania]"
5,"['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[Universidad Nacional Autónoma de México, CONAHCYT]"
6,"['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[Inserm, CNRS, University Cancer Institute Toulouse Oncopole, ANR]"
7,['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University]
8,"['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw]
9,"['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']",[Chang Gung University]
10,"['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']","[Ludwig-Maximilians-Universität in Munich, Medical Genetics Center, Ruhr University Bochum, BG University Hospital Bergmannsheil Bochum]"
11,"['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[IRCCS Ospedale San Raffaele, Vita-Salute San Raffaele University]"
12,"['University of Adelaide', 'Queen Elizabeth Hospital']","[University of Adelaide, Queen Elizabeth Hospital]"
13,['University of Zimbabwe'],[University of Zimbabwe]
14,['University of Tokyo Hospital'],[University of Tokyo Hospital]
15,['University Hospital Centre of Grenoble'],[]
16,['Harvard'],[]
17,['University of Washington'],[University of Washington]
18,['University of Würzburg'],[University of Würzburg]
19,"['Mannheim Medical Center', 'University of Heidelberg']",[]
20,NaN,[]
21,['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology]
22,['Duke University Medical Center'],[]
23,"['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]",[]
24,['University of Rochester'],[University of Rochester]
25,['Stavanger University Hospital'],[Stavanger University Hospital]
26,['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[]
27,['Akademii Medycznej w Gdańsku'],[]
28,['Vienna Medical University'],[]
29,"['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]"
30,NaN,[]
31,"['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University]
32,"['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital]
33,"['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University]
34,NaN,[]
35,['Royal North Brisbane Hospital'],[]
36,['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[Azienda Ospedaliero Universitaria Maggiore della Carita]
37,['Universitá degli Studi di Palermo'],[]
38,['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf]
39,NaN,[]
40,"['Institute of Medical Microbiology', 'Charles University']","[Institute of Microbiology CAS, Charles University]"
41,['Queensland Institute of Medical Research'],[Queensland Institute of Medical Research]
42,['University of Porto'],[University of Porto]
43,"['University of Liverpool', 'Linda McCartney Centre', 'Royal Liverpool University Hospital']","[University of Liverpool, Royal Liverpool University Hospital]"
44,"['University of Leipzig Medical Center', 'University Medical Center Hamburg-Eppendorf', 'Institute for Medical Biostatistics, Epidemiology and Informatics', 'University of Mainz Medical Center', 'University Hospital of Essen', ""Children's Hospital""]","[University Medical Center Freiburg, Institute for Medical Informatics and Biostatistics, University Medical Center Göttingen, University of Würzburg, Cnopf Children's Hospital, Kantonsspital St. Gallen, University Medical Center Hamburg-Eppendorf]"
45,"['Northwestern Memorial Hospital', 'Robert H. Lurie Comprehensive Cancer Center', 'Northwestern University']","[Robert H. Lurie Comprehensive Cancer Center, Northwestern Memorial Hospital, Northwestern University]"
46,"['First Affiliated Hospital', 'Nanchang University']",[First Affiliated Hospital of Nanchang University]
47,"['Suzhou Municipal Hospital', 'Affiliated Suzhou Hospital', 'Nanjing Medical University', ""Shaoxing People's Hospital"", 'Shaoxing Hospital', 'Zhejiang University']","[Children's Hospital of Zhejiang University, Suzhou Municipal Hospital]"
48,NaN,[]
49,NaN,[]
50,"['Institute of Biomedical and Genetic Engineering (IBGE)', 'International Islamic University']",[Institute of Biomedical and Genetic Engineering]
51,"['Istanbul University', 'Institute of Experimental Medicine', 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital']","[Istanbul University, Yeditepe University]"
52,NaN,[]
53,NaN,[]
54,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', 'Cancer and Blood Disease Institute', ""Boston Children's Hospital"", 'Harvard']","[Cincinnati Children's Hospital Medical Center, Boston Children's Museum, IIT@Harvard, University of Cincinnati]"
55,"['Erasmus MC', 'Utrecht University', 'Erasmus MC Cancer Institute']","[Utrecht University, Erasmus MC, Erasmus MC Cancer Institute]"
56,NaN,[]
57,NaN,[]
58,"['Queen Elizabeth Hospital', 'Royal Victoria Infirmary', 'Medical Research Council Clinical Trials Unit', 'University College London']","[Royal Victoria Infirmary, Medical Research Council, University College London, Queen Elizabeth Hospital]"
59,"['Centro Nacional de Investigaciones Oncológicas (CNIO)', 'Center for Molecular Biology of Heidelberg University (ZMBH)', 'Centro de Investigación en Red de Enfermedades Neurodegenerativas (CIBERNED)', 'University of Cantabria', 'IDIVAL', 'Center for Biomedicine and Medical Technology Mannheim (CBTM)', 'Heidelberg University', 'German Cancer Research Center (DKFZ)', 'Hope Center for Neurological Diseases', 'Washington University']","[IDIVAL, University of Cantabria, Center for Molecular Biology Severo Ochoa, Heidelberg University, DKFZ-ZMBH Alliance, Centro de Investigación Biomédica en Red, Enfermedades Neurodegenerativas]"
60,"[""King's College London"", 'Comprehensive Biomedical Research Centre', ""Guy's and St Thomas NHS Foundation Trust"", 'Uppsala University', 'Medical Products Agency', 'Karolinska Insituet']","[Uppsala University, Medical Products Agency, King's College London, Guy's and St Thomas' NHS Foundation Trust, Karolinska Institutet, UCL Biomedical Research Centre]"
61,"['August Pi i Sunyer Biomedical Research Institute', 'Hospital Clínic', 'Sant Joan de Deu Childrens Hospital', 'University of Barcelona', 'Nihon University School of Medicine', 'University of Lausanne', 'University of Pennsylvania', 'Catalan Institution for Research and Advanced Studies']","[University of Barcelona, Nihon University, Catalan Institution for Research and Advanced Studies, University of Pennsylvania, Sant Joan de Déu-Barcelona Children’s Hospital]"
62,['Delhi State Cancer Institute'],[Delhi State Cancer Institute]
63,"['Kushiro Rosai Hospital', 'Kanagawa Cancer Center', 'Keio University', 'Sapporo Medical University', 'Hijirigaoka Hospital', 'National Hospital Organization', 'Osaka National Hospital', 'Hiroshima University', 'University of Tokyo', 'Tokai Central Hospital', 'Translational Research and Clinical Trial Center', 'Hokkaido University Hospital', 'Japanese Foundation for Multidisciplinary Treatment of Cancer']","[Osaka National Hospital, Kanagawa Cancer Center, Japanese Foundation for Multidisciplinary Treatment of Cancer, Tokai Central Hospital, Hiroshima University, Hokkaido University Hospital, Sapporo Medical University, National Hospital Organization, Kushiro Rosai Hospital, Keio University]"
64,['Life Raft Group'],[]
65,['Washington State University'],[Washington State University]
66,"['Addis Ababa University', 'Karolinska Institutet', 'Karolinska University Hospital', 'Center for Innovative Drug Development and Therapeutic Trials', 'Armauer Hansen Research Institute']","[Karolinska Institutet, Addis Ababa University, Armauer Hansen Research Institute, Karolinska University Hospital]"
67,[nan],[]
68,"['Tulane University', 'Louisiana State University Health Sciences Center']","[Louisiana State University Health Sciences Center New Orleans, Tulane University]"
69,"['Hebei Medical University', 'Bethune International Peace Hospital', 'Hebei University of Chinese Medicine']","[Hebei Medical University, Bethune International Peace Hospital, Hebei University of Chinese Medicine]"
70,"[""Henan Provincial People's Hospital"", ""Zhengzhou University People's Hospital"", ""Henan University People's Hospital"", 'Institute of Hematology']",[]
71,"['Huazhong University of Science and Technology Union Shenzhen Hospital (Nanshan Hospital)', ""Shenzhen Second People's Hospital"", 'First Affiliated Hospital', 'Shenzhen University']",[Huazhong University of Science and Technology]
72,['Medical University of Innsbruck'],[]
73,"['Stanton L. Young Biomedical Research Center', 'University of Oklahoma Health Science Center']",[University of Oklahoma Health Sciences Center]
74,"['Center for Bioengineering and Tissue Regeneration', 'University of California', 'Gladstone Institutes', 'Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research', 'Helen Diller Family Comprehensive Cancer Center']","[University of California, San Francisco, Gladstone Institutes, UCSF Helen Diller Family Comprehensive Cancer Center]"
75,"['Northwestern University', 'Robert H. Lurie Comprehensive Cancer Center']","[Robert H. Lurie Comprehensive Cancer Center, Northwestern University]"
76,"['Qilu Hospital', 'Shandong University', 'Central Hospital', 'Zaozhuang Coal Mining Group', 'Jinan integrative medicine hospital']",[Qilu Hospital of Shandong University]
77,"[""St. Jude Children's Research Hospital"", 'Cornell', 'University of Chicago', 'Howard Hughes Medical Institute']","[University of Chicago, Memphis Zoo, St. Jude Children's Research Hospital, Weill Cornell Medicine, Howard Hughes Medical Institute]"
78,['Baylor College of Medicine'],[Baylor College of Medicine]
79,['University of California'],"[University of California, San Francisco]"
80,NaN,[]
81,NaN,[]
82,"['Second Affiliated Hospital', 'Fujian Medical University', 'Nanjing Medical University']","[Second Affiliated Hospital of Fujian Medical University, Nanjing Medical University]"
83,"['Universidade de São Paulo', 'Universidade do Oeste Paulista UNOESTE', 'Center of Translational Research in Oncology (LIM24)', 'Instituto do Cancer do Estado de Sao Paulo (ICESP)']","[Instituto do Câncer do Estado de São Paulo, Universidade de São Paulo]"
84,"['Hepatic Surgery Center', 'Tongji Hospital', 'Huazhong University of Science and Technology', 'Shanxi Bethune Hospital', 'Shanxi Academy of Medical Sciences', 'Shanxi Medical University', 'Shanxi Tongji Hospital']","[Shanxi Medical University, Bethune Second Hospital, Tongji Hospital, Huazhong University of Science and Technology, Shanxi Academy of Medical Sciences]"
85,"['Centre de Recherche des Cordeliers', 'INSERM', 'Sorbonne Université', 'Université Paris Cité', 'Institut universitaire de France', 'Institut Gustave Roussy', 'Centre de Recherche des Cordeliers', 'Klinikum Rechts der Isar', 'Technical University of Munich', 'Institute of Biophysics', 'Czech Academy of Sciences', 'CNRS', 'Institut Polytechnique de Paris', 'Université Paris-Saclay', 'Université Sorbonne Paris Nord', 'Institut du Cancer Paris CARPEM', 'Hôpital Européen Georges Pompidou']","[INSERM, Université Sorbonne Paris Nord, Technical University of Munich, Czech Academy of Sciences, Institut Gustave Roussy, Centre de Recherche des Cordeliers, Institut Polytechnique de Paris, Sorbonne Université, Klinikum rechts der Isar, CNRS, École Polytechnique, Université Paris Cité, Institut Universitaire de France]"
86,"['Norwegian University of Science and Technology', 'St. Olavs Hospital', 'Center for Oral Health Services and Research Mid-Norway (TkMidt)', 'Clinic of Medicine', 'K.G. Jebsen Centre for Genetic Epidemiology']",[Norwegian University of Science and Technology]
87,['Mayo Clinic'],[Mayo Clinic]
88,"['University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca', 'Biotechnology Research Center', 'Life Sciences Institute King Michael I of Romania', 'Babeș-Bolyai University']","[Universitatea Babeș-Bolyai, Biotechnology Research Center]"
89,"['Graduate Institute of Biomedical Science', 'China Medical University', 'Taichung Tzu Chi Hospital', 'Buddhist Tzu Chi Medical Foundation', 'China Medical University Hospital', 'Asia University', 'Institute of New Drug Development']","[China Medical University Hospital, China Medical University, Tzu Chi University, Buddhist Tzu Chi Medical Foundation]"
90,"['Chongqing University Three Gorges Hospital', 'Center for Medicine Research and Translation', ""Chengdu Fifth People's Hospital""]",[]
91,"['Boston University', 'Shaukat Khanum Memorial Cancer Hospital and Research Centre']","[Shaukat Khanum Memorial Cancer Hospital and Research Center, Boston University]"
92,NaN,[]
93,NaN,[]
94,['Georgetown University Medical Center'],[Georgetown University Medical Center]
95,['University of South Florida'],[University of South Florida]
96,['Johns Hopkins Oncology Center'],[]
97,"['Albert Einstein Cancer Center', 'Montefiore Medical Center']","[Albert Einstein Cancer Center at Montefiore, Montefiore Medical Center]"
98,['General Hospital Manuel Gea Gonzalez'],[Hospital General Dr. Manuel Gea Gonzalez]
99,['University Hospital Leiden'],[Leiden University]
100,['Paul Scherrer Institute'],[Paul Scherrer Institute]
101,['Wayne State University'],[Wayne State University]
102,[],[]

In [12]:
# -----------------------
# CACHE (LRU size = 1000)
# -----------------------

CACHE_SIZE = 1000
institution_cache = OrderedDict()

# -----------------------
# PRE-CREATE RESULT COLUMNS
# -----------------------

df['Institutions_db_id'] = [[] for _ in range(len(df))]
df['Institutions_db_name'] = [[] for _ in range(len(df))]
df['Countries_db_country'] = [[] for _ in range(len(df))]

# -----------------------
# DB CONNECTION
# -----------------------

connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)

cursor = connection.cursor()

# -----------------------
# LOAD DATABASE TABLES INTO MEMORY
# -----------------------

print("Loading institution_names...")
cursor.execute("SELECT institution_id, name FROM institution_names")
rows = cursor.fetchall()

name_index = {}
for inst_id, name in rows:
    name_index.setdefault(name, []).append((inst_id, name))

print("Loading institution_locations...")
cursor.execute("""
    SELECT institution_id, city_name, country_name, subdivision_name
    FROM institution_locations
""")

rows = cursor.fetchall()

location_index = {
    r[0]: (r[1], r[2], r[3])
    for r in rows
}

print("Indices loaded.")

# -----------------------
# MAIN LOOP
# -----------------------

for row in tqdm(range(len(df))):

    if pd.isna(df.at[row, "NER_BERT"]):
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'SUBC'
    }

    cou_ner_results = {
        ner.get('word') for ner in ner_results
        if ner.get('entity_group') == 'COU'
    }

    found_institutions = []

    for ner in ner_results:

        if ner.get('entity_group') != 'INS':
            continue

        query = ner.get('word')

        # -----------------------
        # CACHE LOOKUP
        # -----------------------

        if query in institution_cache:

            ids, names, countries = institution_cache[query]

            for inst in zip(ids, names, countries):
                found_institutions.append(inst)

            institution_cache.move_to_end(query)

            continue

        # -----------------------
        # EXACT MATCH (IN MEMORY)
        # -----------------------

        records = name_index.get(query, [])
        candidates = {r[0]: r[1] for r in records}

        resolved = []

        # =========================
        # EXACT MATCH: ONE
        # =========================

        if len(candidates) == 1:

            inst_id = next(iter(candidates))

            location = location_index.get(inst_id)

            if location:
                city, country, subdivision = location
                resolved.append((inst_id, candidates[inst_id], country))

        # =========================
        # EXACT MATCH: MULTIPLE
        # =========================

        elif len(candidates) > 1:

            candidate_ids = list(candidates.keys())

            location_map = {
                inst_id: location_index[inst_id]
                for inst_id in candidate_ids
                if inst_id in location_index
            }

            matching_candidates = []

            for inst_id, inst_name in candidates.items():

                if inst_id not in location_map:
                    continue

                city, country, subdivision = location_map[inst_id]

                if country in cou_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

                elif city in subc_ner_results or subdivision in subc_ner_results:
                    matching_candidates.append((inst_id, inst_name, country))

            if len(matching_candidates) == 1:
                resolved.append(matching_candidates[0])

        # =========================
        # EXACT MATCH: ZERO → FUZZY
        # =========================

        elif len(candidates) == 0:

            cursor.execute(
                """
                SELECT institution_id, name
                FROM institution_names
                WHERE similarity(name, %s) > 0.6
                """,
                (query,)
            )

            records = cursor.fetchall()
            candidates = {r[0]: r[1] for r in records}

            # -------------------
            # FUZZY: ONE
            # -------------------

            if len(candidates) == 1:

                inst_id = next(iter(candidates))
                location = location_index.get(inst_id)

                if location:

                    city, country, subdivision = location

                    if (
                        country in cou_ner_results
                        or city in subc_ner_results
                        or subdivision in subc_ner_results
                    ):
                        resolved.append((inst_id, candidates[inst_id], country))

            # -------------------
            # FUZZY: MULTIPLE
            # -------------------

            elif len(candidates) > 1:

                candidate_ids = list(candidates.keys())

                location_map = {
                    inst_id: location_index[inst_id]
                    for inst_id in candidate_ids
                    if inst_id in location_index
                }

                matching_candidates = []

                for inst_id, inst_name in candidates.items():

                    if inst_id not in location_map:
                        continue

                    city, country, subdivision = location_map[inst_id]

                    if country in cou_ner_results:
                        matching_candidates.append((inst_id, inst_name, country))

                    elif city in subc_ner_results or subdivision in subc_ner_results:
                        matching_candidates.append((inst_id, inst_name, country))

                if len(matching_candidates) == 1:
                    resolved.append(matching_candidates[0])

        # -----------------------
        # STORE IN CACHE
        # -----------------------

        if resolved:

            ids, names, countries = zip(*resolved)

            institution_cache[query] = (list(ids), list(names), list(countries))

            if len(institution_cache) > CACHE_SIZE:
                institution_cache.popitem(last=False)

            for inst in resolved:
                found_institutions.append(inst)

    # =========================
    # WRITE RESULTS
    # =========================

    if found_institutions:

        found_institutions = list(set(found_institutions))

        ids, names, countries = zip(*found_institutions)

        df.at[row, 'Institutions_db_id'] = list(ids)
        df.at[row, 'Institutions_db_name'] = list(names)
        df.at[row, 'Countries_db_country'] = list(countries)

cursor.close()
connection.close()

Loading institution_names...
Loading institution_locations...
Indices loaded.

100%|████████████████████████████████████████████████████████████████████████████████| 103/103 [07:37<00:00,  4.44s/it]

In [13]:
df[["Institutions_man", "Institutions_db_name"]]

,Institutions_man,Institutions_db_name
0,NaN,[]
1,NaN,[]
2,"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of Porto, University of British Columbia, i3S - Instituto de Investigação e Inovação em Saúde, Universidade do Porto]"
3,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[Cincinnati Children's Hospital Medical Center, Children's Healthcare of Atlanta, University of Cincinnati, Emory University]"
4,"['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[Stephenson Cancer Center, University of Chicago, University of Memphis, University of Oklahoma Health Sciences Center, Rutgers Biomedical and Health Sciences, Battelle Memorial Institute, University of Pennsylvania]"
5,"['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[Universidad Nacional Autónoma de México, CONAHCYT]"
6,"['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[Inserm, CNRS, University Cancer Institute Toulouse Oncopole, ANR]"
7,['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University]
8,"['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw]
9,"['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']",[Chang Gung University]
10,"['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']","[Ludwig-Maximilians-Universität in Munich, Medical Genetics Center, Ruhr University Bochum, BG University Hospital Bergmannsheil Bochum]"
11,"['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[IRCCS Ospedale San Raffaele, Vita-Salute San Raffaele University]"
12,"['University of Adelaide', 'Queen Elizabeth Hospital']","[University of Adelaide, Queen Elizabeth Hospital]"
13,['University of Zimbabwe'],[University of Zimbabwe]
14,['University of Tokyo Hospital'],[University of Tokyo Hospital]
15,['University Hospital Centre of Grenoble'],[]
16,['Harvard'],[]
17,['University of Washington'],[University of Washington]
18,['University of Würzburg'],[University of Würzburg]
19,"['Mannheim Medical Center', 'University of Heidelberg']",[]
20,NaN,[]
21,['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology]
22,['Duke University Medical Center'],[]
23,"['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]",[]
24,['University of Rochester'],[University of Rochester]
25,['Stavanger University Hospital'],[Stavanger University Hospital]
26,['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[]
27,['Akademii Medycznej w Gdańsku'],[]
28,['Vienna Medical University'],[]
29,"['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]"
30,NaN,[]
31,"['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University]
32,"['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital]
33,"['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University]
34,NaN,[]
35,['Royal North Brisbane Hospital'],[]
36,['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[Azienda Ospedaliero Universitaria Maggiore della Carita]
37,['Universitá degli Studi di Palermo'],[]
38,['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf]
39,NaN,[]
40,"['Institute of Medical Microbiology', 'Charles University']","[Institute of Microbiology CAS, Charles University]"
41,['Queensland Institute of Medical Research'],[Queensland Institute of Medical Research]
42,['University of Porto'],[University of Porto]
43,"['University of Liverpool', 'Linda McCartney Centre', 'Royal Liverpool University Hospital']","[University of Liverpool, Royal Liverpool University Hospital]"
44,"['University of Leipzig Medical Center', 'University Medical Center Hamburg-Eppendorf', 'Institute for Medical Biostatistics, Epidemiology and Informatics', 'University of Mainz Medical Center', 'University Hospital of Essen', ""Children's Hospital""]","[University Medical Center Freiburg, Institute for Medical Informatics and Biostatistics, University Medical Center Göttingen, University of Würzburg, Cnopf Children's Hospital, Kantonsspital St. Gallen, University Medical Center Hamburg-Eppendorf]"
45,"['Northwestern Memorial Hospital', 'Robert H. Lurie Comprehensive Cancer Center', 'Northwestern University']","[Robert H. Lurie Comprehensive Cancer Center, Northwestern Memorial Hospital, Northwestern University]"
46,"['First Affiliated Hospital', 'Nanchang University']",[First Affiliated Hospital of Nanchang University]
47,"['Suzhou Municipal Hospital', 'Affiliated Suzhou Hospital', 'Nanjing Medical University', ""Shaoxing People's Hospital"", 'Shaoxing Hospital', 'Zhejiang University']","[Children's Hospital of Zhejiang University, Suzhou Municipal Hospital]"
48,NaN,[]
49,NaN,[]
50,"['Institute of Biomedical and Genetic Engineering (IBGE)', 'International Islamic University']",[Institute of Biomedical and Genetic Engineering]
51,"['Istanbul University', 'Institute of Experimental Medicine', 'Yedikule Chest Disease and Thoracic Surgery Training and Research Hospital']","[Istanbul University, Yeditepe University]"
52,NaN,[]
53,NaN,[]
54,"[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', 'Cancer and Blood Disease Institute', ""Boston Children's Hospital"", 'Harvard']","[Cincinnati Children's Hospital Medical Center, Boston Children's Museum, IIT@Harvard, University of Cincinnati]"
55,"['Erasmus MC', 'Utrecht University', 'Erasmus MC Cancer Institute']","[Utrecht University, Erasmus MC, Erasmus MC Cancer Institute]"
56,NaN,[]
57,NaN,[]
58,"['Queen Elizabeth Hospital', 'Royal Victoria Infirmary', 'Medical Research Council Clinical Trials Unit', 'University College London']","[Royal Victoria Infirmary, Medical Research Council, University College London, Queen Elizabeth Hospital]"
59,"['Centro Nacional de Investigaciones Oncológicas (CNIO)', 'Center for Molecular Biology of Heidelberg University (ZMBH)', 'Centro de Investigación en Red de Enfermedades Neurodegenerativas (CIBERNED)', 'University of Cantabria', 'IDIVAL', 'Center for Biomedicine and Medical Technology Mannheim (CBTM)', 'Heidelberg University', 'German Cancer Research Center (DKFZ)', 'Hope Center for Neurological Diseases', 'Washington University']","[IDIVAL, University of Cantabria, Center for Molecular Biology Severo Ochoa, Heidelberg University, DKFZ-ZMBH Alliance, Centro de Investigación Biomédica en Red, Enfermedades Neurodegenerativas]"
60,"[""King's College London"", 'Comprehensive Biomedical Research Centre', ""Guy's and St Thomas NHS Foundation Trust"", 'Uppsala University', 'Medical Products Agency', 'Karolinska Insituet']","[Uppsala University, Medical Products Agency, King's College London, Guy's and St Thomas' NHS Foundation Trust, Karolinska Institutet, UCL Biomedical Research Centre]"
61,"['August Pi i Sunyer Biomedical Research Institute', 'Hospital Clínic', 'Sant Joan de Deu Childrens Hospital', 'University of Barcelona', 'Nihon University School of Medicine', 'University of Lausanne', 'University of Pennsylvania', 'Catalan Institution for Research and Advanced Studies']","[University of Barcelona, Nihon University, Catalan Institution for Research and Advanced Studies, University of Pennsylvania, Sant Joan de Déu-Barcelona Children’s Hospital]"
62,['Delhi State Cancer Institute'],[Delhi State Cancer Institute]
63,"['Kushiro Rosai Hospital', 'Kanagawa Cancer Center', 'Keio University', 'Sapporo Medical University', 'Hijirigaoka Hospital', 'National Hospital Organization', 'Osaka National Hospital', 'Hiroshima University', 'University of Tokyo', 'Tokai Central Hospital', 'Translational Research and Clinical Trial Center', 'Hokkaido University Hospital', 'Japanese Foundation for Multidisciplinary Treatment of Cancer']","[Osaka National Hospital, Kanagawa Cancer Center, Japanese Foundation for Multidisciplinary Treatment of Cancer, Tokai Central Hospital, Hiroshima University, Hokkaido University Hospital, Sapporo Medical University, National Hospital Organization, Kushiro Rosai Hospital, Keio University]"
64,['Life Raft Group'],[]
65,['Washington State University'],[Washington State University]
66,"['Addis Ababa University', 'Karolinska Institutet', 'Karolinska University Hospital', 'Center for Innovative Drug Development and Therapeutic Trials', 'Armauer Hansen Research Institute']","[Karolinska Institutet, Addis Ababa University, Armauer Hansen Research Institute, Karolinska University Hospital]"
67,[nan],[]
68,"['Tulane University', 'Louisiana State University Health Sciences Center']","[Louisiana State University Health Sciences Center New Orleans, Tulane University]"
69,"['Hebei Medical University', 'Bethune International Peace Hospital', 'Hebei University of Chinese Medicine']","[Hebei Medical University, Bethune International Peace Hospital, Hebei University of Chinese Medicine]"
70,"[""Henan Provincial People's Hospital"", ""Zhengzhou University People's Hospital"", ""Henan University People's Hospital"", 'Institute of Hematology']",[]
71,"['Huazhong University of Science and Technology Union Shenzhen Hospital (Nanshan Hospital)', ""Shenzhen Second People's Hospital"", 'First Affiliated Hospital', 'Shenzhen University']",[Huazhong University of Science and Technology]
72,['Medical University of Innsbruck'],[]
73,"['Stanton L. Young Biomedical Research Center', 'University of Oklahoma Health Science Center']",[University of Oklahoma Health Sciences Center]
74,"['Center for Bioengineering and Tissue Regeneration', 'University of California', 'Gladstone Institutes', 'Eli and Edythe Broad Center of Regeneration Medicine and Stem Cell Research', 'Helen Diller Family Comprehensive Cancer Center']","[University of California, San Francisco, Gladstone Institutes, UCSF Helen Diller Family Comprehensive Cancer Center]"
75,"['Northwestern University', 'Robert H. Lurie Comprehensive Cancer Center']","[Robert H. Lurie Comprehensive Cancer Center, Northwestern University]"
76,"['Qilu Hospital', 'Shandong University', 'Central Hospital', 'Zaozhuang Coal Mining Group', 'Jinan integrative medicine hospital']",[Qilu Hospital of Shandong University]
77,"[""St. Jude Children's Research Hospital"", 'Cornell', 'University of Chicago', 'Howard Hughes Medical Institute']","[University of Chicago, Memphis Zoo, St. Jude Children's Research Hospital, Weill Cornell Medicine, Howard Hughes Medical Institute]"
78,['Baylor College of Medicine'],[Baylor College of Medicine]
79,['University of California'],"[University of California, San Francisco]"
80,NaN,[]
81,NaN,[]
82,"['Second Affiliated Hospital', 'Fujian Medical University', 'Nanjing Medical University']","[Second Affiliated Hospital of Fujian Medical University, Nanjing Medical University]"
83,"['Universidade de São Paulo', 'Universidade do Oeste Paulista UNOESTE', 'Center of Translational Research in Oncology (LIM24)', 'Instituto do Cancer do Estado de Sao Paulo (ICESP)']","[Instituto do Câncer do Estado de São Paulo, Universidade de São Paulo]"
84,"['Hepatic Surgery Center', 'Tongji Hospital', 'Huazhong University of Science and Technology', 'Shanxi Bethune Hospital', 'Shanxi Academy of Medical Sciences', 'Shanxi Medical University', 'Shanxi Tongji Hospital']","[Shanxi Medical University, Bethune Second Hospital, Tongji Hospital, Huazhong University of Science and Technology, Shanxi Academy of Medical Sciences]"
85,"['Centre de Recherche des Cordeliers', 'INSERM', 'Sorbonne Université', 'Université Paris Cité', 'Institut universitaire de France', 'Institut Gustave Roussy', 'Centre de Recherche des Cordeliers', 'Klinikum Rechts der Isar', 'Technical University of Munich', 'Institute of Biophysics', 'Czech Academy of Sciences', 'CNRS', 'Institut Polytechnique de Paris', 'Université Paris-Saclay', 'Université Sorbonne Paris Nord', 'Institut du Cancer Paris CARPEM', 'Hôpital Européen Georges Pompidou']","[INSERM, Université Sorbonne Paris Nord, Technical University of Munich, Czech Academy of Sciences, Institut Gustave Roussy, Centre de Recherche des Cordeliers, Institut Polytechnique de Paris, Sorbonne Université, Klinikum rechts der Isar, CNRS, École Polytechnique, Université Paris Cité, Institut Universitaire de France]"
86,"['Norwegian University of Science and Technology', 'St. Olavs Hospital', 'Center for Oral Health Services and Research Mid-Norway (TkMidt)', 'Clinic of Medicine', 'K.G. Jebsen Centre for Genetic Epidemiology']",[Norwegian University of Science and Technology]
87,['Mayo Clinic'],[Mayo Clinic]
88,"['University of Agricultural Sciences and Veterinary Medicine of Cluj-Napoca', 'Biotechnology Research Center', 'Life Sciences Institute King Michael I of Romania', 'Babeș-Bolyai University']","[Universitatea Babeș-Bolyai, Biotechnology Research Center]"
89,"['Graduate Institute of Biomedical Science', 'China Medical University', 'Taichung Tzu Chi Hospital', 'Buddhist Tzu Chi Medical Foundation', 'China Medical University Hospital', 'Asia University', 'Institute of New Drug Development']","[China Medical University Hospital, China Medical University, Tzu Chi University, Buddhist Tzu Chi Medical Foundation]"
90,"['Chongqing University Three Gorges Hospital', 'Center for Medicine Research and Translation', ""Chengdu Fifth People's Hospital""]",[]
91,"['Boston University', 'Shaukat Khanum Memorial Cancer Hospital and Research Centre']","[Shaukat Khanum Memorial Cancer Hospital and Research Center, Boston University]"
92,NaN,[]
93,NaN,[]
94,['Georgetown University Medical Center'],[Georgetown University Medical Center]
95,['University of South Florida'],[University of South Florida]
96,['Johns Hopkins Oncology Center'],[]
97,"['Albert Einstein Cancer Center', 'Montefiore Medical Center']","[Albert Einstein Cancer Center at Montefiore, Montefiore Medical Center]"
98,['General Hospital Manuel Gea Gonzalez'],[Hospital General Dr. Manuel Gea Gonzalez]
99,['University Hospital Leiden'],[Leiden University]
100,['Paul Scherrer Institute'],[Paul Scherrer Institute]
101,['Wayne State University'],[Wayne State University]
102,[],[]