In [1]:
import os
import pandas as pd
import numpy as np

In [8]:
# Path to the .csv files with articles' information
DF_input = input().strip()

  D:\Data_40_years_cancer_studies\BERT_NER_parsedXMLs_combined_until_Oct2025_base\

In [12]:
# Path to the file name with prepared institutions
DF_output = input().strip()

 C:\Users\svalb\OneDrive\Escritorio\Data_40_years_cancer_studies\preparedInstitutionsTestDatabaseAccess_v2.csv

In [10]:
# Import list of csvs to parse
list_csvs = []

for file in os.listdir(DF_input):
    if file[-4:] == ".csv":
        list_csvs.append(file)

n_csvs = len(list_csvs)

In [20]:
list_rows = []

for csv in list_csvs[0:1] + list_csvs[30:]:
    print(f"Parsing csv {csv}")
    df = pd.read_csv(DF_input + csv)
    df = df.loc[df["Authors"].notna()]
    df = df.iloc[2:4]
    list_rows.append(df)
    del df

Parsing csv BERT_NER_parsedXMLs_first_pred_26400.csv
Parsing csv BERT_NER_parsedX_3100000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_3200000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_3300000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_3400000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_3500000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_3600000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_3700000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_3800000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_3900000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_400000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_4000000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_4100000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_4200000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_4300000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_4400000.csv

C:\Users\svalb\AppData\Local\Temp\ipykernel_360\4245863533.py:5: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DF_input + csv)

Parsing csv BERT_NER_parsedX_4454000.csv
Parsing csv BERT_NER_parsedX_500000.csv
Parsing csv BERT_NER_parsedX_600000.csv
Parsing csv BERT_NER_parsedX_700000.csv
Parsing csv BERT_NER_parsedX_800000.csv
Parsing csv BERT_NER_parsedX_900000.csv

In [21]:
df = pd.concat(list_rows)
df = df.reset_index()[["PMID", "Authors", "NER_BERT", "Country"]]

In [22]:
df["Institutions_man"] = None
df["Institutions_man"] = df["Institutions_man"].astype("object")
df["Countries_man"] = None
df["Countries_man"] = df["Countries_man"].astype("object")

In [15]:
df

,PMID,Authors,NER_BERT,Country,Institutions_man,Countries_man
0,20301377,"[{'Name': 'Katy Phelan', 'Affiliation': ['Dire...","[{'entity_group': 'INS', 'score': np.float32(0...",United States,NaN,NaN
1,20301398,"[{'Name': 'Alex F Nisbet', 'Affiliation': [""Ch...","[{'entity_group': 'INS', 'score': np.float32(0...",United States,NaN,NaN
2,39290119,"[{'Name': 'Ali Najafi', 'Affiliation': ['Molec...","[{'entity_group': 'INS', 'score': np.float32(0...",Iran,NaN,NaN
3,39290121,"[{'Name': 'Marziyeh Ghanemi', 'Affiliation': [...","[{'entity_group': 'INS', 'score': np.float32(0...",Iran,NaN,NaN
4,39979457,"[{'Name': 'Kollin Schultz', 'Affiliation': ['A...","[{'entity_group': 'INS', 'score': np.float32(0...",United States,NaN,NaN
...,...,...,...,...,...,...
97,8823341,[],[],NaN,NaN,NaN
98,9556147,"[{'Name': 'C Numata', 'Affiliation': ['Cancer ...","[{'entity_group': 'INS', 'score': np.float32(0...",Japan,NaN,NaN
99,9556164,"[{'Name': 'N Morikawa', 'Affiliation': ['Depar...","[{'entity_group': 'INS', 'score': np.float32(0...",Japan,NaN,NaN
100,10524428,"[{'Name': 'M Mohiuddin', 'Affiliation': ['Depa...","[{'entity_group': 'INS', 'score': np.float32(0...",United States,NaN,NaN
101,10524430,"[{'Name': 'I F Ciernik', 'Affiliation': ['Divi...","[{'entity_group': 'INS', 'score': np.float32(0...",Switzerland,NaN,NaN

In [146]:
df.at[77,"Authors"]

"[{'Name': 'Alexendar R Perez', 'Affiliation': ['Laboratory of Biochemistry and Molecular Biology, National Cancer Institute, Bethesda, MD, USA.', 'Department of Anesthesia and Perioperative Care, University of California, San Francisco, San Francisco, CA, USA.']}, {'Name': 'Laura Sala', 'Affiliation': ['Laboratory of Biochemistry and Molecular Biology, National Cancer Institute, Bethesda, MD, USA.']}, {'Name': 'Richard K Perez', 'Affiliation': ['School of Medicine, University of California, San Francisco, San Francisco, CA, USA.', 'Department of Anesthesiology, Perioperative and Pain Medicine, Stanford University, Palo Alto, CA, USA.']}, {'Name': 'Joana A Vidigal', 'Affiliation': ['Laboratory of Biochemistry and Molecular Biology, National Cancer Institute, Bethesda, MD, USA. joana.vidigal@nih.gov.']}]"

In [147]:

#df.loc[, ["Institutions_man", "Countries_man"]] = pd.Series([[], []],index=["Institutions_man", "Countries_man"])
#df.loc[, ["Institutions_man", "Countries_man"]] = [np.nan, np.nan]

In [134]:
df.loc[0, ["Institutions_man", "Countries_man"]] = pd.Series([["Florida Cancer Specialists and Research Institute", "RCR Genetics", "Clemson University"], ["United States", "United States", "United States"]],index=["Institutions_man", "Countries_man"])
df.loc[1, ["Institutions_man", "Countries_man"]] = pd.Series([["Children's Hospital of Philadelphia", "University of Pennsylvania"], ["United States", "United States"]],index=["Institutions_man", "Countries_man"])
df.loc[2, ["Institutions_man", "Countries_man"]] = pd.Series([["Molecular Biology Research Center", "Biomedicine Technologies Institute", "Baqiyatallah University of Medical Sciences", "Applied Virology Research Center", "Research Institute of Petroleum Industry (RIPI)"], ["Iran", "Iran", "Iran", "Iran", "Iran"]],index=["Institutions_man", "Countries_man"])
df.loc[3, ["Institutions_man", "Countries_man"]] = pd.Series([["Shahed University", "Cellular and Molecular Research Center", "Ahvaz Jundishapur University of Medical Sciences", "Biotechnology Research Center", "Medical Biology Research Center", "Health Technology Institute", "Kermanshah University of Medical Sciences", "Abadan University of Medical Sciences"], ["Iran", "Iran", "Iran", "Iran", "Iran", "Iran", "Iran", "Iran"]],index=["Institutions_man", "Countries_man"])
df.loc[4, ["Institutions_man", "Countries_man"]] = pd.Series([["Abramson Family Cancer Research Institute", "University of Pennsylvania"], ["United States", "United States"]],index=["Institutions_man", "Countries_man"])
df.loc[5, ["Institutions_man", "Countries_man"]] = pd.Series([["University of California", "Center of Immunotherapy and Immunity", "Seattle Children's Research Institute", "Molecular Engineering and Science Institute", "University of Washington", "Brotman-Baty Institute for Precision Medicine", "Molecular Biology Institute", "Jonsson Comprehensive Cancer Center", "Brain Research Institute", "Eli and Edythe Broad Center of Regenerative Medicine and Stem Cell Research", "Partillion Bioscience Corporation", "California NanoSystems Institute (CNSI)"], ["United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States", "United States"]],index=["Institutions_man", "Countries_man"])
df.loc[6, ["Institutions_man", "Countries_man"]] = [np.nan, np.nan]
df.loc[7, ["Institutions_man", "Countries_man"]] = pd.Series([["Kao Autoimmunity Institute", "Cedars-Sinai Medical Center", "University of California", "Samuel Oschin Comprehensive Cancer Institute"], ["United States", "United States", "United States", "United States"]],index=["Institutions_man", "Countries_man"])
df.loc[8, ["Institutions_man", "Countries_man"]] = pd.Series([["University of Cyprus", "National and Kapodistrian University of Athens", "'Aghia Sophia' Children's Hospital", "Center of Clinical, Experimental Surgery and Translational Research", "Biomedical Research Foundation", "Academy of Athens", "NICHD", "NIH"], ["Cyprus", "Greece", "Greece", "Greece", "Greece", "Greece", "United States", "United States"]],index=["Institutions_man", "Countries_man"])
df.loc[9, ["Institutions_man", "Countries_man"]] = pd.Series([["Oregon State University", "Oregon Health & Sciences University"], ["United States", "United States"]],index=["Institutions_man", "Countries_man"])
df.loc[10, ["Institutions_man", "Countries_man"]] = pd.Series([["UMDNJ"], ["United States"]],index=["Institutions_man", "Countries_man"])
df.loc[11, ["Institutions_man", "Countries_man"]] = pd.Series([["Biometric Centre in Therapeutic Studies"], ["Germany"]],index=["Institutions_man", "Countries_man"])
df.loc[12, ["Institutions_man", "Countries_man"]] = pd.Series([["Aichi Cancer Center Research Institute"], ["Japan"]],index=["Institutions_man", "Countries_man"])
df.loc[13, ["Institutions_man", "Countries_man"]] = pd.Series([["Paterson Institute for Cancer Research", "Christie CRC Research Centre"], ["United Kingdom", "United Kingdom"]],index=["Institutions_man", "Countries_man"])
df.loc[14, ["Institutions_man", "Countries_man"]] = pd.Series([["University of Texas Health Science Center"], ["United States"]],index=["Institutions_man", "Countries_man"])
df.loc[15, ["Institutions_man", "Countries_man"]] = pd.Series([["Karolinska Institute & Hospital"], ["Sweden"]],index=["Institutions_man", "Countries_man"])
df.loc[16, ["Institutions_man", "Countries_man"]] = pd.Series([["Institute for Clinical Immunology", "Friedrich Alexander University of Erlangen-Nuremberg"], ["Germany", "Germany"]],index=["Institutions_man", "Countries_man"])
df.loc[17, ["Institutions_man", "Countries_man"]] = pd.Series([["Klinik für Radiologie", "Friedrich-Schiller-Universität Jena"], ["Germany", "Germany"]],index=["Institutions_man", "Countries_man"])
df.loc[18, ["Institutions_man", "Countries_man"]] = pd.Series([["Kyung Hee University"], ["South Korea"]],index=["Institutions_man", "Countries_man"])
df.loc[19, ["Institutions_man", "Countries_man"]] = pd.Series([["Jichi Medical School"], ["Japan"]],index=["Institutions_man", "Countries_man"])
df.loc[20, ["Institutions_man", "Countries_man"]] = pd.Series([["National University Corporation", "University of Toyama"], ["Japan", "Japan"]],index=["Institutions_man", "Countries_man"])
df.loc[21, ["Institutions_man", "Countries_man"]] = pd.Series([["Academy of Medical Sciences and Technology", "Academy Charity Teaching Hospital"], ["Sudan", "Sudan"]],index=["Institutions_man", "Countries_man"])
df.loc[22, ["Institutions_man", "Countries_man"]] = pd.Series([["Clinical Center for Tumor Therapy", "2nd Affiliated Hospital", "Institute of Ultrasonic Engineering in Medicine", "Chongqing University of Medical Sciences"], ["China", "China", "China", "China"]],index=["Institutions_man", "Countries_man"])
df.loc[23, ["Institutions_man", "Countries_man"]] = pd.Series([["Niigata University"], ["Japan"]],index=["Institutions_man", "Countries_man"])
df.loc[24, ["Institutions_man", "Countries_man"]] = pd.Series([["National Tuberculosis and Lung Diseases Research Institute"], ["Poland"]],index=["Institutions_man", "Countries_man"])
df.loc[25, ["Institutions_man", "Countries_man"]] = pd.Series([["Radboud University Nijmegen Medical Centre"], ["The Netherlands"]],index=["Institutions_man", "Countries_man"])
df.loc[26, ["Institutions_man", "Countries_man"]] = pd.Series([["Stem Cell Research Center", "Korea Research Institute of Bioscience and Biotechnology"], ["South Korea", "South Korea"]],index=["Institutions_man", "Countries_man"])
df.loc[27, ["Institutions_man", "Countries_man"]] = pd.Series([["Wooridul Spine Hospital"], ["South Korea"]],index=["Institutions_man", "Countries_man"])
df.loc[28, ["Institutions_man", "Countries_man"]] = pd.Series([["University of Veterinary Medicine"], ["Germany"]],index=["Institutions_man", "Countries_man"])
df.loc[29, ["Institutions_man", "Countries_man"]] = pd.Series([["University of Applied Sciences"], ["Switzerland"]],index=["Institutions_man", "Countries_man"])
df.loc[30, ["Institutions_man", "Countries_man"]] = pd.Series([["Guangdong Lung Cancer Institute", "Guangdong General Hospital", "Guangdong Academy of Medical Sciences"], ["China", "China", "China"]],index=["Institutions_man", "Countries_man"])
df.loc[31, ["Institutions_man", "Countries_man"]] = pd.Series([["Shanghai Chest Hospital", "Shanghai Jiaotong University"], ["China", "China"]],index=["Institutions_man", "Countries_man"])
df.loc[32, ["Institutions_man", "Countries_man"]] = pd.Series([["National University Hospital"], ["Singapore"]],index=["Institutions_man", "Countries_man"])
df.loc[33, ["Institutions_man", "Countries_man"]] = pd.Series([["Boston University Medical Center"], ["United States"]],index=["Institutions_man", "Countries_man"])
df.loc[34, ["Institutions_man", "Countries_man"]] = pd.Series([["Semmelweis University"], ["Hungary"]],index=["Institutions_man", "Countries_man"])
df.loc[35, ["Institutions_man", "Countries_man"]] = pd.Series([["Clinic of Transplantation and Surgery", "Semmelweis University"], ["Hungary", "Hungary"]],index=["Institutions_man", "Countries_man"])
df.loc[36, ["Institutions_man", "Countries_man"]] = pd.Series([["Georgia Health Sciences University"], ["United States"]],index=["Institutions_man", "Countries_man"])
df.loc[37, ["Institutions_man", "Countries_man"]] = pd.Series([["University of Sydney"], ["Australia"]],index=["Institutions_man", "Countries_man"])
df.loc[38, ["Institutions_man", "Countries_man"]] = pd.Series([["Haartman Institute", "University of Helsinki", "Helsinki University Central Hospital"], ["Finland", "Finland", "Finland"]],index=["Institutions_man", "Countries_man"])
df.loc[39, ["Institutions_man", "Countries_man"]] = pd.Series([["Kyung Hee University"], ["South Korea"]],index=["Institutions_man", "Countries_man"])
df.loc[40, ["Institutions_man", "Countries_man"]] = pd.Series([["Comissão de Controle de Infecção Hospitalar", "Hospital das Clínicas", "Universidade de São Paulo"], ["Brazil", "Brazil", "Brazil"]],index=["Institutions_man", "Countries_man"])
df.loc[41, ["Institutions_man", "Countries_man"]] = pd.Series([["Johns Hopkins University"], ["United States"]],index=["Institutions_man", "Countries_man"])
df.loc[42, ["Institutions_man", "Countries_man"]] = pd.Series([["Erasmus MC Cancer Institute", "Radboud University Nijmegen Medical Center"], ["The Netherlands", "The Netherlands"]],index=["Institutions_man", "Countries_man"])
df.loc[43, ["Institutions_man", "Countries_man"]] = pd.Series([["China Medical University Hospital", "Taipei Medical University", "China Medical University", "Chi-Mei Hospital", "Taipei Medical University Hospital"], ["Taiwan","Taiwan","Taiwan","Taiwan","Taiwan"]],index=["Institutions_man", "Countries_man"])
df.loc[44, ["Institutions_man", "Countries_man"]] = pd.Series([["Nanjing First Hospital", "Nanjing Medical University"], ["China","China"]],index=["Institutions_man", "Countries_man"])
df.loc[45, ["Institutions_man", "Countries_man"]] = pd.Series([["Tumor Hospital"], ["China"]],index=["Institutions_man", "Countries_man"])
df.loc[46, ["Institutions_man", "Countries_man"]] = [np.nan, np.nan]
df.loc[47, ["Institutions_man", "Countries_man"]] = [np.nan, np.nan]
df.loc[48, ["Institutions_man", "Countries_man"]] = pd.Series([["Zahedan University of Medical Sciences", "Cellular and Molecular Research Center", "Genetic of non-communicable disease research Center", "University of Manitoba"], ["Iran", "Iran", "Iran", "Canada"]],index=["Institutions_man", "Countries_man"])
df.loc[49, ["Institutions_man", "Countries_man"]] = pd.Series([["Payame Noor University", "Shahid Beheshti University of Medical Sciences", "Pediatric Infections Research Center", "Mofid Children Hospital", "Zabol University of Medical Sciences"], ["Iran", "Iran", "Iran", "Iran", "Iran"]],index=["Institutions_man", "Countries_man"])
df.loc[50, ["Institutions_man", "Countries_man"]] = [np.nan, np.nan]
df.loc[51, ["Institutions_man", "Countries_man"]] = [np.nan, np.nan]
df.loc[52, ["Institutions_man", "Countries_man"]] = pd.Series([["Hospital for Sick Children", "University of Toronto", "Research Institute", "Princess Margaret Hospital"], ["Canada", "Canada", "Canada", "Canada"]],index=["Institutions_man", "Countries_man"])
df.loc[53, ["Institutions_man", "Countries_man"]] = pd.Series([["University of Kansas"], ["United States"]],index=["Institutions_man", "Countries_man"])
df.loc[54, ["Institutions_man", "Countries_man"]] = [np.nan, np.nan]
df.loc[55, ["Institutions_man", "Countries_man"]] = [np.nan, np.nan]
df.loc[56, ["Institutions_man", "Countries_man"]] = pd.Series([["St John of God Hospital", "St Vincent's Hospital", "University of Melbourne", "Olivia Newton-John Cancer Research Institute", "La Trobe University", "Peter MacCallum Cancer Centre"], ["Australia", "Australia", "Australia", "Australia", "Australia", "Australia"]],index=["Institutions_man", "Countries_man"])
df.loc[57, ["Institutions_man", "Countries_man"]] = pd.Series([["Seoul National University Hospital", "SMG-SNU Boramae Medical Center", "Kyunghee University Hospital", "Seoul National University"], ["South Korea", "South Korea", "South Korea", "South Korea"]],index=["Institutions_man", "Countries_man"])
df.loc[58, ["Institutions_man", "Countries_man"]] = [np.nan, np.nan]
df.loc[59, ["Institutions_man", "Countries_man"]] = [np.nan, np.nan]
df.loc[60, ["Institutions_man", "Countries_man"]] = pd.Series([["Shiraz University of Medical Sciences"], ["Iran"]],index=["Institutions_man", "Countries_man"])
df.loc[61, ["Institutions_man", "Countries_man"]] = pd.Series([["Hamadan University of Medical Sciences"], ["Iran"]],index=["Institutions_man", "Countries_man"])
df.loc[62, ["Institutions_man", "Countries_man"]] = pd.Series([["Capital Medical University Cancer Center", "Beijing Shijitan Hospital", "Beijing Institute of Biotechnology", "Jilin University"], ["China", "China", "China", "China"]],index=["Institutions_man", "Countries_man"])
df.loc[63, ["Institutions_man", "Countries_man"]] = pd.Series([["Bakirkoy Dr. Sadi Konuk Education and Research Hospital", "Gazi University", "Akdeniz University", "Ankara Numune Education and Research Hospital"], ["Türkiye", "Türkiye", "Türkiye", "Türkiye"]],index=["Institutions_man", "Countries_man"])
df.loc[64, ["Institutions_man", "Countries_man"]] = pd.Series([["Nicolaus Copernicus University", "Kuyavian and Pomeranian Pulmonology Centre"], ["Poland", "Poland"]],index=["Institutions_man", "Countries_man"])
df.loc[65, ["Institutions_man", "Countries_man"]] = pd.Series([["King's College London", "Global Health Institute", "American University of Beirut", "London School of Hygiene and Tropical Medicine", "Institute of Cancer Policy"], ["United Kingdom", "Lebanon", "Lebanon", "United Kingdom", "United Kingdom"]],index=["Institutions_man", "Countries_man"])
df.loc[66, ["Institutions_man", "Countries_man"]] = pd.Series([["Shanghai University", "Fudan Institute of Urology", "Fudan University"], ["China", "China", "China"]],index=["Institutions_man", "Countries_man"])
df.loc[67, ["Institutions_man", "Countries_man"]] = pd.Series([["Sapienza University of Rome", "Istituto Pasteur Italia", "Fondazione Cenci Bolognetti", "Regina Elena National Cancer Institute", "University G. d'Annunzio"], ["Italy", "Italy", "Italy", "Italy", "Italy"]],index=["Institutions_man", "Countries_man"])
df.loc[68, ["Institutions_man", "Countries_man"]] = pd.Series([["Danish Cancer Society Research Center", "Center for Autophagy, Recycling and Disease", "University of Copenhagen", "Novo Nordisk Foundation Center for Protein Research"], ["Denmark", "Denmark", "Denmark", "Denmark"]],index=["Institutions_man", "Countries_man"])
df.loc[69, ["Institutions_man", "Countries_man"]] = pd.Series([["Sarah W. Stedman Nutrition and Metabolism Center", "Duke University Medical Center", "Duke Molecular Physiology Institute", "Genomics Institute of the Novartis Research Foundation"], ["United States","United States","United States","United States"]],index=["Institutions_man", "Countries_man"])
df.loc[70, ["Institutions_man", "Countries_man"]] = pd.Series([["Tongji Hospital", "Huazhong University of Science and Technology"], ["China", "China"]],index=["Institutions_man", "Countries_man"])
df.loc[71, ["Institutions_man", "Countries_man"]] = pd.Series([["Sichuan University"], ["China"]],index=["Institutions_man", "Countries_man"])
df.loc[72, ["Institutions_man", "Countries_man"]] = pd.Series([["Indiana University", "Purdue University", "Center for Health Services Research", "Regenstrief Institute, Inc."], ["United States", "United States", "United States", "United States"]],index=["Institutions_man", "Countries_man"])
df.loc[73, ["Institutions_man", "Countries_man"]] = pd.Series([["Zengcheng District People's Hospital", "BoJi-Affiliated Hospital", "Sun Yat-sen University", "Sun Yat-sen Memorial Hospital"], ["China", "China", "China", "China"]],index=["Institutions_man", "Countries_man"])
df.loc[74, ["Institutions_man", "Countries_man"]] = pd.Series([["Institute of Antibody Engineering", "Southern Medical University", "First People's Hospital", "Sun Yat-Sen Memorial Hospital", "Sun Yat-Sen University", "Guangzhou Darui Biotechnology Co., Ltd."], ["China", "China", "China", "China", "China", "China"]],index=["Institutions_man", "Countries_man"])
df.loc[75, ["Institutions_man", "Countries_man"]] = pd.Series([["Southwest Hospital", "Army Medical University", "Third Military Medical University"], ["China", "China", "China"]],index=["Institutions_man", "Countries_man"])
df.loc[76, ["Institutions_man", "Countries_man"]] = pd.Series([["First Affiliated Hospital", "Xi'an Jiaotong University"], ["China", "China"]],index=["Institutions_man", "Countries_man"])
df.loc[77, ["Institutions_man", "Countries_man"]] = pd.Series([["National Cancer Institute", "University of California", "Stanford University"], ["United States","United States","United States"]],index=["Institutions_man", "Countries_man"])

In [20]:
df

,PMID,Authors,NER_BERT,Country,Institutions_man,Countries_man
0,20301377,"[{'Name': 'Katy Phelan', 'Affiliation': ['Dire...","[{'entity_group': 'INS', 'score': np.float32(0...",United States,[Florida Cancer Specialists and Research Insti...,"[United States, United States, United States]"
1,20301398,"[{'Name': 'Alex F Nisbet', 'Affiliation': [""Ch...","[{'entity_group': 'INS', 'score': np.float32(0...",United States,"[Children's Hospital of Philadelphia, Universi...","[United States, United States]"
2,39290119,"[{'Name': 'Ali Najafi', 'Affiliation': ['Molec...","[{'entity_group': 'INS', 'score': np.float32(0...",Iran,"[Molecular Biology Research Center, Biomedicin...","[Iran, Iran, Iran, Iran]"
3,39290121,"[{'Name': 'Marziyeh Ghanemi', 'Affiliation': [...","[{'entity_group': 'INS', 'score': np.float32(0...",Iran,NaN,NaN
4,39979457,"[{'Name': 'Kollin Schultz', 'Affiliation': ['A...","[{'entity_group': 'INS', 'score': np.float32(0...",United States,NaN,NaN
...,...,...,...,...,...,...
97,8823341,[],[],NaN,NaN,NaN
98,9556147,"[{'Name': 'C Numata', 'Affiliation': ['Cancer ...","[{'entity_group': 'INS', 'score': np.float32(0...",Japan,NaN,NaN
99,9556164,"[{'Name': 'N Morikawa', 'Affiliation': ['Depar...","[{'entity_group': 'INS', 'score': np.float32(0...",Japan,NaN,NaN
100,10524428,"[{'Name': 'M Mohiuddin', 'Affiliation': ['Depa...","[{'entity_group': 'INS', 'score': np.float32(0...",United States,NaN,NaN
101,10524430,"[{'Name': 'I F Ciernik', 'Affiliation': ['Divi...","[{'entity_group': 'INS', 'score': np.float32(0...",Switzerland,NaN,NaN

In [24]:
# Save the prepared institutions dataset
df.to_csv(DF_output, index = False)